<?php

namespace Database\Seeders;

use App\Models\MarketplaceCity;
use Illuminate\Database\Seeder;

/**
 * Backfill marketplace_cities.getyourguide_city_id for bilete.online's
 * city catalogue. Generated by tools/gyg-city-scraper/generate_seeder.py
 * from out.csv on {datetime} — re-run that script if the scrape is
 * refreshed.
 *
 * Idempotent: each row updates by primary key, so running the seeder
 * twice produces no duplicates and no overwrites of any value already
 * matching what's in the script.
 *
 * Coverage of this run: 48 cities auto-seeded.
 *
 * Rows that DIDN'T make it into this seeder live in
 * tools/gyg-city-scraper/review.csv with a per-row reason:
 *   - country: GYG returned the whole-Romania page (id 169162); widget
 *     would be too broad. SKIPPED — no value in widget.
 *   - wrong:   low-confidence match with a non-county slug (e.g. Bran
 *     hit Tirana). SKIPPED — would surface bad activities.
 *   - review:  high-confidence match but the slug looks suspicious
 *     (e.g. Slănic Moldova -> /slanic-l…/). Verify manually before
 *     adding via tinker.
 *   - not_found: GYG has no page for this city; leave the column NULL,
 *     widget simply doesn't render.
 */
class AddGetyourguideCityIdsSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            ['id' => 789, 'gyg_id' => '111'], // București -> bucuresti
            ['id' => 794, 'gyg_id' => '185106'], // Pantelimon -> judetul-ilfov
            ['id' => 795, 'gyg_id' => '185106'], // Otopeni -> judetul-ilfov
            ['id' => 798, 'gyg_id' => '2393'], // Cluj-Napoca -> cluj-napoca
            ['id' => 799, 'gyg_id' => '144427'], // Turda -> judetul-cluj
            ['id' => 800, 'gyg_id' => '144427'], // Dej -> judetul-cluj
            ['id' => 802, 'gyg_id' => '144427'], // Gherla -> judetul-cluj
            ['id' => 816, 'gyg_id' => '2660'], // Constanța -> judetul-constanta
            ['id' => 821, 'gyg_id' => '2660'], // Mamaia -> judetul-constanta
            ['id' => 822, 'gyg_id' => '2660'], // Eforie Nord -> judetul-constanta
            ['id' => 827, 'gyg_id' => '2003'], // Brașov -> brasov
            ['id' => 828, 'gyg_id' => '182616'], // Făgăraș -> judetul-brasov
            ['id' => 831, 'gyg_id' => '2004'], // Râșnov -> rasnov
            ['id' => 832, 'gyg_id' => '182616'], // Zărnești -> judetul-brasov
            ['id' => 833, 'gyg_id' => '182616'], // Predeal -> judetul-brasov
            ['id' => 834, 'gyg_id' => '182616'], // Poiana Brașov -> judetul-brasov
            ['id' => 841, 'gyg_id' => '186732'], // Câmpina -> judetul-prahova
            ['id' => 844, 'gyg_id' => '124688'], // Sinaia -> sinaia
            ['id' => 845, 'gyg_id' => '234246'], // Bușteni -> busteni
            ['id' => 846, 'gyg_id' => '186732'], // Azuga -> judetul-prahova
            ['id' => 849, 'gyg_id' => '1833'], // Sibiu -> sibiu
            ['id' => 850, 'gyg_id' => '144426'], // Mediaș -> judetul-sibiu
            ['id' => 851, 'gyg_id' => '144426'], // Cisnădie -> judetul-sibiu
            ['id' => 852, 'gyg_id' => '144426'], // Avrig -> judetul-sibiu
            ['id' => 855, 'gyg_id' => '144426'], // Păltiniș -> judetul-sibiu
            ['id' => 856, 'gyg_id' => '144429'], // Târgu Mureș -> judetul-mures
            ['id' => 858, 'gyg_id' => '2012'], // Sighișoara -> sighisoara
            ['id' => 859, 'gyg_id' => '144429'], // Târnăveni -> judetul-mures
            ['id' => 871, 'gyg_id' => '201945'], // Pitești -> arges
            ['id' => 872, 'gyg_id' => '201945'], // Câmpulung -> arges
            ['id' => 873, 'gyg_id' => '201945'], // Curtea de Argeș -> arges
            ['id' => 900, 'gyg_id' => '2510'], // Deva -> judetul-alba
            ['id' => 901, 'gyg_id' => '2510'], // Hunedoara -> judetul-alba
            ['id' => 909, 'gyg_id' => '257948'], // Suceava -> judetul-suceava
            ['id' => 912, 'gyg_id' => '201945'], // Câmpulung Moldovenesc -> arges
            ['id' => 914, 'gyg_id' => '257948'], // Gura Humorului -> judetul-suceava
            ['id' => 916, 'gyg_id' => '2510'], // Alba Iulia -> judetul-alba
            ['id' => 917, 'gyg_id' => '2510'], // Aiud -> judetul-alba
            ['id' => 918, 'gyg_id' => '2510'], // Blaj -> judetul-alba
            ['id' => 919, 'gyg_id' => '2510'], // Sebeș -> judetul-alba
            ['id' => 920, 'gyg_id' => '2510'], // Cugir -> judetul-alba
            ['id' => 921, 'gyg_id' => '144429'], // Ocna Mureș -> judetul-mures
            ['id' => 944, 'gyg_id' => '169139'], // Moldova Nouă -> moldova
            ['id' => 957, 'gyg_id' => '185430'], // Târgoviște -> judetul-dambovita
            ['id' => 1023, 'gyg_id' => '490'], // Alexandria -> alexandria
            ['id' => 1028, 'gyg_id' => '2659'], // Tulcea -> tulcea
            ['id' => 1032, 'gyg_id' => '2658'], // Sulina -> judetul-tulcea
            ['id' => 1033, 'gyg_id' => '2658'], // Murighiol -> judetul-tulcea
        ];

        foreach ($rows as $row) {
            MarketplaceCity::where('id', $row['id'])
                ->update(['getyourguide_city_id' => $row['gyg_id']]);
        }

        $this->command->info(sprintf(
            'Updated GetYourGuide city ids for %d marketplace_cities rows.',
            count($rows)
        ));
    }
}
