<?php

namespace App\Services;

use App\Models\FestivalEdition;
use App\Models\Vendor;
use App\Models\VendorEdition;
use App\Models\VendorSaleItem;
use App\Models\Wristband;
use App\Models\WristbandTransaction;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class NfcSyncService
{
    /**
     * Sync a batch of offline NFC transactions from a terminal.
     *
     * Each transaction in the batch should contain:
     * - offline_ref: string (unique idempotency key generated by terminal)
     * - uid: string (wristband UID)
     * - transaction_type: string (payment|topup|refund)
     * - amount_cents: int
     * - balance_after_cents: int (balance on chip after transaction)
     * - transacted_at: string (ISO 8601 timestamp of when it happened)
     * - vendor_id: int (optional)
     * - pos_device_id: int (optional)
     * - pos_device_uid: string (optional)
     * - employee_id: int (optional)
     * - shift_id: int (optional)
     * - operator: string (optional)
     * - payment_method: string (optional, for topups)
     * - items: array (optional, for payments — same format as charge endpoint)
     *
     * @return array Array of results per transaction: ['offline_ref' => string, 'status' => string, 'message' => ?string]
     */
    public function syncBatch(array $transactions, int $editionId, int $tenantId): array
    {
        $edition = FestivalEdition::findOrFail($editionId);
        $results = [];

        foreach ($transactions as $tx) {
            $results[] = $this->syncOne($tx, $edition, $tenantId);
        }

        return $results;
    }

    private function syncOne(array $tx, FestivalEdition $edition, int $tenantId): array
    {
        $offlineRef = $tx['offline_ref'] ?? null;

        if (! $offlineRef) {
            return ['offline_ref' => null, 'status' => 'error', 'message' => 'Missing offline_ref'];
        }

        // Duplicate check
        $exists = WristbandTransaction::where('offline_ref', $offlineRef)->exists();
        if ($exists) {
            return ['offline_ref' => $offlineRef, 'status' => 'duplicate'];
        }

        $wristband = Wristband::where('uid', $tx['uid'] ?? '')->first();
        if (! $wristband) {
            return ['offline_ref' => $offlineRef, 'status' => 'wristband_not_found'];
        }

        try {
            return DB::transaction(function () use ($tx, $edition, $tenantId, $wristband, $offlineRef) {
                $locked = Wristband::lockForUpdate()->find($wristband->id);
                $serverBalanceBefore = $locked->balance_cents;

                $amountCents = (int) $tx['amount_cents'];
                $type = $tx['transaction_type'];
                $chipBalanceAfter = (int) ($tx['balance_after_cents'] ?? 0);

                // Calculate new server balance based on transaction type
                if (in_array($type, ['payment', 'cashout'])) {
                    $newServerBalance = $serverBalanceBefore - $amountCents;
                } else {
                    $newServerBalance = $serverBalanceBefore + $amountCents;
                }

                // Check reconciliation: chip balance should match server after applying
                $isReconciled = ($chipBalanceAfter === $newServerBalance);

                if (! $isReconciled) {
                    Log::warning('NFC sync balance mismatch', [
                        'offline_ref'          => $offlineRef,
                        'wristband_uid'        => $wristband->uid,
                        'chip_balance_after'   => $chipBalanceAfter,
                        'server_balance_after'  => $newServerBalance,
                        'server_balance_before' => $serverBalanceBefore,
                    ]);

                    // Trust the chip — adjust server to match
                    $newServerBalance = $chipBalanceAfter;
                }

                $locked->update(['balance_cents' => $newServerBalance]);

                $transaction = WristbandTransaction::create([
                    'wristband_id'          => $wristband->id,
                    'tenant_id'             => $tenantId,
                    'festival_edition_id'   => $edition->id,
                    'customer_id'           => $wristband->customer_id,
                    'transaction_type'      => $type,
                    'amount_cents'          => $amountCents,
                    'balance_before_cents'  => $serverBalanceBefore,
                    'balance_after_cents'   => $newServerBalance,
                    'currency'              => $wristband->currency,
                    'vendor_name'           => $tx['vendor_name'] ?? null,
                    'vendor_location'       => $tx['vendor_location'] ?? null,
                    'vendor_id'             => $tx['vendor_id'] ?? null,
                    'vendor_pos_device_id'  => $tx['pos_device_id'] ?? null,
                    'payment_method'        => $tx['payment_method'] ?? null,
                    'operator'              => $tx['operator'] ?? null,
                    'description'           => $tx['description'] ?? 'NFC offline sync',
                    'sync_source'           => 'offline_sync',
                    'offline_ref'           => $offlineRef,
                    'offline_transacted_at' => $tx['transacted_at'] ?? null,
                    'is_reconciled'         => $isReconciled,
                ]);

                // Create sale items for payments
                if ($type === 'payment' && ! empty($tx['items'])) {
                    $this->createSaleItems($tx, $transaction, $edition, $wristband);
                }

                // Update shift counters
                if ($type === 'payment' && ! empty($tx['shift_id'])) {
                    \App\Models\VendorShift::find($tx['shift_id'])?->recordSale($amountCents);
                }

                // Update POS heartbeat
                if (! empty($tx['pos_device_id'])) {
                    \App\Models\VendorPosDevice::find($tx['pos_device_id'])?->heartbeat();
                }

                return [
                    'offline_ref'    => $offlineRef,
                    'status'         => 'synced',
                    'is_reconciled'  => $isReconciled,
                    'server_balance' => $newServerBalance,
                ];
            });
        } catch (\Throwable $e) {
            Log::error('NFC sync transaction failed', [
                'offline_ref' => $offlineRef,
                'error'       => $e->getMessage(),
            ]);

            return ['offline_ref' => $offlineRef, 'status' => 'error', 'message' => $e->getMessage()];
        }
    }

    private function createSaleItems(array $tx, WristbandTransaction $transaction, FestivalEdition $edition, Wristband $wristband): void
    {
        $vendorId = $tx['vendor_id'] ?? null;
        $vendorEdition = null;

        if ($vendorId) {
            $vendorEdition = VendorEdition::where('vendor_id', $vendorId)
                ->where('festival_edition_id', $edition->id)
                ->first();
        }

        foreach ($tx['items'] as $item) {
            $lineTotal = ($item['quantity'] ?? 1) * ($item['unit_price_cents'] ?? 0);
            $commissionRate = $vendorEdition?->commission_rate ?? 0;
            $commissionCents = $vendorEdition ? $vendorEdition->calculateCommission($lineTotal) : 0;

            VendorSaleItem::create([
                'vendor_id'                => $vendorId,
                'festival_edition_id'      => $edition->id,
                'vendor_product_id'        => $item['product_id'] ?? null,
                'wristband_transaction_id' => $transaction->id,
                'vendor_pos_device_id'     => $tx['pos_device_id'] ?? null,
                'vendor_employee_id'       => $tx['employee_id'] ?? null,
                'vendor_shift_id'          => $tx['shift_id'] ?? null,
                'product_name'             => $item['name'] ?? 'Unknown',
                'category_name'            => $item['category'] ?? null,
                'variant_name'             => $item['variant'] ?? null,
                'quantity'                 => $item['quantity'] ?? 1,
                'unit_price_cents'         => $item['unit_price_cents'] ?? 0,
                'total_cents'              => $lineTotal,
                'currency'                 => $wristband->currency,
                'commission_cents'         => $commissionCents,
                'commission_rate'          => $commissionRate,
                'operator'                 => $tx['operator'] ?? null,
            ]);
        }
    }
}
