<?php

namespace App\Policies\Marketplace;

use App\Models\Marketplace\MarketplaceOrganizerUser;
use App\Models\Marketplace\MarketplacePayout;

/**
 * Policy for payouts in the Organizer panel.
 * Ensures organizers can only view their own payouts.
 */
class OrganizerPayoutPolicy
{
    /**
     * Determine whether the user can view any payouts.
     */
    public function viewAny(MarketplaceOrganizerUser $user): bool
    {
        return true; // Query is scoped by organizer_id in resource
    }

    /**
     * Determine whether the user can view the payout.
     */
    public function view(MarketplaceOrganizerUser $user, MarketplacePayout $payout): bool
    {
        return $payout->organizer_id === $user->organizer_id;
    }

    /**
     * Determine whether the user can create payouts.
     */
    public function create(MarketplaceOrganizerUser $user): bool
    {
        return false; // Payouts are generated by the marketplace
    }

    /**
     * Determine whether the user can update the payout.
     */
    public function update(MarketplaceOrganizerUser $user, MarketplacePayout $payout): bool
    {
        return false; // Organizers cannot modify payouts
    }

    /**
     * Determine whether the user can delete the payout.
     */
    public function delete(MarketplaceOrganizerUser $user, MarketplacePayout $payout): bool
    {
        return false; // Payouts cannot be deleted
    }

    /**
     * Determine whether the user can restore the payout.
     */
    public function restore(MarketplaceOrganizerUser $user, MarketplacePayout $payout): bool
    {
        return false;
    }

    /**
     * Determine whether the user can permanently delete the payout.
     */
    public function forceDelete(MarketplaceOrganizerUser $user, MarketplacePayout $payout): bool
    {
        return false;
    }
}
