<!DOCTYPE html>
<html lang="ro" class="scroll-smooth">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
  <meta name="robots" content="noindex, nofollow">
  <meta name="theme-color" content="#061a15">
  <title>Contact și suport — Nordvale</title>
  <meta name="description" content="Contact și suport public pentru tenantul leisure Nordvale, powered by Tixello.">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Fraunces:opsz,wght@9..144,500;9..144,600;9..144,700&display=swap" rel="stylesheet">
  <style>
    :root{
      --pine-950:#061a15;--pine-900:#09251d;--pine-850:#0d3027;--pine-800:#123b30;--pine-700:#1b5242;
      --acid:#dffc62;--ember:#f27b4a;--cream:#fffdf6;--oat:#f0ecdf;--moss:#b7c9a3;--ink:#16231e;--sky:#b8dce0;
      --line:rgba(9,37,29,.12);--shadow:0 30px 90px -48px rgba(6,26,21,.5);--shadow-dark:0 32px 90px -44px rgba(0,0,0,.64);
      --display:'Fraunces',serif;--sans:'DM Sans',sans-serif
    }
    *{box-sizing:border-box}html{background:var(--oat);scroll-behavior:smooth}body{margin:0;overflow-x:hidden;background:var(--oat);color:var(--ink);font-family:var(--sans);text-rendering:optimizeLegibility}body.menu-open,body.modal-open{overflow:hidden}button,input,textarea,select{font:inherit}button,a{-webkit-tap-highlight-color:transparent}a{color:inherit;text-decoration:none}img{display:block;max-width:100%}::selection{background:var(--acid);color:var(--pine-950)}
    .display{font-family:var(--display)}.wrap{width:min(1240px,calc(100% - 40px));margin-inline:auto}.safe-top{padding-top:max(12px,env(safe-area-inset-top))}.safe-bottom{padding-bottom:max(16px,env(safe-area-inset-bottom))}
    .paper-grid{background-image:linear-gradient(rgba(9,37,29,.045) 1px,transparent 1px),linear-gradient(90deg,rgba(9,37,29,.045) 1px,transparent 1px);background-size:30px 30px}
    .topo-dark{background-image:radial-gradient(circle at 16% 24%,rgba(223,252,98,.13),transparent 23%),radial-gradient(circle at 82% 18%,rgba(242,123,74,.12),transparent 20%),url("data:image/svg+xml,%3Csvg width='900' height='900' viewBox='0 0 900 900' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' stroke='%23ffffff' stroke-opacity='.055' stroke-width='1.2'%3E%3Cpath d='M89 231c42-122 183-201 313-145 107 46 128 172 65 257-59 80-174 69-233 151-61 84-48 222-161 268-110 45-231-48-204-166 26-111 147-116 166-218 11-59-4-101 54-147Z'/%3E%3Cpath d='M142 267c31-91 136-151 233-109 80 34 95 128 48 191-44 59-129 51-174 112-45 63-35 165-120 199-82 34-172-35-152-123 20-83 110-86 124-163 8-44-3-75 41-107Z'/%3E%3Cpath d='M544 451c64-92 184-122 271-53 84 66 66 191-18 247-77 51-172 20-232 89-53 60-38 153-115 177-85 26-166-52-138-136 27-77 119-76 162-146 34-55 34-119 70-178Z'/%3E%3Cpath d='M584 484c47-69 138-91 202-40 63 49 49 142-14 184-57 38-128 15-173 66-40 45-28 114-85 132-64 20-124-39-103-101 20-57 89-56 121-108 26-41 26-89 52-133Z'/%3E%3C/g%3E%3C/svg%3E");background-size:auto,auto,900px 900px}
    .grain{position:relative}.grain::after{content:'';position:absolute;inset:0;z-index:2;pointer-events:none;opacity:.08;mix-blend-mode:soft-light;background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 180 180' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.82' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.55'/%3E%3C/svg%3E")}
    #scrollProgress{position:fixed;z-index:180;top:0;left:0;width:100%;height:3px;background:var(--acid);transform:scaleX(0);transform-origin:left center}
    .site-header{position:fixed;inset:0 0 auto;z-index:120;padding-inline:20px;pointer-events:none}.nav{width:min(1240px,100%);height:72px;margin:0 auto;display:flex;align-items:center;justify-content:space-between;gap:20px;padding:0 14px 0 18px;color:white;border:1px solid rgba(255,255,255,.12);border-radius:24px;background:rgba(6,26,21,.72);backdrop-filter:blur(22px) saturate(130%);box-shadow:0 22px 60px -42px rgba(0,0,0,.92);pointer-events:auto;transition:.35s ease}.nav.scrolled{height:64px;margin-top:6px;background:rgba(6,26,21,.9)}
    .brand{display:inline-flex;align-items:center;gap:11px;min-width:0}.brand-mark{width:42px;height:42px;display:grid;place-items:center;border-radius:15px;background:var(--acid);color:var(--pine-950);flex:none}.brand-name{display:block;font-family:var(--display);font-size:20px;font-weight:700;line-height:1}.brand-sub{display:block;margin-top:4px;font-size:8px;font-weight:700;text-transform:uppercase;letter-spacing:.16em;color:rgba(255,255,255,.5);white-space:nowrap}
    .nav-links{display:flex;align-items:center;gap:25px;font-size:12px;font-weight:700}.nav-links a{color:rgba(255,255,255,.76);transition:.2s}.nav-links a:hover,.nav-links a.active{color:white}.nav-actions{display:flex;align-items:center;gap:9px}.nav-icon{width:42px;height:42px;display:grid;place-items:center;border:1px solid rgba(255,255,255,.12);border-radius:15px;background:rgba(255,255,255,.05);color:white;cursor:pointer}.ticket-btn{height:42px;padding:0 17px;display:inline-flex;align-items:center;justify-content:center;border-radius:14px;background:var(--acid);color:var(--pine-950);font-size:11px;font-weight:800;white-space:nowrap}.mobile-trigger{display:none}
    .mobile-menu{position:fixed;inset:0;z-index:160;visibility:hidden;pointer-events:none}.mobile-menu.open{visibility:visible;pointer-events:auto}.menu-backdrop{position:absolute;inset:0;background:rgba(3,15,12,.72);opacity:0;transition:.3s}.mobile-menu.open .menu-backdrop{opacity:1}.menu-panel{position:absolute;top:0;right:0;width:min(420px,92vw);height:100%;padding:24px;background:var(--cream);transform:translateX(100%);transition:.38s cubic-bezier(.2,.75,.2,1);overflow:auto}.mobile-menu.open .menu-panel{transform:none}.menu-head{display:flex;justify-content:space-between;align-items:center}.menu-close{width:44px;height:44px;border:1px solid var(--line);border-radius:15px;background:white;cursor:pointer}.menu-links{display:grid;gap:5px;margin-top:40px}.menu-links a{padding:16px 4px;border-bottom:1px solid var(--line);font-family:var(--display);font-size:28px}.menu-cta{margin-top:28px;display:grid;gap:10px}
    .btn{min-height:48px;padding:0 21px;display:inline-flex;align-items:center;justify-content:center;gap:10px;border:0;border-radius:16px;font-size:12px;font-weight:800;cursor:pointer;transition:transform .2s ease,box-shadow .2s ease,background .2s}.btn:hover{transform:translateY(-2px)}.btn-acid{background:var(--acid);color:var(--pine-950);box-shadow:0 18px 52px -30px rgba(223,252,98,.72)}.btn-dark{background:var(--pine-900);color:white}.btn-cream{background:var(--cream);color:var(--pine-900)}.btn-outline{border:1px solid rgba(9,37,29,.16);background:transparent;color:var(--pine-900)}.btn-white-outline{border:1px solid rgba(255,255,255,.2);background:rgba(255,255,255,.04);color:white}
    .eyebrow{display:inline-flex;align-items:center;gap:9px;font-size:10px;font-weight:800;letter-spacing:.18em;text-transform:uppercase;color:var(--pine-700)}.eyebrow::before{content:'';width:22px;height:1px;background:currentColor}.eyebrow.light{color:var(--acid)}.title-xl{font-family:var(--display);font-size:clamp(52px,7.8vw,112px);line-height:.88;letter-spacing:-.06em;margin:0}.title-lg{font-family:var(--display);font-size:clamp(40px,5vw,74px);line-height:.98;letter-spacing:-.045em;margin:0}.title-md{font-family:var(--display);font-size:clamp(34px,4vw,58px);line-height:1;letter-spacing:-.04em;margin:0}.muted{color:rgba(22,35,30,.62)}
    .hero{min-height:780px;padding:140px 0 74px;background:var(--pine-950);color:white;position:relative;overflow:hidden}.hero::before{content:'';position:absolute;inset:0;background:linear-gradient(90deg,rgba(6,26,21,.94) 0%,rgba(6,26,21,.78) 42%,rgba(6,26,21,.15) 76%,rgba(6,26,21,.45) 100%),url('https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=2200&q=88') center/cover no-repeat;opacity:.96}.hero::after{content:'';position:absolute;inset:auto 0 0;height:180px;background:linear-gradient(transparent,var(--pine-950))}.hero-grid{position:relative;z-index:3;display:grid;grid-template-columns:minmax(0,1.1fr) minmax(340px,.72fr);gap:70px;align-items:end}.hero-copy{padding-top:66px}.hero-copy p{max-width:680px;margin:26px 0 0;font-size:18px;line-height:1.72;color:rgba(255,255,255,.72)}.hero-actions{display:flex;flex-wrap:wrap;gap:11px;margin-top:30px}.hero-note{margin-top:26px;display:flex;align-items:center;gap:12px;font-size:11px;color:rgba(255,255,255,.55)}.status-card{position:relative;padding:28px;border:1px solid rgba(255,255,255,.14);border-radius:30px;background:rgba(7,29,23,.72);backdrop-filter:blur(20px);box-shadow:var(--shadow-dark);overflow:hidden}.status-card::before{content:'';position:absolute;inset:0;background:linear-gradient(135deg,rgba(223,252,98,.08),transparent 48%,rgba(242,123,74,.08));pointer-events:none}.status-head{position:relative;display:flex;align-items:flex-start;justify-content:space-between;gap:18px}.status-live{display:flex;align-items:center;gap:8px;font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.12em;color:var(--acid)}.pulse-dot{width:8px;height:8px;border-radius:50%;background:var(--acid);animation:pulse 2.2s infinite}@keyframes pulse{0%{box-shadow:0 0 0 0 rgba(223,252,98,.5)}70%{box-shadow:0 0 0 10px rgba(223,252,98,0)}100%{box-shadow:0 0 0 0 rgba(223,252,98,0)}}.status-time{font-family:var(--display);font-size:42px;line-height:1;margin:20px 0 5px}.status-grid{position:relative;display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:22px}.status-box{padding:15px;border:1px solid rgba(255,255,255,.1);border-radius:18px;background:rgba(255,255,255,.05)}.status-box small{display:block;color:rgba(255,255,255,.44);font-size:9px;text-transform:uppercase;letter-spacing:.12em}.status-box strong{display:block;margin-top:7px;font-size:13px}.status-contact{position:relative;margin-top:18px;padding-top:18px;border-top:1px solid rgba(255,255,255,.1);display:flex;justify-content:space-between;gap:16px;align-items:center}.status-contact span{font-size:11px;color:rgba(255,255,255,.55)}.route-map{position:absolute;right:6%;top:12%;width:380px;height:240px;opacity:.46;pointer-events:none}.route-map path{fill:none;stroke:var(--acid);stroke-width:2;stroke-dasharray:8 12;filter:drop-shadow(0 0 7px rgba(223,252,98,.34))}.route-map circle{fill:var(--acid)}
    .ops-strip{position:relative;z-index:5;margin-top:-1px;background:var(--pine-950);color:white}.ops-inner{padding:18px 0 27px;display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.ops-item{display:flex;align-items:center;gap:12px;padding:13px 15px;border:1px solid rgba(255,255,255,.09);border-radius:18px;background:rgba(255,255,255,.035)}.ops-icon{width:38px;height:38px;display:grid;place-items:center;border-radius:14px;background:rgba(223,252,98,.1);color:var(--acid);flex:none}.ops-item small{display:block;font-size:8px;text-transform:uppercase;letter-spacing:.14em;color:rgba(255,255,255,.38)}.ops-item strong{display:block;margin-top:3px;font-size:11px}
    .support-section{padding:100px 0}.section-head{display:grid;grid-template-columns:1fr .8fr;gap:50px;align-items:end;margin-bottom:42px}.section-head p{margin:0;font-size:16px;line-height:1.75}.support-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.support-card{min-height:290px;padding:24px;display:flex;flex-direction:column;border:1px solid var(--line);border-radius:28px;background:var(--cream);box-shadow:0 20px 60px -46px rgba(6,26,21,.55);transition:.28s ease;cursor:pointer}.support-card:hover{transform:translateY(-5px);box-shadow:var(--shadow)}.support-card.active{background:var(--pine-900);color:white;border-color:var(--pine-900)}.support-number{width:44px;height:44px;display:grid;place-items:center;border-radius:16px;background:var(--acid);color:var(--pine-950);font-size:11px;font-weight:800}.support-card h3{font-family:var(--display);font-size:27px;line-height:1.02;margin:26px 0 11px}.support-card p{font-size:12px;line-height:1.65;color:rgba(22,35,30,.58);margin:0}.support-card.active p{color:rgba(255,255,255,.6)}.support-link{margin-top:auto;padding-top:22px;display:flex;justify-content:space-between;align-items:center;font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.1em}.support-card.active .support-link{color:var(--acid)}
    .contact-workspace{padding:96px 0;background:var(--cream)}.workspace-grid{display:grid;grid-template-columns:minmax(0,1.05fr) minmax(350px,.65fr);gap:24px;align-items:start}.form-card,.contact-sidebar{border:1px solid var(--line);border-radius:34px;background:white;box-shadow:var(--shadow)}.form-card{padding:34px}.form-head{display:flex;justify-content:space-between;gap:24px;align-items:flex-start;padding-bottom:26px;border-bottom:1px solid var(--line)}.topic-pill{padding:9px 12px;border-radius:999px;background:var(--acid);font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:.1em}.form-head h2{font-family:var(--display);font-size:42px;line-height:1;margin:12px 0 0}.response-time{max-width:170px;text-align:right;font-size:10px;line-height:1.5;color:rgba(22,35,30,.52)}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:17px;margin-top:26px}.field{display:grid;gap:8px}.field.full{grid-column:1/-1}.field label{font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.12em;color:rgba(22,35,30,.58)}.input,.select,.textarea{width:100%;border:1px solid rgba(9,37,29,.15);border-radius:16px;background:var(--cream);color:var(--ink);outline:none;transition:.2s}.input,.select{height:52px;padding:0 15px}.textarea{min-height:142px;padding:15px;resize:vertical}.input:focus,.select:focus,.textarea:focus{border-color:var(--pine-700);box-shadow:0 0 0 4px rgba(27,82,66,.08)}.field-hint{font-size:10px;color:rgba(22,35,30,.44)}.file-drop{padding:20px;border:1px dashed rgba(9,37,29,.22);border-radius:18px;background:var(--oat);text-align:center;cursor:pointer}.file-drop strong{display:block;font-size:12px}.file-drop span{display:block;margin-top:4px;font-size:10px;color:rgba(22,35,30,.46)}.file-list{display:flex;flex-wrap:wrap;gap:7px;margin-top:9px}.file-chip{display:inline-flex;align-items:center;gap:7px;padding:8px 10px;border-radius:999px;background:rgba(9,37,29,.08);font-size:9px;font-weight:700}.file-chip button{border:0;background:none;cursor:pointer}.form-foot{display:flex;justify-content:space-between;gap:18px;align-items:center;margin-top:24px}.consent{display:flex;gap:10px;align-items:flex-start;max-width:430px;font-size:10px;line-height:1.5;color:rgba(22,35,30,.54)}.consent input{margin-top:2px;accent-color:var(--pine-800)}
    .contact-sidebar{padding:25px;position:sticky;top:92px}.channel-list{display:grid;gap:10px}.channel{padding:17px;border:1px solid var(--line);border-radius:20px;background:var(--cream);display:grid;grid-template-columns:44px 1fr auto;gap:12px;align-items:center}.channel-icon{width:44px;height:44px;display:grid;place-items:center;border-radius:15px;background:var(--pine-900);color:var(--acid)}.channel small{display:block;font-size:8px;text-transform:uppercase;letter-spacing:.13em;color:rgba(22,35,30,.42)}.channel strong{display:block;margin-top:4px;font-size:11px}.channel button,.channel a{border:0;background:none;color:var(--pine-700);font-size:9px;font-weight:800;cursor:pointer}.sidebar-divider{height:1px;background:var(--line);margin:22px 0}.hours h3,.quick-status h3{font-family:var(--display);font-size:24px;margin:0 0 14px}.hours-row{display:flex;justify-content:space-between;gap:15px;padding:10px 0;border-bottom:1px solid var(--line);font-size:10px}.hours-row span:first-child{color:rgba(22,35,30,.54)}.hours-row.today{font-weight:800;color:var(--pine-900)}.hours-row.today span:first-child{color:var(--pine-900)}.quick-status{margin-top:24px;padding:20px;border-radius:24px;background:var(--pine-900);color:white}.quick-status p{font-size:10px;line-height:1.6;color:rgba(255,255,255,.6)}.status-line{display:flex;align-items:center;gap:8px;margin-top:12px;font-size:10px}.status-line i{width:7px;height:7px;border-radius:50%;background:var(--acid)}
    .location-section{padding:100px 0}.location-grid{display:grid;grid-template-columns:.65fr 1.15fr;gap:24px}.location-copy{padding:34px;border-radius:32px;background:var(--pine-900);color:white}.location-copy p{font-size:13px;line-height:1.72;color:rgba(255,255,255,.62)}.address-card{margin-top:28px;padding:18px;border:1px solid rgba(255,255,255,.12);border-radius:20px;background:rgba(255,255,255,.05)}.address-card small{display:block;font-size:8px;text-transform:uppercase;letter-spacing:.13em;color:rgba(255,255,255,.4)}.address-card strong{display:block;margin-top:7px;font-size:13px;line-height:1.5}.address-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}.map-card{min-height:530px;position:relative;overflow:hidden;border-radius:34px;background:#abc8af}.map-card::before{content:'';position:absolute;inset:0;background:url('https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1800&q=86') center/cover;filter:saturate(.72) contrast(.9)}.map-overlay{position:absolute;inset:0;background:linear-gradient(135deg,rgba(6,26,21,.05),rgba(6,26,21,.52))}.map-route{position:absolute;inset:10% 9%;width:82%;height:80%}.map-route path{fill:none;stroke:var(--acid);stroke-width:3;stroke-linecap:round;stroke-dasharray:10 14;filter:drop-shadow(0 0 7px rgba(223,252,98,.5))}.map-route circle{fill:var(--acid)}.map-label{position:absolute;padding:10px 13px;border-radius:14px;background:rgba(6,26,21,.88);color:white;box-shadow:var(--shadow-dark);font-size:9px;font-weight:800}.map-label.main{left:56%;top:45%}.map-label.parking{left:17%;bottom:18%}.map-label.shuttle{right:8%;top:17%}.transport-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:18px}.transport{padding:16px;border:1px solid rgba(255,255,255,.11);border-radius:18px;background:rgba(255,255,255,.05)}.transport strong{display:block;font-size:11px}.transport span{display:block;margin-top:5px;font-size:9px;line-height:1.5;color:rgba(255,255,255,.48)}
    .faq-section{padding:100px 0;background:var(--pine-950);color:white}.faq-grid{display:grid;grid-template-columns:.65fr 1.05fr;gap:70px}.faq-intro{position:sticky;top:110px;height:max-content}.faq-intro p{font-size:13px;line-height:1.72;color:rgba(255,255,255,.58)}.faq-list{display:grid;gap:9px}.faq-item{border:1px solid rgba(255,255,255,.1);border-radius:20px;background:rgba(255,255,255,.04);overflow:hidden}.faq-q{width:100%;padding:19px 20px;display:flex;align-items:center;justify-content:space-between;gap:18px;border:0;background:none;color:white;text-align:left;cursor:pointer;font-size:12px;font-weight:700}.faq-q span:last-child{font-size:20px;color:var(--acid);transition:.25s}.faq-item.open .faq-q span:last-child{transform:rotate(45deg)}.faq-a{max-height:0;overflow:hidden;transition:max-height .35s ease}.faq-a p{margin:0;padding:0 20px 20px;font-size:11px;line-height:1.7;color:rgba(255,255,255,.58)}.faq-item.open .faq-a{max-height:220px}
    .emergency{padding:70px 0;background:var(--ember)}.emergency-card{display:grid;grid-template-columns:1fr auto;gap:40px;align-items:center}.emergency-card h2{font-family:var(--display);font-size:clamp(36px,5vw,66px);line-height:.96;margin:0}.emergency-card p{max-width:700px;margin:17px 0 0;font-size:13px;line-height:1.65}.emergency-actions{display:flex;gap:9px;flex-wrap:wrap;justify-content:flex-end}
    footer{padding:72px 0 28px;background:var(--pine-950);color:white}.footer-grid{display:grid;grid-template-columns:.8fr 1.2fr;gap:70px}.footer-brand p{max-width:340px;font-size:11px;line-height:1.65;color:rgba(255,255,255,.46)}.footer-cols{display:grid;grid-template-columns:repeat(4,1fr);gap:24px}.footer-col h4{margin:0 0 14px;font-size:9px;text-transform:uppercase;letter-spacing:.14em;color:rgba(255,255,255,.35)}.footer-col a{display:block;margin:10px 0;font-size:11px;color:rgba(255,255,255,.66)}.footer-col a:hover{color:white}.footer-bottom{display:flex;justify-content:space-between;gap:20px;margin-top:52px;padding-top:22px;border-top:1px solid rgba(255,255,255,.09);font-size:9px;color:rgba(255,255,255,.36)}
    .modal{position:fixed;inset:0;z-index:200;display:grid;place-items:center;padding:20px;visibility:hidden;pointer-events:none}.modal.open{visibility:visible;pointer-events:auto}.modal-backdrop{position:absolute;inset:0;background:rgba(3,15,12,.76);opacity:0;transition:.25s}.modal.open .modal-backdrop{opacity:1}.modal-card{position:relative;width:min(560px,100%);max-height:min(760px,calc(100vh - 40px));overflow:auto;padding:30px;border-radius:30px;background:var(--cream);box-shadow:var(--shadow-dark);transform:translateY(24px) scale(.98);opacity:0;transition:.3s}.modal.open .modal-card{transform:none;opacity:1}.modal-close{position:absolute;right:18px;top:18px;width:42px;height:42px;border:1px solid var(--line);border-radius:14px;background:white;cursor:pointer}.success-icon{width:68px;height:68px;display:grid;place-items:center;border-radius:24px;background:var(--acid);color:var(--pine-950)}.chat-messages{display:grid;gap:10px;margin:22px 0}.chat-message{max-width:82%;padding:13px 15px;border-radius:18px;font-size:11px;line-height:1.6}.chat-message.agent{background:white;border:1px solid var(--line)}.chat-message.user{margin-left:auto;background:var(--pine-900);color:white}.chat-input{display:flex;gap:8px}.chat-input input{flex:1;height:48px;padding:0 14px;border:1px solid var(--line);border-radius:15px;outline:none}
    .toast{position:fixed;left:50%;bottom:22px;z-index:260;max-width:calc(100% - 28px);padding:13px 17px;border-radius:999px;background:var(--pine-900);color:white;box-shadow:var(--shadow-dark);font-size:10px;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;transform:translate(-50%,130%);transition:.35s}.toast.show{transform:translate(-50%,0)}
    [data-reveal]{opacity:0;transform:translateY(28px)}
    @media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;animation:none!important;transition:none!important}[data-reveal]{opacity:1!important;transform:none!important}}
    @media(max-width:1050px){.nav-links{display:none}.mobile-trigger{display:grid}.hero-grid{grid-template-columns:1fr .72fr;gap:30px}.support-grid{grid-template-columns:1fr 1fr}.workspace-grid,.location-grid{grid-template-columns:1fr}.contact-sidebar{position:relative;top:auto}.map-card{min-height:470px}.faq-grid{grid-template-columns:1fr;gap:34px}.faq-intro{position:relative;top:auto}.footer-grid{grid-template-columns:1fr}.footer-cols{grid-template-columns:repeat(4,1fr)}}
    @media(max-width:760px){.wrap{width:min(100% - 28px,1240px)}.site-header{padding-inline:12px}.nav{height:62px;border-radius:20px;padding:0 9px 0 12px;gap:9px}.brand-mark{width:38px;height:38px;border-radius:13px}.brand-name{font-size:17px}.brand-sub{display:none}.ticket-btn{height:39px;padding:0 12px}.nav-icon{width:39px;height:39px}.hero{min-height:auto;padding:116px 0 46px}.hero-grid{grid-template-columns:1fr;gap:28px}.hero-copy{padding-top:22px}.hero-copy p{font-size:15px;margin-top:20px}.hero-actions{display:grid;grid-template-columns:1fr}.hero-actions .btn{width:100%}.status-card{padding:22px;border-radius:24px}.route-map{display:none}.ops-inner{grid-template-columns:1fr 1fr;padding-bottom:18px}.support-section,.contact-workspace,.location-section,.faq-section{padding:72px 0}.section-head{grid-template-columns:1fr;gap:18px;margin-bottom:28px}.support-grid{grid-template-columns:1fr}.support-card{min-height:230px}.workspace-grid{gap:16px}.form-card,.contact-sidebar{border-radius:25px}.form-card{padding:21px}.form-head{display:grid;gap:14px}.response-time{text-align:left;max-width:none}.form-head h2{font-size:34px}.form-grid{grid-template-columns:1fr}.field.full{grid-column:auto}.form-foot{display:grid}.form-foot .btn{width:100%}.channel{grid-template-columns:42px 1fr}.channel>a,.channel>button{grid-column:2;text-align:left;padding:0}.location-copy{padding:25px;border-radius:25px}.map-card{min-height:420px;border-radius:25px}.map-label{font-size:8px}.transport-grid{grid-template-columns:1fr}.emergency-card{grid-template-columns:1fr}.emergency-actions{justify-content:flex-start}.emergency-actions .btn{flex:1}.footer-cols{grid-template-columns:1fr 1fr}.footer-bottom{display:grid}.modal{padding:10px;align-items:end}.modal-card{width:100%;max-height:88vh;border-radius:26px 26px 0 0;padding:26px 20px 24px}.status-grid{grid-template-columns:1fr 1fr}}
    @media(max-width:420px){.nav-actions{gap:6px}.ticket-btn{font-size:10px;padding:0 10px}.ops-inner{grid-template-columns:1fr}.status-grid{grid-template-columns:1fr}.footer-cols{grid-template-columns:1fr}.support-card{min-height:210px}.map-card{min-height:360px}.map-label.shuttle{right:3%}.map-label.main{left:43%}.emergency-actions{display:grid}.title-xl{font-size:50px}.form-card{padding:18px}.contact-sidebar{padding:18px}}
  </style>
</head>
<body>
  <div id="scrollProgress" aria-hidden="true"></div>
  <?php $nvNoSpacer = true; include __DIR__ . '/includes/header.php'; ?>

  <main>
    <section class="hero topo-dark grain">
      <svg class="route-map" viewBox="0 0 420 260" aria-hidden="true"><path id="heroRoute" d="M16 202C73 154 84 83 151 105c63 21 71-73 140-45 62 25 31 104 108 128"/><circle id="heroMarker" cx="16" cy="202" r="6"/></svg>
      <div class="wrap hero-grid">
        <div class="hero-copy" data-reveal><span class="eyebrow light">Contact și suport</span><h1 class="title-xl" style="margin-top:18px">Spune-ne<br>unde te-ai<br><em style="color:var(--acid);font-weight:500">oprit.</em></h1><p>Îți răspundem cu informații concrete — despre bilete, acces, vreme, grupuri sau o problemă apărută în timpul vizitei. Fără formulare trimise în gol.</p><div class="hero-actions"><a class="btn btn-acid" href="#mesaj">Trimite un mesaj</a><button class="btn btn-white-outline" type="button" data-open-chat>Deschide chatul</button></div><div class="hero-note"><span class="pulse-dot"></span><span>Timp mediu de răspuns astăzi: 18 minute în chat · sub 4 ore prin email</span></div></div>
        <aside class="status-card" data-reveal><div class="status-head"><div><div class="status-live"><span class="pulse-dot"></span> Centrul de suport este online</div><div class="status-time">18:33</div><div style="font-size:11px;color:rgba(255,255,255,.5)">Miercuri, 29 iulie 2026</div></div><span style="font-size:9px;color:rgba(255,255,255,.4);text-transform:uppercase;letter-spacing:.12em">Ora locală</span></div><div class="status-grid"><div class="status-box"><small>Telefon</small><strong>până la 20:00</strong></div><div class="status-box"><small>Chat</small><strong>răspuns rapid</strong></div><div class="status-box"><small>Casa de bilete</small><strong>deschisă</strong></div><div class="status-box"><small>Urgențe în parc</small><strong>linie activă</strong></div></div><div class="status-contact"><span>Ai o vizită în următoarele 24h?</span><a class="btn btn-acid" style="min-height:40px;padding-inline:14px" href="tel:+40210000000">Sună acum</a></div></aside>
      </div>
    </section>

    <section class="ops-strip"><div class="wrap ops-inner"><div class="ops-item"><span class="ops-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none"><path d="M4 19h16M6 16l3-8 3 5 2-3 4 6" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg></span><span><small>Parc</small><strong>Deschis · 09:00–20:00</strong></span></div><div class="ops-item"><span class="ops-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none"><path d="M4 17h16M6 17V9h12v8M9 9V6h6v3" stroke="currentColor" stroke-width="1.6"/></svg></span><span><small>Shuttle</small><strong>La fiecare 30 minute</strong></span></div><div class="ops-item"><span class="ops-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none"><path d="M6 14a6 6 0 1 1 11.2 3H7a4 4 0 1 1-.8-7.9" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/></svg></span><span><small>Vreme</small><strong>24°C · fără alerte</strong></span></div><div class="ops-item"><span class="ops-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none"><path d="M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18Z" stroke="currentColor" stroke-width="1.6"/><path d="M12 7v5l3 2" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/></svg></span><span><small>Răspuns email</small><strong>În aceeași zi</strong></span></div></div></section>

    <section class="support-section paper-grid" id="alege"><div class="wrap"><div class="section-head" data-reveal><div><span class="eyebrow">Alege traseul corect</span><h2 class="title-lg" style="margin-top:14px">Nu orice întrebare<br>merge în același inbox.</h2></div><p class="muted">Alege tema, iar formularul și timpul de răspuns se adaptează. Pentru urgențe în parc sau acces în următoarele ore, folosește telefonul.</p></div><div class="support-grid" id="supportTopics">
      <button class="support-card active" type="button" data-topic="bilete"><span class="support-number">01</span><h3>Bilete & rezervări</h3><p>Plată, confirmare, schimbare de dată, beneficiar, factură sau acces la bilete.</p><span class="support-link">Răspuns în max. 4h <span>↗</span></span></button>
      <button class="support-card" type="button" data-topic="vizita"><span class="support-number">02</span><h3>Vizita ta</h3><p>Acces, parcare, shuttle, vreme, reguli, echipament sau accesibilitate.</p><span class="support-link">Răspuns în max. 2h <span>↗</span></span></button>
      <button class="support-card" type="button" data-topic="grupuri"><span class="support-number">03</span><h3>Grupuri & școli</h3><p>Oferte, itinerare, transport, masă, facturare și condiții pentru organizatori.</p><span class="support-link">Răspuns în 1 zi <span>↗</span></span></button>
      <button class="support-card" type="button" data-topic="parteneriate"><span class="support-number">04</span><h3>Presă & parteneriate</h3><p>Colaborări, filmări, proiecte educaționale, conservare și solicitări media.</p><span class="support-link">Răspuns în 2 zile <span>↗</span></span></button>
    </div></div></section>

    <section class="contact-workspace" id="mesaj"><div class="wrap workspace-grid"><article class="form-card" data-reveal><div class="form-head"><div><span class="topic-pill" id="topicPill">Bilete & rezervări</span><h2 id="formTitle">Cu ce te putem ajuta?</h2></div><div class="response-time" id="responseTime">Echipa de ticketing răspunde, de regulă, în maximum 4 ore în timpul programului.</div></div>
      <form id="contactForm" novalidate><div class="form-grid"><div class="field"><label for="name">Nume complet</label><input class="input" id="name" name="name" autocomplete="name" required placeholder="Andrei Popescu"><span class="field-hint">Așa cum apare pe rezervare, dacă există.</span></div><div class="field"><label for="email">Email</label><input class="input" id="email" name="email" type="email" autocomplete="email" required placeholder="andrei@email.ro"></div><div class="field"><label for="phone">Telefon</label><input class="input" id="phone" name="phone" type="tel" autocomplete="tel" placeholder="07xx xxx xxx"></div><div class="field"><label for="order">Număr comandă <span style="font-weight:500;text-transform:none;letter-spacing:0">(opțional)</span></label><input class="input" id="order" name="order" placeholder="NV-2026-1842"></div><div class="field full" id="dynamicField"></div><div class="field full"><label for="subject">Subiect</label><input class="input" id="subject" name="subject" required placeholder="Descrie pe scurt situația"></div><div class="field full"><label for="message">Mesaj</label><textarea class="textarea" id="message" name="message" required placeholder="Spune-ne ce s-a întâmplat, când și ce rezultat ai nevoie să obții."></textarea><span class="field-hint">Cu cât contextul este mai concret, cu atât răspunsul va fi mai rapid.</span></div><div class="field full"><label>Documente sau capturi</label><label class="file-drop" for="attachments"><strong>Adaugă fișiere</strong><span>PDF, JPG sau PNG · maximum 10 MB</span></label><input id="attachments" type="file" accept=".pdf,.jpg,.jpeg,.png" multiple hidden><div class="file-list" id="fileList"></div></div></div><div class="form-foot"><label class="consent"><input id="consent" type="checkbox" required><span>Sunt de acord ca datele mele să fie folosite pentru soluționarea solicitării, conform politicii de confidențialitate.</span></label><button class="btn btn-dark" type="submit">Trimite solicitarea <span>↗</span></button></div></form></article>
      <aside class="contact-sidebar" data-reveal><div class="channel-list"><div class="channel"><span class="channel-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none"><path d="M7.5 4h-2A1.5 1.5 0 0 0 4 5.5v2C4 14.4 9.6 20 16.5 20h2a1.5 1.5 0 0 0 1.5-1.5v-2l-4-2-1.2 2c-2.9-1.2-5.4-3.7-6.6-6.6l2-1.2-2.7-4.7Z" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg></span><span><small>Telefon suport</small><strong>021 000 00 00</strong></span><a href="tel:+40210000000">Sună</a></div><div class="channel"><span class="channel-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none"><path d="M4 6h16v12H4V6Z" stroke="currentColor" stroke-width="1.6"/><path d="m5 7 7 6 7-6" stroke="currentColor" stroke-width="1.6"/></svg></span><span><small>Email</small><strong>salut@nordvale.demo</strong></span><button type="button" data-copy="salut@nordvale.demo">Copiază</button></div><div class="channel"><span class="channel-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none"><path d="M5 5h14v11H9l-4 3V5Z" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"/></svg></span><span><small>Chat live</small><strong>Online acum</strong></span><button type="button" data-open-chat>Deschide</button></div></div><div class="sidebar-divider"></div><div class="hours"><h3>Program suport</h3><div class="hours-row"><span>Luni–Vineri</span><span>08:30–20:00</span></div><div class="hours-row today"><span>Miercuri · astăzi</span><span>08:30–20:00</span></div><div class="hours-row"><span>Sâmbătă–Duminică</span><span>08:00–20:30</span></div><div class="hours-row"><span>Urgențe în parc</span><span>până la închidere</span></div></div><div class="quick-status"><h3>Status servicii</h3><p>Nu există incidente active care să afecteze cumpărarea biletelor sau accesul în parc.</p><div class="status-line"><i></i><span>Ticketing operațional</span></div><div class="status-line"><i></i><span>Plăți operaționale</span></div><div class="status-line"><i></i><span>Scanare QR operațională</span></div></div></aside>
    </div></section>

    <section class="location-section paper-grid"><div class="wrap location-grid"><div class="location-copy topo-dark" data-reveal><span class="eyebrow light">Ajungi la noi</span><h2 class="title-md" style="margin-top:15px">Ultimii kilometri<br>fac parte din experiență.</h2><p>Nordvale este un concept demonstrativ amplasat într-o zonă forestieră fictivă. Datele de mai jos sunt dummy, construite pentru template.</p><div class="address-card"><small>Adresă demonstrativă</small><strong>Drumul Forestier Valea Nordului 18<br>Comuna Stejaru, județul Brașov</strong><div class="address-actions"><button class="btn btn-acid" type="button" data-copy="Drumul Forestier Valea Nordului 18, Stejaru, Brașov">Copiază adresa</button><a class="btn btn-white-outline" href="#">Deschide harta</a></div></div><div class="transport-grid"><div class="transport"><strong>Cu mașina</strong><span>40 min din Brașov · parcare la intrarea sudică.</span></div><div class="transport"><strong>Cu shuttle</strong><span>Plecări din Gara Brașov la 08:30, 10:00 și 12:00.</span></div><div class="transport"><strong>Cu bicicleta</strong><span>Rastel păzit și punct de reparații la Visitor Base.</span></div></div></div><div class="map-card grain" data-reveal><div class="map-overlay"></div><svg class="map-route" viewBox="0 0 720 430" aria-hidden="true"><path id="mapPath" d="M43 344C106 310 128 239 196 261c75 25 104-93 195-66 70 21 62 111 132 93 51-13 73-76 155-56"/><circle id="mapMarker" cx="43" cy="344" r="8"/></svg><span class="map-label parking">Parcare sud</span><span class="map-label main">Visitor Base</span><span class="map-label shuttle">Stație shuttle</span></div></div></section>

    <section class="faq-section topo-dark"><div class="wrap faq-grid"><div class="faq-intro" data-reveal><span class="eyebrow light">Răspunsuri rapide</span><h2 class="title-lg" style="margin-top:15px">Poate nici nu trebuie<br>să ne scrii.</h2><p>Am adunat întrebările care apar cel mai des înainte de vizită. Pentru situații specifice unei comenzi, folosește formularul și adaugă numărul rezervării.</p><a class="btn btn-acid" href="/cont/suport" style="margin-top:18px">Ajutor din cont</a></div><div class="faq-list" id="faqList" data-reveal>
      <article class="faq-item open"><button class="faq-q" type="button"><span>Pot schimba data unei rezervări?</span><span>+</span></button><div class="faq-a"><p>Da, în funcție de tipul biletului și disponibilitate. Din cont poți vedea imediat dacă modificarea este eligibilă. Pentru o vizită în următoarele 24 de ore, contactează suportul telefonic.</p></div></article>
      <article class="faq-item"><button class="faq-q" type="button"><span>Ce se întâmplă dacă vremea închide o experiență?</span><span>+</span></button><div class="faq-a"><p>Primești automat opțiunile aplicabile rezervării: reprogramare, credit Nordvale sau rambursare, în funcție de durata suspendării și produsele cumpărate.</p></div></article>
      <article class="faq-item"><button class="faq-q" type="button"><span>Pot cumpăra bilete direct la intrare?</span><span>+</span></button><div class="faq-a"><p>Da, doar în limita capacității rămase. Pentru traseele cu echipament și interval orar recomandăm rezervarea online.</p></div></article>
      <article class="faq-item"><button class="faq-q" type="button"><span>Există condiții speciale pentru accesibilitate?</span><span>+</span></button><div class="faq-a"><p>Visitor Base, traseul Meadow Loop și zonele principale de servicii sunt accesibile. Pentru asistență personalizată, alege tema „Vizita ta” și menționează nevoile concrete.</p></div></article>
      <article class="faq-item"><button class="faq-q" type="button"><span>Cum primesc factura?</span><span>+</span></button><div class="faq-a"><p>Factura se generează în cont și se trimite prin email. Datele pot fi completate sau corectate înainte de emiterea documentului fiscal.</p></div></article>
      <article class="faq-item"><button class="faq-q" type="button"><span>Unde raportez un obiect pierdut?</span><span>+</span></button><div class="faq-a"><p>Selectează tema „Vizita ta”, descrie obiectul, zona și ora aproximativă. Echipa Lost & Found răspunde în aceeași zi.</p></div></article>
    </div></div></section>

    <section class="emergency"><div class="wrap emergency-card"><div><span class="eyebrow" style="color:var(--pine-950)">Situație urgentă</span><h2>Ai nevoie de ajutor<br>în timp ce ești în parc?</h2><p>Pentru accident, persoană rătăcită, reacție medicală sau pericol imediat, nu folosi formularul. Sună echipa operațională sau 112.</p></div><div class="emergency-actions"><a class="btn btn-dark" href="tel:+40210000011">Echipă parc · 021 000 00 11</a><a class="btn btn-cream" href="tel:112">Sună 112</a></div></div></section>
  </main>

  <?php include __DIR__ . '/includes/footer.php'; ?>

  <div class="modal" id="successModal" aria-hidden="true"><div class="modal-backdrop" data-close-modal></div><div class="modal-card"><button class="modal-close" type="button" data-close-modal>×</button><div class="success-icon"><svg width="32" height="32" viewBox="0 0 24 24" fill="none"><path d="m5 12 4 4 10-10" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></div><span class="eyebrow" style="margin-top:24px">Solicitare înregistrată</span><h2 class="display" style="font-size:40px;line-height:1;margin:14px 0">Am primit mesajul.</h2><p class="muted" style="font-size:12px;line-height:1.7">Numărul demonstrativ al solicitării este <strong id="caseNumber">NV-SUP-0000</strong>. Confirmarea a fost trimisă la adresa introdusă.</p><div style="padding:16px;border-radius:18px;background:white;border:1px solid var(--line);margin-top:20px"><small style="font-size:8px;text-transform:uppercase;letter-spacing:.13em;color:rgba(22,35,30,.42)">Timp estimat de răspuns</small><strong id="modalResponse" style="display:block;margin-top:7px;font-size:13px">Maximum 4 ore</strong></div><button class="btn btn-dark" style="width:100%;margin-top:20px" type="button" data-close-modal>Închide</button></div></div>
  <div class="modal" id="chatModal" aria-hidden="true"><div class="modal-backdrop" data-close-chat></div><div class="modal-card"><button class="modal-close" type="button" data-close-chat>×</button><span class="eyebrow">Chat Nordvale</span><h2 class="display" style="font-size:38px;line-height:1;margin:14px 0">Discuție rapidă.</h2><div class="chat-messages" id="chatMessages"><div class="chat-message agent">Salut! Sunt Mara din echipa Nordvale. Spune-mi pe scurt cu ce te pot ajuta.</div></div><form class="chat-input" id="chatForm"><input id="chatText" placeholder="Scrie mesajul…" required><button class="btn btn-dark" type="submit">Trimite</button></form></div></div>
  <div class="toast" id="toast">Copiat.</div>

  <script>
    (()=>{
      'use strict';
      const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
      const body=document.body, nav=$('#siteNav'), progress=$('#scrollProgress');
      const menu=$('#mobileMenu');
      function setMenu(open){menu?.classList.toggle('open',open);menu?.setAttribute('aria-hidden',String(!open));body.classList.toggle('menu-open',open)}
      $('#menuOpen')?.addEventListener('click',()=>setMenu(true));$('#menuClose')?.addEventListener('click',()=>setMenu(false));$('#menuBackdrop')?.addEventListener('click',()=>setMenu(false));
      function onScroll(){const y=scrollY;nav?.classList.toggle('scrolled',y>24);const max=document.documentElement.scrollHeight-innerHeight;progress.style.transform=`scaleX(${max>0?Math.min(1,y/max):0})`}
      addEventListener('scroll',onScroll,{passive:true});onScroll();
      addEventListener('keydown',e=>{if(e.key==='Escape'){setMenu(false);closeModal();closeChat()}});

      const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
      if(!reduce&&'IntersectionObserver'in window){const io=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.animate([{opacity:0,transform:'translateY(28px)'},{opacity:1,transform:'none'}],{duration:680,easing:'cubic-bezier(.2,.75,.2,1)',fill:'forwards'});io.unobserve(entry.target)}}),{threshold:.12});$$('[data-reveal]').forEach(el=>io.observe(el))}else{$$('[data-reveal]').forEach(el=>{el.style.opacity=1;el.style.transform='none'})}

      function animatePath(path,marker,duration=2200){if(!path||!marker||reduce)return;const length=path.getTotalLength();path.style.strokeDasharray=String(length);path.style.strokeDashoffset=String(length);path.animate([{strokeDashoffset:length},{strokeDashoffset:0}],{duration,easing:'cubic-bezier(.2,.75,.2,1)',fill:'forwards',delay:250});const start=performance.now()+250;function move(t){const p=Math.max(0,Math.min(1,(t-start)/duration)),pt=path.getPointAtLength(length*p);marker.setAttribute('cx',pt.x);marker.setAttribute('cy',pt.y);if(p<1)requestAnimationFrame(move)}requestAnimationFrame(move)}
      animatePath($('#heroRoute'),$('#heroMarker'));animatePath($('#mapPath'),$('#mapMarker'),2600);

      const topics={
        bilete:{label:'Bilete & rezervări',title:'Cu ce te putem ajuta?',response:'Echipa de ticketing răspunde, de regulă, în maximum 4 ore în timpul programului.',modal:'Maximum 4 ore',dynamic:'<label for="bookingDate">Data rezervării <span style="font-weight:500;text-transform:none;letter-spacing:0">(opțional)</span></label><input class="input" id="bookingDate" name="bookingDate" type="date">'},
        vizita:{label:'Vizita ta',title:'Pregătim vizita împreună.',response:'Pentru întrebări despre acces, vreme și facilități răspundem, de regulă, în maximum 2 ore.',modal:'Maximum 2 ore',dynamic:'<label for="plannedVisitDate">Data planificată a vizitei</label><input class="input" id="plannedVisitDate" name="plannedVisitDate" type="date">'},
        grupuri:{label:'Grupuri & școli',title:'Spune-ne cum arată grupul.',response:'Un coordonator de grup revine cu detalii și ofertă în maximum o zi lucrătoare.',modal:'Maximum 1 zi lucrătoare',dynamic:'<label for="groupSize">Număr estimat de participanți</label><input class="input" id="groupSize" name="groupSize" type="number" min="10" placeholder="Ex. 32">'},
        parteneriate:{label:'Presă & parteneriate',title:'Construim contextul potrivit.',response:'Solicitările editoriale și de parteneriat primesc răspuns în maximum două zile lucrătoare.',modal:'Maximum 2 zile lucrătoare',dynamic:'<label for="organization">Organizație / publicație</label><input class="input" id="organization" name="organization" placeholder="Numele organizației">'}
      };
      let activeTopic='bilete';
      function setTopic(topic){if(!topics[topic])return;activeTopic=topic;$$('[data-topic]').forEach(b=>b.classList.toggle('active',b.dataset.topic===topic));const data=topics[topic];$('#topicPill').textContent=data.label;$('#formTitle').textContent=data.title;$('#responseTime').textContent=data.response;$('#dynamicField').innerHTML=data.dynamic;$('#mesaj').scrollIntoView({behavior:reduce?'auto':'smooth',block:'start'})}
      $$('[data-topic]').forEach(btn=>btn.addEventListener('click',()=>setTopic(btn.dataset.topic)));

      const fileInput=$('#attachments'),fileList=$('#fileList');let files=[];
      fileInput?.addEventListener('change',()=>{files=[...fileInput.files].slice(0,5);renderFiles()});
      function renderFiles(){fileList.innerHTML='';files.forEach((file,index)=>{const chip=document.createElement('span');chip.className='file-chip';chip.innerHTML=`<span>${file.name}</span><button type="button" aria-label="Elimină ${file.name}">×</button>`;chip.querySelector('button').addEventListener('click',()=>{files.splice(index,1);renderFiles()});fileList.appendChild(chip)})}

      const toast=$('#toast');function showToast(text){toast.textContent=text;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),2800)}
      $$('[data-copy]').forEach(el=>el.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(el.dataset.copy);showToast('Copiat în clipboard.')}catch{showToast(el.dataset.copy)}}));

      const success=$('#successModal');function openModal(){const n=`NV-SUP-${Math.floor(1000+Math.random()*9000)}`;$('#caseNumber').textContent=n;$('#modalResponse').textContent=topics[activeTopic].modal;success.classList.add('open');success.setAttribute('aria-hidden','false');body.classList.add('modal-open')}function closeModal(){success?.classList.remove('open');success?.setAttribute('aria-hidden','true');if(!$('#chatModal')?.classList.contains('open'))body.classList.remove('modal-open')}$$('[data-close-modal]').forEach(el=>el.addEventListener('click',closeModal));
      $('#contactForm')?.addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;if(!form.checkValidity()){form.reportValidity();return}openModal();form.reset();files=[];renderFiles()});

      const chat=$('#chatModal');function openChat(){chat.classList.add('open');chat.setAttribute('aria-hidden','false');body.classList.add('modal-open');setTimeout(()=>$('#chatText')?.focus(),300)}function closeChat(){chat?.classList.remove('open');chat?.setAttribute('aria-hidden','true');if(!success?.classList.contains('open'))body.classList.remove('modal-open')}$$('[data-open-chat]').forEach(el=>el.addEventListener('click',openChat));$$('[data-close-chat]').forEach(el=>el.addEventListener('click',closeChat));
      $('#chatForm')?.addEventListener('submit',e=>{e.preventDefault();const input=$('#chatText'),text=input.value.trim();if(!text)return;const mine=document.createElement('div');mine.className='chat-message user';mine.textContent=text;$('#chatMessages').appendChild(mine);input.value='';setTimeout(()=>{const reply=document.createElement('div');reply.className='chat-message agent';reply.textContent='Am înțeles. Pentru această situație am nevoie de numărul comenzii sau data vizitei. Îl poți trimite aici.';$('#chatMessages').appendChild(reply);reply.scrollIntoView({behavior:'smooth',block:'nearest'})},700)});

      $$('.faq-q').forEach(btn=>btn.addEventListener('click',()=>{const item=btn.closest('.faq-item'),open=item.classList.contains('open');$$('.faq-item').forEach(i=>i.classList.remove('open'));if(!open)item.classList.add('open')}));
    })();
  </script>
</body>
</html>
