<!DOCTYPE html>
<html lang="ro" class="scroll-smooth">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
  <meta name="robots" content="noindex, nofollow">
  <meta name="theme-color" content="#061a15">
  <title>Întrebări frecvente — Nordvale</title>
  <meta name="description" content="Centrul public de întrebări frecvente pentru tenantul leisure Nordvale, powered by Tixello.">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Fraunces:opsz,wght@9..144,500;9..144,600;9..144,700&display=swap" rel="stylesheet">
  <style>
    :root{--pine-950:#061a15;--pine-900:#09251d;--pine-850:#0d3027;--pine-800:#123b30;--pine-700:#1b5242;--acid:#dffc62;--ember:#f27b4a;--cream:#fffdf6;--oat:#f0ecdf;--moss:#b7c9a3;--ink:#16231e;--sky:#b8dce0;--line:rgba(9,37,29,.12);--shadow:0 30px 90px -48px rgba(6,26,21,.5);--shadow-dark:0 32px 90px -44px rgba(0,0,0,.64);--display:'Fraunces',serif;--sans:'DM Sans',sans-serif}
    *{box-sizing:border-box}html{background:var(--oat);scroll-behavior:smooth}body{margin:0;overflow-x:hidden;background:var(--oat);color:var(--ink);font-family:var(--sans);text-rendering:optimizeLegibility}body.menu-open,body.modal-open{overflow:hidden}button,input,textarea,select{font:inherit}button,a{-webkit-tap-highlight-color:transparent}a{color:inherit;text-decoration:none}img{display:block;max-width:100%}::selection{background:var(--acid);color:var(--pine-950)}
    .display{font-family:var(--display)}.wrap{width:min(1240px,calc(100% - 40px));margin-inline:auto}.safe-top{padding-top:max(12px,env(safe-area-inset-top))}.safe-bottom{padding-bottom:max(16px,env(safe-area-inset-bottom))}.paper-grid{background-image:linear-gradient(rgba(9,37,29,.045) 1px,transparent 1px),linear-gradient(90deg,rgba(9,37,29,.045) 1px,transparent 1px);background-size:30px 30px}.topo-dark{background-image:radial-gradient(circle at 16% 24%,rgba(223,252,98,.13),transparent 23%),radial-gradient(circle at 82% 18%,rgba(242,123,74,.12),transparent 20%),url("data:image/svg+xml,%3Csvg width='900' height='900' viewBox='0 0 900 900' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' stroke='%23ffffff' stroke-opacity='.055' stroke-width='1.2'%3E%3Cpath d='M89 231c42-122 183-201 313-145 107 46 128 172 65 257-59 80-174 69-233 151-61 84-48 222-161 268-110 45-231-48-204-166 26-111 147-116 166-218 11-59-4-101 54-147Z'/%3E%3Cpath d='M142 267c31-91 136-151 233-109 80 34 95 128 48 191-44 59-129 51-174 112-45 63-35 165-120 199-82 34-172-35-152-123 20-83 110-86 124-163 8-44-3-75 41-107Z'/%3E%3Cpath d='M544 451c64-92 184-122 271-53 84 66 66 191-18 247-77 51-172 20-232 89-53 60-38 153-115 177-85 26-166-52-138-136 27-77 119-76 162-146 34-55 34-119 70-178Z'/%3E%3Cpath d='M584 484c47-69 138-91 202-40 63 49 49 142-14 184-57 38-128 15-173 66-40 45-28 114-85 132-64 20-124-39-103-101 20-57 89-56 121-108 26-41 26-89 52-133Z'/%3E%3C/g%3E%3C/svg%3E");background-size:auto,auto,900px 900px}.grain{position:relative}.grain::after{content:'';position:absolute;inset:0;z-index:2;pointer-events:none;opacity:.08;mix-blend-mode:soft-light;background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 180 180' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.82' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.55'/%3E%3C/svg%3E")}
    #scrollProgress{position:fixed;z-index:180;top:0;left:0;width:100%;height:3px;background:var(--acid);transform:scaleX(0);transform-origin:left center}.site-header{position:fixed;inset:0 0 auto;z-index:120;padding-inline:20px;pointer-events:none}.nav{width:min(1240px,100%);height:72px;margin:0 auto;display:flex;align-items:center;justify-content:space-between;gap:20px;padding:0 14px 0 18px;color:white;border:1px solid rgba(255,255,255,.12);border-radius:24px;background:rgba(6,26,21,.72);backdrop-filter:blur(22px) saturate(130%);box-shadow:0 22px 60px -42px rgba(0,0,0,.92);pointer-events:auto;transition:.35s ease}.nav.scrolled{height:64px;margin-top:6px;background:rgba(6,26,21,.9)}
    .brand{display:inline-flex;align-items:center;gap:11px;min-width:0}.brand-mark{width:42px;height:42px;display:grid;place-items:center;border-radius:15px;background:var(--acid);color:var(--pine-950);flex:none}.brand-name{display:block;font-family:var(--display);font-size:20px;font-weight:700;line-height:1}.brand-sub{display:block;margin-top:4px;font-size:8px;font-weight:700;text-transform:uppercase;letter-spacing:.16em;color:rgba(255,255,255,.5);white-space:nowrap}.nav-links{display:flex;align-items:center;gap:25px;font-size:12px;font-weight:700}.nav-links a{color:rgba(255,255,255,.76);transition:.2s}.nav-links a:hover,.nav-links a.active{color:white}.nav-actions{display:flex;align-items:center;gap:9px}.nav-icon{width:42px;height:42px;display:grid;place-items:center;border:1px solid rgba(255,255,255,.12);border-radius:15px;background:rgba(255,255,255,.05);color:white;cursor:pointer}.ticket-btn{height:42px;padding:0 17px;display:inline-flex;align-items:center;justify-content:center;border-radius:14px;background:var(--acid);color:var(--pine-950);font-size:11px;font-weight:800;white-space:nowrap}.mobile-trigger{display:none}
    .mobile-menu{position:fixed;inset:0;z-index:160;visibility:hidden;pointer-events:none}.mobile-menu.open{visibility:visible;pointer-events:auto}.menu-backdrop{position:absolute;inset:0;background:rgba(3,15,12,.72);opacity:0;transition:.3s}.mobile-menu.open .menu-backdrop{opacity:1}.menu-panel{position:absolute;top:0;right:0;width:min(420px,92vw);height:100%;padding:24px;background:var(--cream);transform:translateX(100%);transition:.38s cubic-bezier(.2,.75,.2,1);overflow:auto}.mobile-menu.open .menu-panel{transform:none}.menu-head{display:flex;justify-content:space-between;align-items:center}.menu-close{width:44px;height:44px;border:1px solid var(--line);border-radius:15px;background:white;cursor:pointer}.menu-links{display:grid;gap:5px;margin-top:40px}.menu-links a{padding:16px 4px;border-bottom:1px solid var(--line);font-family:var(--display);font-size:28px}.menu-cta{margin-top:28px;display:grid;gap:10px}
    .btn{min-height:48px;padding:0 21px;display:inline-flex;align-items:center;justify-content:center;gap:10px;border:0;border-radius:16px;font-size:12px;font-weight:800;cursor:pointer;transition:transform .2s ease,box-shadow .2s ease,background .2s}.btn:hover{transform:translateY(-2px)}.btn-acid{background:var(--acid);color:var(--pine-950);box-shadow:0 18px 52px -30px rgba(223,252,98,.72)}.btn-dark{background:var(--pine-900);color:white}.btn-cream{background:var(--cream);color:var(--pine-900)}.btn-outline{border:1px solid rgba(9,37,29,.16);background:transparent;color:var(--pine-900)}.btn-white-outline{border:1px solid rgba(255,255,255,.2);background:rgba(255,255,255,.04);color:white}.eyebrow{display:inline-flex;align-items:center;gap:9px;font-size:10px;font-weight:800;letter-spacing:.18em;text-transform:uppercase;color:var(--pine-700)}.eyebrow::before{content:'';width:22px;height:1px;background:currentColor}.eyebrow.light{color:var(--acid)}.title-xl{font-family:var(--display);font-size:clamp(52px,7.8vw,112px);line-height:.88;letter-spacing:-.06em;margin:0}.title-lg{font-family:var(--display);font-size:clamp(40px,5vw,74px);line-height:.98;letter-spacing:-.045em;margin:0}.title-md{font-family:var(--display);font-size:clamp(34px,4vw,58px);line-height:1;letter-spacing:-.04em;margin:0}.muted{color:rgba(22,35,30,.62)}
    .hero{min-height:710px;padding:142px 0 72px;background:var(--pine-950);color:white;position:relative;overflow:hidden}.hero::before{content:'';position:absolute;inset:0;background:linear-gradient(90deg,rgba(6,26,21,.95),rgba(6,26,21,.78) 47%,rgba(6,26,21,.22) 78%,rgba(6,26,21,.6)),url('https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=2200&q=88') center/cover no-repeat}.hero::after{content:'';position:absolute;inset:auto 0 0;height:190px;background:linear-gradient(transparent,var(--pine-950))}.hero-inner{position:relative;z-index:3;display:grid;grid-template-columns:minmax(0,1.1fr) minmax(340px,.72fr);gap:68px;align-items:end}.hero-copy p{max-width:680px;margin:24px 0 0;font-size:18px;line-height:1.72;color:rgba(255,255,255,.72)}.hero-search{margin-top:32px;position:relative}.search-box{display:grid;grid-template-columns:54px 1fr auto;align-items:center;gap:8px;padding:8px;border-radius:22px;background:var(--cream);box-shadow:var(--shadow-dark)}.search-box svg{margin-left:13px;color:var(--pine-700)}.search-box input{height:52px;border:0;outline:0;background:transparent;color:var(--ink);font-size:14px;min-width:0}.search-box .btn{min-height:52px}.suggestions{position:absolute;top:calc(100% + 10px);left:0;right:0;z-index:15;display:none;padding:10px;border-radius:20px;background:var(--cream);box-shadow:var(--shadow-dark);color:var(--ink)}.suggestions.open{display:grid}.suggestion{width:100%;display:flex;justify-content:space-between;gap:16px;padding:13px;border:0;border-radius:14px;background:none;text-align:left;cursor:pointer}.suggestion:hover{background:rgba(9,37,29,.06)}.suggestion strong{font-size:11px}.suggestion span{font-size:9px;color:rgba(22,35,30,.45)}.popular-row{display:flex;flex-wrap:wrap;gap:8px;margin-top:15px}.popular-chip{padding:9px 12px;border:1px solid rgba(255,255,255,.16);border-radius:999px;background:rgba(255,255,255,.05);color:rgba(255,255,255,.76);font-size:9px;font-weight:700;cursor:pointer}.popular-chip:hover{border-color:var(--acid);color:white}
    .hero-card{padding:27px;border:1px solid rgba(255,255,255,.13);border-radius:30px;background:rgba(7,29,23,.73);backdrop-filter:blur(20px);box-shadow:var(--shadow-dark)}.hero-card-head{display:flex;justify-content:space-between;gap:20px}.hero-card-head small{font-size:9px;text-transform:uppercase;letter-spacing:.15em;color:var(--acid)}.hero-card h2{font-family:var(--display);font-size:34px;line-height:1.04;margin:14px 0 8px}.hero-card p{margin:0;font-size:11px;line-height:1.65;color:rgba(255,255,255,.58)}.answer-stats{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-top:22px}.answer-stat{padding:15px;border:1px solid rgba(255,255,255,.1);border-radius:18px;background:rgba(255,255,255,.05)}.answer-stat strong{display:block;font-family:var(--display);font-size:28px;color:white}.answer-stat span{display:block;margin-top:3px;font-size:8px;text-transform:uppercase;letter-spacing:.12em;color:rgba(255,255,255,.38)}.hero-route{width:100%;height:120px;margin-top:20px}.hero-route path{fill:none;stroke:var(--acid);stroke-width:3;stroke-linecap:round;stroke-dasharray:9 13;filter:drop-shadow(0 0 8px rgba(223,252,98,.35))}.hero-route circle{fill:var(--acid)}
    .ops-strip{background:var(--pine-950);color:white;border-top:1px solid rgba(255,255,255,.08)}.ops-inner{display:grid;grid-template-columns:repeat(4,1fr)}.ops-item{min-height:82px;padding:18px 22px;display:flex;align-items:center;gap:12px;border-right:1px solid rgba(255,255,255,.08)}.ops-item:last-child{border-right:0}.ops-icon{width:36px;height:36px;display:grid;place-items:center;border-radius:13px;background:rgba(255,255,255,.06);color:var(--acid);flex:none}.ops-item small{display:block;font-size:8px;text-transform:uppercase;letter-spacing:.13em;color:rgba(255,255,255,.36)}.ops-item strong{display:block;margin-top:4px;font-size:10px;color:rgba(255,255,255,.82)}
    .category-section{padding:96px 0}.section-head{display:grid;grid-template-columns:1fr .55fr;gap:50px;align-items:end;margin-bottom:36px}.section-head p{font-size:13px;line-height:1.72}.category-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.category-card{min-height:230px;padding:22px;display:flex;flex-direction:column;justify-content:space-between;border:1px solid var(--line);border-radius:28px;background:var(--cream);box-shadow:var(--shadow);cursor:pointer;transition:.28s;position:relative;overflow:hidden}.category-card::after{content:'';position:absolute;inset:auto -25px -50px auto;width:130px;height:130px;border:1px solid rgba(9,37,29,.08);border-radius:50%}.category-card:hover,.category-card.active{transform:translateY(-5px);border-color:rgba(9,37,29,.26)}.category-card.active{background:var(--pine-900);color:white}.category-icon{width:48px;height:48px;display:grid;place-items:center;border-radius:17px;background:var(--acid);color:var(--pine-950)}.category-card h3{font-family:var(--display);font-size:27px;line-height:1.05;margin:30px 0 9px}.category-card p{margin:0;font-size:10px;line-height:1.6;color:rgba(22,35,30,.54)}.category-card.active p{color:rgba(255,255,255,.55)}.category-foot{display:flex;justify-content:space-between;align-items:center;margin-top:16px;font-size:9px;font-weight:800}.category-count{padding:6px 9px;border-radius:999px;background:rgba(9,37,29,.07)}.category-card.active .category-count{background:rgba(255,255,255,.1)}
    .faq-workspace{padding:100px 0;background:var(--cream)}.workspace{display:grid;grid-template-columns:280px minmax(0,1fr);gap:34px}.filter-sidebar{position:sticky;top:96px;height:max-content;padding:20px;border:1px solid var(--line);border-radius:26px;background:white;box-shadow:var(--shadow)}.filter-sidebar h3{margin:0 0 13px;font-family:var(--display);font-size:25px}.filter-list{display:grid;gap:6px}.filter-btn{width:100%;padding:12px 13px;display:flex;align-items:center;justify-content:space-between;gap:12px;border:0;border-radius:14px;background:transparent;color:var(--ink);text-align:left;font-size:10px;font-weight:700;cursor:pointer}.filter-btn span:last-child{color:rgba(22,35,30,.38)}.filter-btn:hover{background:rgba(9,37,29,.05)}.filter-btn.active{background:var(--pine-900);color:white}.filter-btn.active span:last-child{color:rgba(255,255,255,.5)}.sidebar-note{margin-top:18px;padding:17px;border-radius:18px;background:var(--oat)}.sidebar-note strong{font-family:var(--display);font-size:19px}.sidebar-note p{margin:8px 0 0;font-size:9px;line-height:1.6;color:rgba(22,35,30,.54)}.mobile-filters{display:none;overflow:auto;gap:7px;padding-bottom:4px;margin-bottom:22px;scrollbar-width:none}.mobile-filters::-webkit-scrollbar{display:none}.mobile-filter{white-space:nowrap;padding:10px 13px;border:1px solid var(--line);border-radius:999px;background:white;font-size:9px;font-weight:800}.mobile-filter.active{background:var(--pine-900);color:white;border-color:var(--pine-900)}
    .faq-main-head{display:flex;align-items:flex-end;justify-content:space-between;gap:25px;margin-bottom:22px}.faq-main-head h2{font-family:var(--display);font-size:clamp(34px,4vw,54px);line-height:1;margin:0}.results-count{font-size:9px;text-transform:uppercase;letter-spacing:.13em;color:rgba(22,35,30,.44)}.faq-list{display:grid;gap:10px}.faq-item{border:1px solid var(--line);border-radius:22px;background:white;overflow:hidden;transition:.25s}.faq-item[hidden]{display:none}.faq-item.open{box-shadow:var(--shadow)}.faq-q{width:100%;padding:20px;display:grid;grid-template-columns:38px 1fr 34px;align-items:center;gap:13px;border:0;background:none;text-align:left;color:var(--ink);cursor:pointer}.faq-number{width:36px;height:36px;display:grid;place-items:center;border-radius:13px;background:var(--oat);font-family:var(--display);font-size:14px}.faq-q strong{font-size:12px;line-height:1.45}.faq-plus{width:32px;height:32px;display:grid;place-items:center;border-radius:12px;background:var(--pine-900);color:var(--acid);font-size:18px;transition:.25s}.faq-item.open .faq-plus{transform:rotate(45deg)}.faq-a{max-height:0;overflow:hidden;transition:max-height .38s ease}.faq-answer{padding:0 20px 22px 71px}.faq-answer p{margin:0;font-size:11px;line-height:1.75;color:rgba(22,35,30,.62)}.faq-answer ul{margin:13px 0 0;padding-left:18px;font-size:10px;line-height:1.75;color:rgba(22,35,30,.62)}.answer-links{display:flex;flex-wrap:wrap;gap:8px;margin-top:16px}.answer-link{padding:9px 11px;border:1px solid var(--line);border-radius:12px;background:var(--cream);font-size:9px;font-weight:800}.helpful{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-top:18px;padding-top:15px;border-top:1px solid var(--line)}.helpful span{font-size:9px;color:rgba(22,35,30,.46)}.helpful-actions{display:flex;gap:6px}.helpful-btn{width:34px;height:34px;display:grid;place-items:center;border:1px solid var(--line);border-radius:12px;background:white;cursor:pointer}.empty-state{display:none;padding:54px 24px;text-align:center;border:1px dashed rgba(9,37,29,.2);border-radius:26px}.empty-state.show{display:block}.empty-state h3{font-family:var(--display);font-size:30px;margin:0}.empty-state p{max-width:520px;margin:12px auto 20px;font-size:11px;line-height:1.7;color:rgba(22,35,30,.56)}
    .guide-section{padding:100px 0}.guide-grid{display:grid;grid-template-columns:.82fr 1.18fr;gap:24px}.guide-copy{padding:35px;border-radius:32px;background:var(--pine-900);color:white}.guide-copy p{font-size:12px;line-height:1.72;color:rgba(255,255,255,.6)}.guide-note{margin-top:25px;padding:17px;border:1px solid rgba(255,255,255,.11);border-radius:19px;background:rgba(255,255,255,.05)}.guide-note strong{display:block;font-family:var(--display);font-size:22px}.guide-note span{display:block;margin-top:6px;font-size:9px;line-height:1.55;color:rgba(255,255,255,.48)}.guide-panel{padding:28px;border:1px solid var(--line);border-radius:32px;background:var(--cream);box-shadow:var(--shadow)}.guide-step{display:none}.guide-step.active{display:block}.guide-step h3{font-family:var(--display);font-size:34px;line-height:1.05;margin:0 0 8px}.guide-step>p{margin:0 0 22px;font-size:11px;color:rgba(22,35,30,.56)}.guide-options{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.guide-option{min-height:130px;padding:17px;border:1px solid var(--line);border-radius:20px;background:white;text-align:left;cursor:pointer}.guide-option:hover{border-color:rgba(9,37,29,.3)}.guide-option strong{display:block;font-family:var(--display);font-size:20px}.guide-option span{display:block;margin-top:7px;font-size:9px;line-height:1.5;color:rgba(22,35,30,.48)}.guide-progress{display:flex;gap:6px;margin-bottom:22px}.guide-progress i{height:4px;flex:1;border-radius:999px;background:rgba(9,37,29,.1)}.guide-progress i.active{background:var(--acid)}.guide-result{padding:23px;border-radius:24px;background:var(--oat)}.guide-result small{font-size:8px;text-transform:uppercase;letter-spacing:.13em;color:rgba(22,35,30,.4)}.guide-result h4{font-family:var(--display);font-size:31px;margin:8px 0}.guide-result p{font-size:10px;line-height:1.65;color:rgba(22,35,30,.58)}.guide-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:17px}
    .support-cta{padding:76px 0;background:var(--ember)}.support-card{display:grid;grid-template-columns:1fr auto;gap:40px;align-items:center}.support-card h2{font-family:var(--display);font-size:clamp(38px,5vw,68px);line-height:.95;margin:0}.support-card p{max-width:700px;margin:16px 0 0;font-size:12px;line-height:1.68}.support-actions{display:flex;gap:9px;flex-wrap:wrap;justify-content:flex-end}
    footer{padding:72px 0 28px;background:var(--pine-950);color:white}.footer-grid{display:grid;grid-template-columns:.8fr 1.2fr;gap:70px}.footer-brand p{max-width:340px;font-size:11px;line-height:1.65;color:rgba(255,255,255,.46)}.footer-cols{display:grid;grid-template-columns:repeat(4,1fr);gap:24px}.footer-col h4{margin:0 0 14px;font-size:9px;text-transform:uppercase;letter-spacing:.14em;color:rgba(255,255,255,.35)}.footer-col a{display:block;margin:10px 0;font-size:11px;color:rgba(255,255,255,.66)}.footer-col a:hover{color:white}.footer-bottom{display:flex;justify-content:space-between;gap:20px;margin-top:52px;padding-top:22px;border-top:1px solid rgba(255,255,255,.09);font-size:9px;color:rgba(255,255,255,.36)}.toast{position:fixed;left:50%;bottom:22px;z-index:260;max-width:calc(100% - 28px);padding:13px 17px;border-radius:999px;background:var(--pine-900);color:white;box-shadow:var(--shadow-dark);font-size:10px;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;transform:translate(-50%,130%);transition:.35s}.toast.show{transform:translate(-50%,0)}[data-reveal]{opacity:0;transform:translateY(28px)}
    @media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;animation:none!important;transition:none!important}[data-reveal]{opacity:1!important;transform:none!important}}
    @media(max-width:1050px){.nav-links{display:none}.mobile-trigger{display:grid}.hero-inner{grid-template-columns:1fr .75fr;gap:30px}.category-grid{grid-template-columns:1fr 1fr}.workspace{grid-template-columns:240px 1fr}.guide-grid{grid-template-columns:1fr}.footer-grid{grid-template-columns:1fr}.footer-cols{grid-template-columns:repeat(4,1fr)}}
    @media(max-width:760px){.wrap{width:min(100% - 28px,1240px)}.site-header{padding-inline:12px}.nav{height:62px;border-radius:20px;padding:0 9px 0 12px;gap:9px}.brand-mark{width:38px;height:38px;border-radius:13px}.brand-name{font-size:17px}.brand-sub{display:none}.ticket-btn{height:39px;padding:0 12px}.nav-icon{width:39px;height:39px}.hero{min-height:auto;padding:116px 0 48px}.hero-inner{grid-template-columns:1fr;gap:25px}.hero-copy p{font-size:15px}.search-box{grid-template-columns:42px 1fr;padding:6px}.search-box .btn{grid-column:1/-1;width:100%}.search-box svg{margin-left:9px}.hero-card{padding:22px;border-radius:24px}.hero-route{height:90px}.ops-inner{grid-template-columns:1fr 1fr;padding-bottom:16px}.category-section,.faq-workspace,.guide-section{padding:72px 0}.section-head{grid-template-columns:1fr;gap:16px;margin-bottom:27px}.category-grid{grid-template-columns:1fr}.category-card{min-height:205px}.workspace{grid-template-columns:1fr}.filter-sidebar{display:none}.mobile-filters{display:flex}.faq-main-head{align-items:flex-start;display:grid;gap:8px}.faq-q{grid-template-columns:34px 1fr 32px;padding:17px 15px;gap:10px}.faq-number{width:32px;height:32px}.faq-answer{padding:0 15px 20px}.helpful{align-items:flex-start}.guide-copy,.guide-panel{padding:24px;border-radius:25px}.guide-options{grid-template-columns:1fr}.guide-option{min-height:105px}.support-card{grid-template-columns:1fr}.support-actions{justify-content:flex-start}.support-actions .btn{flex:1}.footer-cols{grid-template-columns:1fr 1fr}.footer-bottom{display:grid}}
    @media(max-width:420px){.nav-actions{gap:6px}.ticket-btn{font-size:10px;padding:0 10px}.ops-inner{grid-template-columns:1fr}.answer-stats{grid-template-columns:1fr}.footer-cols{grid-template-columns:1fr}.support-actions{display:grid}.title-xl{font-size:50px}.popular-row{flex-wrap:nowrap;overflow:auto;padding-bottom:4px;scrollbar-width:none}.popular-row::-webkit-scrollbar{display:none}.popular-chip{white-space:nowrap}.faq-q strong{font-size:11px}.guide-actions{display:grid}.guide-actions .btn{width:100%}}
  </style>
</head>
<body>
  <div id="scrollProgress" aria-hidden="true"></div>
  <?php $nvNoSpacer = true; include __DIR__ . '/includes/header.php'; ?>

  <main>
    <section class="hero topo-dark grain">
      <div class="wrap hero-inner">
        <div class="hero-copy" data-reveal><span class="eyebrow light">Centrul de răspunsuri</span><h1 class="title-xl" style="margin-top:18px">Întrebarea ta<br><em style="color:var(--acid);font-style:normal">are un traseu.</em></h1><p>De la alegerea biletului până la vreme, acces, copii sau rambursări — caută direct sau explorează răspunsurile organizate după momentul vizitei.</p>
          <div class="hero-search"><div class="search-box"><svg width="22" height="22" viewBox="0 0 24 24" fill="none"><circle cx="11" cy="11" r="6.5" stroke="currentColor" stroke-width="1.7"/><path d="m16 16 4 4" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/></svg><input id="heroSearch" type="search" autocomplete="off" placeholder="Ex. Ce se întâmplă dacă plouă?" aria-label="Caută în întrebările frecvente"><button class="btn btn-dark" id="searchSubmit" type="button">Caută răspunsul</button></div><div class="suggestions" id="suggestions"></div></div>
          <div class="popular-row"><button class="popular-chip" type="button" data-query="ploaie">Dacă plouă</button><button class="popular-chip" type="button" data-query="copii">Acces copii</button><button class="popular-chip" type="button" data-query="schimb data">Schimbarea datei</button><button class="popular-chip" type="button" data-query="parcare">Parcare</button><button class="popular-chip" type="button" data-query="voucher">Voucher</button></div>
        </div>
        <aside class="hero-card" data-reveal><div class="hero-card-head"><div><small>Bibliotecă actualizată</small><h2>Răspunsuri înainte de potecă.</h2></div><span style="width:42px;height:42px;display:grid;place-items:center;border-radius:15px;background:var(--acid);color:var(--pine-950)">?</span></div><p>Conținut demonstrativ pentru un tenant leisure Tixello. Întrebările sunt organizate pentru decizii rapide, nu pentru lectură inutilă.</p><div class="answer-stats"><div class="answer-stat"><strong>34</strong><span>răspunsuri</span></div><div class="answer-stat"><strong>6</strong><span>categorii</span></div><div class="answer-stat"><strong>&lt; 2m</strong><span>timp mediu</span></div><div class="answer-stat"><strong>Live</strong><span>suport disponibil</span></div></div><svg class="hero-route" viewBox="0 0 500 120" aria-hidden="true"><path id="heroRoute" d="M12 95C70 79 93 26 151 50c62 25 98 54 154 16 47-32 78-59 129-27 29 18 31 47 54 51"/><circle id="heroMarker" cx="12" cy="95" r="7"/></svg></aside>
      </div>
    </section>
    <section class="ops-strip"><div class="wrap ops-inner"><div class="ops-item"><span class="ops-icon">✓</span><span><small>Parc</small><strong>Deschis · 09:00–20:00</strong></span></div><div class="ops-item"><span class="ops-icon">☁</span><span><small>Vreme</small><strong>24°C · trasee active</strong></span></div><div class="ops-item"><span class="ops-icon">↗</span><span><small>Shuttle</small><strong>La fiecare 30 minute</strong></span></div><div class="ops-item"><span class="ops-icon">●</span><span><small>Suport</small><strong>Răspuns în aceeași zi</strong></span></div></div></section>

    <section class="category-section paper-grid" id="categorii"><div class="wrap"><div class="section-head" data-reveal><div><span class="eyebrow">Explorează după subiect</span><h2 class="title-lg" style="margin-top:14px">Șase puncte de pornire.<br>Un singur răspuns bun.</h2></div><p class="muted">Alege categoria cea mai apropiată de situația ta. Filtrul poate fi schimbat oricând, iar căutarea funcționează în toate răspunsurile.</p></div><div class="category-grid" id="categoryGrid">
      <button class="category-card active" type="button" data-category="all"><span class="category-icon">⌁</span><div><h3>Toate răspunsurile</h3><p>Vezi întreaga bibliotecă și caută liber.</p></div><div class="category-foot"><span>Bibliotecă completă</span><span class="category-count">34</span></div></button>
      <button class="category-card" type="button" data-category="tickets"><span class="category-icon">✦</span><div><h3>Bilete & rezervări</h3><p>Prețuri, date, intervale, transfer și acces.</p></div><div class="category-foot"><span>Înainte de cumpărare</span><span class="category-count">8</span></div></button>
      <button class="category-card" type="button" data-category="visit"><span class="category-icon">↗</span><div><h3>Planificarea vizitei</h3><p>Program, parcare, shuttle, facilități și echipament.</p></div><div class="category-foot"><span>Înainte de plecare</span><span class="category-count">7</span></div></button>
      <button class="category-card" type="button" data-category="experiences"><span class="category-icon">△</span><div><h3>Experiențe & siguranță</h3><p>Vârstă, înălțime, dificultate și pregătire.</p></div><div class="category-foot"><span>Pe traseu</span><span class="category-count">6</span></div></button>
      <button class="category-card" type="button" data-category="weather"><span class="category-icon">☂</span><div><h3>Vreme & modificări</h3><p>Ploaie, vânt, reprogramări și rambursări.</p></div><div class="category-foot"><span>Când planul se schimbă</span><span class="category-count">5</span></div></button>
      <button class="category-card" type="button" data-category="account"><span class="category-icon">○</span><div><h3>Cont, voucher & membership</h3><p>Cont client, beneficii, cadouri și coduri.</p></div><div class="category-foot"><span>După achiziție</span><span class="category-count">8</span></div></button>
    </div></div></section>

    <section class="faq-workspace" id="raspunsuri"><div class="wrap workspace"><aside class="filter-sidebar"><h3>Filtrează biblioteca</h3><div class="filter-list"><button class="filter-btn active" type="button" data-filter="all"><span>Toate</span><span>34</span></button><button class="filter-btn" type="button" data-filter="tickets"><span>Bilete & rezervări</span><span>8</span></button><button class="filter-btn" type="button" data-filter="visit"><span>Planifică vizita</span><span>7</span></button><button class="filter-btn" type="button" data-filter="experiences"><span>Experiențe</span><span>6</span></button><button class="filter-btn" type="button" data-filter="weather"><span>Vreme & modificări</span><span>5</span></button><button class="filter-btn" type="button" data-filter="account"><span>Cont & voucher</span><span>8</span></button></div><div class="sidebar-note"><strong>Nu găsești situația?</strong><p>Trimite o solicitare publică sau intră în cont pentru suport asociat direct comenzii.</p><a class="btn btn-dark" style="width:100%;margin-top:13px" href="/contact">Contactează-ne</a></div></aside>
      <div><div class="mobile-filters" id="mobileFilters"><button class="mobile-filter active" type="button" data-filter="all">Toate</button><button class="mobile-filter" type="button" data-filter="tickets">Bilete</button><button class="mobile-filter" type="button" data-filter="visit">Vizită</button><button class="mobile-filter" type="button" data-filter="experiences">Experiențe</button><button class="mobile-filter" type="button" data-filter="weather">Vreme</button><button class="mobile-filter" type="button" data-filter="account">Cont</button></div><div class="faq-main-head"><div><span class="eyebrow">Biblioteca Nordvale</span><h2 style="margin-top:12px">Răspunsuri esențiale.</h2></div><span class="results-count" id="resultsCount">12 răspunsuri afișate</span></div><div class="faq-list" id="faqList">

      <article class="faq-item" data-category="tickets" data-keywords="bilet bilete cumpărare online casierie acces"><button class="faq-q" type="button"><span class="faq-number">01</span><strong>De unde cumpăr biletele și primesc accesul?</strong><span class="faq-plus">+</span></button><div class="faq-a"><div class="faq-answer"><p>Biletele se cumpără online prin tenantul Nordvale Tixello. După plata confirmată, fiecare participant primește un bilet digital cu QR, disponibil pe email și în cont.</p><div class="answer-links"><a class="answer-link" href="/bilete">Vezi biletele</a><a class="answer-link" href="/cont/bilete">Biletele mele</a></div><div class="helpful"><span>A fost util răspunsul?</span><div class="helpful-actions"><button class="helpful-btn" type="button" data-helpful="yes">↑</button><button class="helpful-btn" type="button" data-helpful="no">↓</button></div></div></div></div></article>
      <article class="faq-item" data-category="tickets" data-keywords="schimb data modificare rezervare interval reprogramare"><button class="faq-q" type="button"><span class="faq-number">02</span><strong>Pot schimba data sau ora rezervării?</strong><span class="faq-plus">+</span></button><div class="faq-a"><div class="faq-answer"><p>Da, dacă pachetul și intervalul permit modificarea. Din cont, deschide biletul sau comanda și alege „Schimbă data”. Pentru cereri speciale există fluxul dedicat de modificare.</p><ul><li>Schimbarea este disponibilă în limita locurilor.</li><li>Unele tarife promoționale pot avea restricții.</li><li>Diferențele de preț se recalculează înainte de confirmare.</li></ul><div class="answer-links"><a class="answer-link" href="/cont/rambursare">Solicită modificarea</a></div><div class="helpful"><span>A fost util răspunsul?</span><div class="helpful-actions"><button class="helpful-btn" type="button" data-helpful="yes">↑</button><button class="helpful-btn" type="button" data-helpful="no">↓</button></div></div></div></div></article>
      <article class="faq-item" data-category="tickets" data-keywords="copii tarif copil vârstă gratuit familie"><button class="faq-q" type="button"><span class="faq-number">03</span><strong>Copiii au tarif separat?</strong><span class="faq-plus">+</span></button><div class="faq-a"><div class="faq-answer"><p>Da. Tarifele pentru copii sunt configurate separat și pot varia după experiență. Pachetul Family Trail aplică prețuri și beneficii dedicate familiilor.</p><p>Înălțimea și vârsta minimă sunt reguli de siguranță ale experienței, nu doar criterii tarifare.</p><div class="helpful"><span>A fost util răspunsul?</span><div class="helpful-actions"><button class="helpful-btn" type="button" data-helpful="yes">↑</button><button class="helpful-btn" type="button" data-helpful="no">↓</button></div></div></div></div></article>
      <article class="faq-item" data-category="visit" data-keywords="parcare mașină acces adresă autoturism"><button class="faq-q" type="button"><span class="faq-number">04</span><strong>Există parcare și trebuie rezervată?</strong><span class="faq-plus">+</span></button><div class="faq-a"><div class="faq-answer"><p>Parcarea principală este la intrarea sudică. Locul standard este inclus în limita capacității, iar parcarea rezervată aproape de Visitor Base poate fi adăugată ca supliment.</p><div class="answer-links"><a class="answer-link" href="/planifica">Acces și hartă</a></div><div class="helpful"><span>A fost util răspunsul?</span><div class="helpful-actions"><button class="helpful-btn" type="button" data-helpful="yes">↑</button><button class="helpful-btn" type="button" data-helpful="no">↓</button></div></div></div></div></article>
      <article class="faq-item" data-category="visit" data-keywords="shuttle transport brașov autobuz gara"><button class="faq-q" type="button"><span class="faq-number">05</span><strong>Cum funcționează shuttle-ul Nordvale?</strong><span class="faq-plus">+</span></button><div class="faq-a"><div class="faq-answer"><p>Shuttle-ul demonstrativ pleacă din Gara Brașov la ore fixe și circulă la fiecare 30 de minute între parcarea sudică și Visitor Base. Orarul exact este afișat în pagina Planifică vizita.</p><div class="helpful"><span>A fost util răspunsul?</span><div class="helpful-actions"><button class="helpful-btn" type="button" data-helpful="yes">↑</button><button class="helpful-btn" type="button" data-helpful="no">↓</button></div></div></div></div></article>
      <article class="faq-item" data-category="visit" data-keywords="mâncare restaurant apă picnic facilități"><button class="faq-q" type="button"><span class="faq-number">06</span><strong>Pot veni cu mâncare și există puncte de masă?</strong><span class="faq-plus">+</span></button><div class="faq-a"><div class="faq-answer"><p>Da, poți aduce gustări și apă. Consumul este permis în zonele de picnic marcate. La Visitor Base există un punct de masă, iar pachetul de prânz poate fi adăugat în coș.</p><div class="helpful"><span>A fost util răspunsul?</span><div class="helpful-actions"><button class="helpful-btn" type="button" data-helpful="yes">↑</button><button class="helpful-btn" type="button" data-helpful="no">↓</button></div></div></div></div></article>
      <article class="faq-item" data-category="experiences" data-keywords="vârstă înălțime greutate restricții copii canopy run"><button class="faq-q" type="button"><span class="faq-number">07</span><strong>Care sunt limitele de vârstă, înălțime și greutate?</strong><span class="faq-plus">+</span></button><div class="faq-a"><div class="faq-answer"><p>Fiecare experiență are propriile limite. Exemplul Canopy Run este recomandat de la 10 ani și are criterii de înălțime și greutate verificate la briefing. Datele exacte apar înainte de rezervare și pe bilet.</p><div class="answer-links"><a class="answer-link" href="/experienta">Detaliu experiență</a></div><div class="helpful"><span>A fost util răspunsul?</span><div class="helpful-actions"><button class="helpful-btn" type="button" data-helpful="yes">↑</button><button class="helpful-btn" type="button" data-helpful="no">↓</button></div></div></div></div></article>
      <article class="faq-item" data-category="experiences" data-keywords="echipament haine încălțăminte sport briefing"><button class="faq-q" type="button"><span class="faq-number">08</span><strong>Ce echipament trebuie să aduc?</strong><span class="faq-plus">+</span></button><div class="faq-a"><div class="faq-answer"><p>Recomandăm încălțăminte sport închisă, haine care permit mișcarea și un strat impermeabil ușor. Echipamentul tehnic de siguranță este furnizat și verificat de echipa Nordvale.</p><div class="helpful"><span>A fost util răspunsul?</span><div class="helpful-actions"><button class="helpful-btn" type="button" data-helpful="yes">↑</button><button class="helpful-btn" type="button" data-helpful="no">↓</button></div></div></div></div></article>
      <article class="faq-item" data-category="weather" data-keywords="ploaie vreme furtună vânt trasee suspendate"><button class="faq-q" type="button"><span class="faq-number">09</span><strong>Ce se întâmplă dacă plouă?</strong><span class="faq-plus">+</span></button><div class="faq-a"><div class="faq-answer"><p>Ploaia ușoară nu închide automat parcul. Activitățile se suspendă doar când vântul, furtuna sau condițiile traseului depășesc pragurile de siguranță. Primești notificare înainte de vizită și opțiuni de reprogramare când Nordvale suspendă experiența.</p><div class="answer-links"><a class="answer-link" href="/calendar">Status și disponibilitate</a></div><div class="helpful"><span>A fost util răspunsul?</span><div class="helpful-actions"><button class="helpful-btn" type="button" data-helpful="yes">↑</button><button class="helpful-btn" type="button" data-helpful="no">↓</button></div></div></div></div></article>
      <article class="faq-item" data-category="weather" data-keywords="rambursare anulare refund credit vreme"><button class="faq-q" type="button"><span class="faq-number">10</span><strong>Când pot solicita rambursarea?</strong><span class="faq-plus">+</span></button><div class="faq-a"><div class="faq-answer"><p>Eligibilitatea depinde de motiv, momentul solicitării și tipul biletului. Dacă experiența este anulată de operator, vei primi opțiunile disponibile: reprogramare, credit sau rambursare conform politicii afișate.</p><div class="answer-links"><a class="answer-link" href="/cont/rambursare">Deschide o cerere</a></div><div class="helpful"><span>A fost util răspunsul?</span><div class="helpful-actions"><button class="helpful-btn" type="button" data-helpful="yes">↑</button><button class="helpful-btn" type="button" data-helpful="no">↓</button></div></div></div></div></article>
      <article class="faq-item" data-category="account" data-keywords="voucher cod sold verificare activare cadou"><button class="faq-q" type="button"><span class="faq-number">11</span><strong>Cum verific și folosesc un voucher?</strong><span class="faq-plus">+</span></button><div class="faq-a"><div class="faq-answer"><p>Introdu codul în pagina de verificare pentru a vedea soldul și valabilitatea. Voucherul poate fi salvat în cont și aplicat la bilete, experiențe sau membership, în limita condițiilor sale.</p><div class="answer-links"><a class="answer-link" href="/voucher">Verifică voucherul</a></div><div class="helpful"><span>A fost util răspunsul?</span><div class="helpful-actions"><button class="helpful-btn" type="button" data-helpful="yes">↑</button><button class="helpful-btn" type="button" data-helpful="no">↓</button></div></div></div></div></article>
      <article class="faq-item" data-category="account" data-keywords="membership abonament beneficii invitați wallet"><button class="faq-q" type="button"><span class="faq-number">12</span><strong>Unde văd beneficiile membership-ului?</strong><span class="faq-plus">+</span></button><div class="faq-a"><div class="faq-answer"><p>În secțiunea „Abonamentele mele” găsești cardul digital, QR-ul de membru, invitațiile rămase, accesul prioritar, punctele și evenimentele private.</p><div class="answer-links"><a class="answer-link" href="/cont/abonamente">Membership-ul meu</a></div><div class="helpful"><span>A fost util răspunsul?</span><div class="helpful-actions"><button class="helpful-btn" type="button" data-helpful="yes">↑</button><button class="helpful-btn" type="button" data-helpful="no">↓</button></div></div></div></div></article>
      </div><div class="empty-state" id="emptyState"><h3>N-am găsit un răspuns exact.</h3><p>Încearcă un termen mai scurt sau trimite direct întrebarea echipei Nordvale. Pentru o comandă existentă, suportul din cont poate prelua automat datele rezervării.</p><a class="btn btn-dark" href="/contact">Trimite întrebarea</a></div></div>
    </div></section>

    <section class="guide-section paper-grid"><div class="wrap guide-grid"><article class="guide-copy topo-dark" data-reveal><span class="eyebrow light">Ghid rapid</span><h2 class="title-md" style="margin-top:15px">Nu știi ce tip de acces<br>ți se potrivește?</h2><p>Răspunde la două întrebări, iar ghidul îți recomandă un punct de pornire. Recomandarea este demonstrativă și nu înlocuiește regulile fiecărei experiențe.</p><div class="guide-note"><strong>Mai puține comparații.</strong><span>Ghidul filtrează întâi după grup și ritmul vizitei, apoi trimite către pachetul relevant.</span></div></article><article class="guide-panel" data-reveal><div class="guide-progress"><i class="active"></i><i></i><i></i></div><div class="guide-step active" data-step="1"><h3>Cu cine vii?</h3><p>Alege profilul principal al grupului.</p><div class="guide-options"><button class="guide-option" type="button" data-group="solo"><strong>Singur / cuplu</strong><span>Flexibilitate și experiențe intense.</span></button><button class="guide-option" type="button" data-group="family"><strong>Familie</strong><span>Ritm echilibrat și pauze incluse.</span></button><button class="guide-option" type="button" data-group="friends"><strong>Grup de prieteni</strong><span>Mai multe experiențe în aceeași zi.</span></button></div></div><div class="guide-step" data-step="2"><h3>Ce ritm preferați?</h3><p>Alege energia dominantă a zilei.</p><div class="guide-options"><button class="guide-option" type="button" data-energy="calm"><strong>Explorare calmă</strong><span>Poteci, natură și ritm fără grabă.</span></button><button class="guide-option" type="button" data-energy="balanced"><strong>Mix echilibrat</strong><span>Acces general plus o experiență.</span></button><button class="guide-option" type="button" data-energy="intense"><strong>Zi intensă</strong><span>Trasee premium și prioritate.</span></button></div></div><div class="guide-step" data-step="3"><div class="guide-result"><small>Recomandarea Nordvale</small><h4 id="guideTitle">Adventure Pass</h4><p id="guideText">Acces de o zi și o experiență principală, cu libertatea de a adăuga alte activități.</p><div class="guide-actions"><a class="btn btn-dark" id="guideLink" href="/bilete">Vezi pachetul</a><button class="btn btn-outline" id="guideReset" type="button">Reia ghidul</button></div></div></div></article></div></section>

    <section class="support-cta"><div class="wrap support-card"><div><span class="eyebrow" style="color:var(--pine-950)">Răspuns personalizat</span><h2>Întrebarea ta nu încape<br>într-un răspuns standard?</h2><p>Trimite situația exactă echipei Nordvale. Pentru rezervări existente, autentifică-te pentru ca numărul comenzii și biletele să fie asociate automat.</p></div><div class="support-actions"><a class="btn btn-dark" href="/contact">Contact public</a><a class="btn btn-cream" href="/cont/suport">Suport din cont</a></div></div></section>
  </main>

  <?php include __DIR__ . '/includes/footer.php'; ?>
  <div class="toast" id="toast">Mulțumim pentru feedback.</div>

  <script>
  (()=>{
    'use strict';
    const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
    const body=document.body, nav=$('#siteNav'), progress=$('#scrollProgress'), menu=$('#mobileMenu');
    const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
    function setMenu(open){menu?.classList.toggle('open',open);menu?.setAttribute('aria-hidden',String(!open));body.classList.toggle('menu-open',open)}
    $('#menuOpen')?.addEventListener('click',()=>setMenu(true));$('#menuClose')?.addEventListener('click',()=>setMenu(false));$('#menuBackdrop')?.addEventListener('click',()=>setMenu(false));
    function onScroll(){const y=scrollY,max=document.documentElement.scrollHeight-innerHeight;nav?.classList.toggle('scrolled',y>24);if(progress)progress.style.transform=`scaleX(${max>0?Math.min(1,y/max):0})`}addEventListener('scroll',onScroll,{passive:true});onScroll();
    if(!reduce&&'IntersectionObserver'in window){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.animate([{opacity:0,transform:'translateY(28px)'},{opacity:1,transform:'none'}],{duration:650,easing:'cubic-bezier(.2,.75,.2,1)',fill:'forwards'});io.unobserve(e.target)}}),{threshold:.12});$$('[data-reveal]').forEach(el=>io.observe(el))}else{$$('[data-reveal]').forEach(el=>{el.style.opacity=1;el.style.transform='none'})}
    function animatePath(path,marker,duration=2200){if(!path||!marker||reduce)return;const length=path.getTotalLength();path.style.strokeDasharray=length;path.style.strokeDashoffset=length;path.animate([{strokeDashoffset:length},{strokeDashoffset:0}],{duration,easing:'cubic-bezier(.2,.75,.2,1)',fill:'forwards',delay:260});const start=performance.now()+260;function move(t){const p=Math.max(0,Math.min(1,(t-start)/duration)),pt=path.getPointAtLength(length*p);marker.setAttribute('cx',pt.x);marker.setAttribute('cy',pt.y);if(p<1)requestAnimationFrame(move)}requestAnimationFrame(move)}animatePath($('#heroRoute'),$('#heroMarker'));

    const faqItems=$$('.faq-item'), results=$('#resultsCount'), empty=$('#emptyState'), search=$('#heroSearch'), suggestions=$('#suggestions');let activeFilter='all',activeQuery='';
    const suggestionData=[['ploaie','Ce se întâmplă dacă plouă?'],['copii','Copiii au tarif separat?'],['schimb data','Pot schimba data rezervării?'],['parcare','Există parcare?'],['voucher','Cum verific un voucher?'],['echipament','Ce echipament trebuie să aduc?']];
    function normalize(v){return v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim()}
    function applyFilters(scroll=true){const q=normalize(activeQuery);let visible=0;faqItems.forEach(item=>{const category=item.dataset.category,text=normalize(item.textContent+' '+item.dataset.keywords);const show=(activeFilter==='all'||category===activeFilter)&&(!q||text.includes(q));item.hidden=!show;if(show)visible++});results.textContent=`${visible} ${visible===1?'răspuns afișat':'răspunsuri afișate'}`;empty.classList.toggle('show',visible===0);if(scroll)$('#raspunsuri').scrollIntoView({behavior:reduce?'auto':'smooth',block:'start'})}
    function setFilter(filter,scroll=true){activeFilter=filter;$$('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));$$('[data-category]').forEach(b=>b.classList.toggle('active',b.dataset.category===filter));applyFilters(scroll)}
    $$('[data-filter]').forEach(b=>b.addEventListener('click',()=>setFilter(b.dataset.filter)));$$('[data-category]').forEach(b=>b.addEventListener('click',()=>setFilter(b.dataset.category)));
    function performSearch(value){activeQuery=value;search.value=value;suggestions.classList.remove('open');applyFilters(true)}
    search.addEventListener('input',()=>{const q=normalize(search.value);if(q.length<2){suggestions.classList.remove('open');return}const matches=suggestionData.filter(([key,label])=>normalize(key+' '+label).includes(q)).slice(0,5);suggestions.innerHTML=matches.map(([key,label])=>`<button class="suggestion" type="button" data-suggest="${key}"><strong>${label}</strong><span>Caută</span></button>`).join('');suggestions.classList.toggle('open',matches.length>0);$$('[data-suggest]',suggestions).forEach(b=>b.addEventListener('click',()=>performSearch(b.dataset.suggest)))});
    $('#searchSubmit').addEventListener('click',()=>performSearch(search.value));search.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();performSearch(search.value)}});$$('[data-query]').forEach(b=>b.addEventListener('click',()=>performSearch(b.dataset.query)));document.addEventListener('click',e=>{if(!e.target.closest('.hero-search'))suggestions.classList.remove('open')});
    $$('.faq-q').forEach(btn=>btn.addEventListener('click',()=>{const item=btn.closest('.faq-item'),open=item.classList.contains('open');faqItems.forEach(i=>{i.classList.remove('open');i.querySelector('.faq-a').style.maxHeight='0px'});if(!open){item.classList.add('open');const answer=item.querySelector('.faq-a');answer.style.maxHeight=answer.scrollHeight+'px'}}));
    const toast=$('#toast');function showToast(text){toast.textContent=text;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),2300)}$$('[data-helpful]').forEach(b=>b.addEventListener('click',()=>showToast(b.dataset.helpful==='yes'?'Mulțumim. Răspuns marcat ca util.':'Mulțumim. Vom îmbunătăți răspunsul.')));

    let guide={group:'',energy:''};const steps=$$('.guide-step'),bars=$$('.guide-progress i');
    function showStep(n){steps.forEach(s=>s.classList.toggle('active',Number(s.dataset.step)===n));bars.forEach((b,i)=>b.classList.toggle('active',i<n))}
    $$('[data-group]').forEach(b=>b.addEventListener('click',()=>{guide.group=b.dataset.group;showStep(2)}));$$('[data-energy]').forEach(b=>b.addEventListener('click',()=>{guide.energy=b.dataset.energy;const map={calm:['Explorer Pass','Acces general, poteci și ritm flexibil, fără rezervarea unei experiențe intense.'],balanced:[guide.group==='family'?'Family Trail':'Adventure Pass','Acces de o zi și o experiență principală, cu un ritm echilibrat.'],intense:['Summit Pass','Acces premium, experiențe multiple și prioritate pentru o zi intensă.']};const rec=map[guide.energy];$('#guideTitle').textContent=rec[0];$('#guideText').textContent=rec[1];showStep(3)}));$('#guideReset').addEventListener('click',()=>{guide={group:'',energy:''};showStep(1)});
    addEventListener('keydown',e=>{if(e.key==='Escape')setMenu(false)});applyFilters(false);
  })();
  </script>
</body>
</html>
