<?php
require_once __DIR__.'/includes/config.php';
require_once __DIR__.'/includes/api.php';

// Detaliile voucherului emis vin din pasul de cumpărare prin query params.
// Fallback pe valorile demo dacă lipsesc (pagina rămâne funcțională standalone).
$gcCode     = trim($_GET['code'] ?? '') ?: 'NORD-8Q2L-5MT7';
$gcAmount   = isset($_GET['amount']) && is_numeric($_GET['amount']) ? (float) $_GET['amount'] : 350;
$gcTo       = trim($_GET['to'] ?? '') ?: 'Mara';
$gcToFull   = trim($_GET['to_full'] ?? '') ?: ($gcTo !== 'Mara' ? $gcTo : 'Mara Pop');
$gcEmail    = trim($_GET['email'] ?? '') ?: 'mara@example.ro';
$gcMsg      = trim($_GET['msg'] ?? ($_GET['message'] ?? '')) ?: 'Pentru o zi cu aer curat, curaj și libertate. Să alegi aventura care te face să uiți de timp.';
$gcFrom     = trim($_GET['from'] ?? '') ?: 'andrei@example.ro';
$gcOrder    = trim($_GET['order'] ?? '') ?: 'NV-GIFT-2041';
$gcAmountFmt = price_fmt($gcAmount, 'RON');
?>
<!DOCTYPE html>
<html lang="ro" class="scroll-smooth">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <meta name="robots" content="noindex, nofollow">
  <meta name="theme-color" content="#061a15">
  <title>Voucher cadou confirmat — Nordvale</title>
  <meta name="description" content="Confirmarea voucherului cadou Nordvale, cu livrare, cod și acțiuni utile.">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Fraunces:opsz,wght@9..144,500;9..144,600;9..144,700&display=swap" rel="stylesheet">
  <style>
    :root{
      --pine-950:#061a15;--pine-900:#09251d;--pine-850:#0d3027;--pine-800:#123b30;--pine-700:#1b5242;
      --acid:#dffc62;--ember:#f27b4a;--sky:#8dd8ca;--cream:#fffdf6;--oat:#f0ecdf;--moss:#b7c9a3;
      --ink:#16231e;--muted:rgba(22,35,30,.62);--line:rgba(9,37,29,.13);
      --shadow:0 34px 100px -58px rgba(6,26,21,.78);--card-shadow:0 22px 62px -42px rgba(6,26,21,.58)
    }
    *{box-sizing:border-box}html{background:var(--oat);scroll-behavior:smooth}body{margin:0;overflow-x:hidden;background:var(--oat);color:var(--ink);font-family:"DM Sans",sans-serif;text-rendering:optimizeLegibility}button,input,select,textarea{font:inherit}button,a{touch-action:manipulation}button{cursor:pointer}a{color:inherit;text-decoration:none}img{display:block;max-width:100%}[hidden]{display:none!important}::selection{background:var(--acid);color:var(--pine-950)}
    .shell{width:min(1460px,calc(100% - 32px));margin-inline:auto}.site-header{position:sticky;top:0;z-index:90;padding:12px 0;background:linear-gradient(180deg,rgba(240,236,223,.98),rgba(240,236,223,.87),transparent)}
    .nav{display:flex;align-items:center;gap:16px;padding:10px 12px 10px 16px;border:1px solid rgba(255,255,255,.12);border-radius:22px;background:rgba(6,26,21,.92);box-shadow:0 24px 70px -46px rgba(0,0,0,.9);backdrop-filter:blur(22px) saturate(130%);color:#fff}.brand{display:flex;align-items:center;gap:11px;min-width:0}.brand-mark{display:grid;place-items:center;width:42px;height:42px;flex:0 0 auto;border:1px solid rgba(223,252,98,.42);border-radius:15px;background:rgba(223,252,98,.08);color:var(--acid)}.brand-copy{min-width:0;line-height:1}.brand-copy strong{display:block;font-family:"Fraunces",serif;font-size:18px;font-weight:600;letter-spacing:-.02em}.brand-copy span{display:block;margin-top:5px;color:rgba(255,255,255,.5);font-size:10px;font-weight:700;letter-spacing:.18em;text-transform:uppercase;white-space:nowrap}.main-nav{display:flex;align-items:center;gap:6px;margin-left:auto}.main-nav a{padding:10px 12px;border-radius:12px;color:rgba(255,255,255,.68);font-size:13px;font-weight:600}.main-nav a:hover{background:rgba(255,255,255,.07);color:#fff}.nav-actions{display:flex;align-items:center;gap:8px}.ticket-cta{display:inline-flex;align-items:center;justify-content:center;min-height:40px;padding:0 16px;border-radius:13px;background:var(--acid);color:var(--pine-950);font-size:13px;font-weight:800;white-space:nowrap}.menu-btn{display:none;place-items:center;width:40px;height:40px;border:0;border-radius:13px;background:rgba(255,255,255,.07);color:#fff}
    .topo{background-image:radial-gradient(circle at 12% 16%,rgba(223,252,98,.15),transparent 22%),radial-gradient(circle at 88% 18%,rgba(242,123,74,.14),transparent 18%),url("data:image/svg+xml,%3Csvg width='760' height='760' viewBox='0 0 760 760' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' stroke='%23fff' stroke-opacity='.052' stroke-width='1.05'%3E%3Cpath d='M74 206c43-106 166-167 278-119 89 39 107 147 52 218-51 66-143 59-194 124-58 73-49 188-142 228-91 38-186-37-164-132 20-89 111-106 122-190 8-57-5-88 48-129Z'/%3E%3Cpath d='M112 231c34-81 128-126 214-90 69 29 82 113 41 167-39 50-110 45-150 95-44 55-38 144-109 174-70 29-143-29-126-102 15-68 85-81 94-146 6-43-4-67 36-98Z'/%3E%3Cpath d='M493 410c57-79 161-89 227-18 60 64 24 169-55 198-71 26-142-17-201 28-52 40-62 123-129 129-74 6-126-73-84-135 38-56 112-39 155-92 35-43 39-79 87-110Z'/%3E%3C/g%3E%3C/svg%3E");background-size:auto,auto,760px 760px}.paper-grid{background-image:linear-gradient(rgba(9,37,29,.045) 1px,transparent 1px),linear-gradient(90deg,rgba(9,37,29,.045) 1px,transparent 1px);background-size:30px 30px}
    .hero{position:relative;overflow:hidden;min-height:590px;margin-top:14px;border-radius:38px;background:var(--pine-900);color:#fff;box-shadow:var(--shadow)}.hero-inner{position:relative;z-index:4;display:grid;grid-template-columns:minmax(0,1fr) minmax(420px,.82fr);gap:56px;align-items:center;min-height:590px;padding:70px}.hero:before{content:"";position:absolute;inset:0;background:linear-gradient(90deg,rgba(9,37,29,.98) 0%,rgba(9,37,29,.86) 45%,rgba(9,37,29,.24)),url("https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=1800&q=86") center/cover;opacity:.92}.hero:after{content:"";position:absolute;right:-130px;bottom:-210px;width:560px;height:560px;border:1px solid rgba(223,252,98,.12);border-radius:50%;box-shadow:0 0 0 58px rgba(223,252,98,.028),0 0 0 116px rgba(223,252,98,.016)}
    .success-badge{display:inline-flex;align-items:center;gap:9px;width:max-content;padding:8px 12px;border:1px solid rgba(223,252,98,.24);border-radius:999px;background:rgba(223,252,98,.1);color:var(--acid);font-size:10px;font-weight:800;letter-spacing:.15em;text-transform:uppercase}.success-dot{position:relative;width:9px;height:9px;border-radius:50%;background:var(--acid)}.success-dot:after{content:"";position:absolute;inset:-6px;border:1px solid rgba(223,252,98,.38);border-radius:50%;animation:pulse 2.2s ease-out infinite}@keyframes pulse{0%{transform:scale(.55);opacity:0}25%{opacity:1}100%{transform:scale(1.4);opacity:0}}
    .hero h1{max-width:720px;margin:22px 0 18px;font-family:"Fraunces",serif;font-size:clamp(50px,5.7vw,84px);font-weight:600;letter-spacing:-.064em;line-height:.92}.hero h1 em{color:var(--acid);font-style:italic}.lead{max-width:650px;margin:0;color:rgba(255,255,255,.68);font-size:16px;line-height:1.75}.order-strip{display:flex;flex-wrap:wrap;gap:10px;margin-top:30px}.order-chip{display:flex;align-items:center;gap:9px;padding:11px 13px;border:1px solid rgba(255,255,255,.12);border-radius:14px;background:rgba(255,255,255,.06);color:rgba(255,255,255,.67);font-size:11px}.order-chip strong{color:#fff;font-size:12px}.hero-actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:28px}
    .btn{display:inline-flex;align-items:center;justify-content:center;gap:9px;min-height:48px;padding:0 18px;border:1px solid transparent;border-radius:15px;font-size:13px;font-weight:800;transition:.22s ease}.btn:hover{transform:translateY(-2px)}.btn-primary{background:var(--acid);color:var(--pine-950)}.btn-primary:hover{box-shadow:0 18px 46px -24px rgba(223,252,98,.65)}.btn-ghost{border-color:rgba(255,255,255,.18);background:rgba(255,255,255,.06);color:#fff}.btn-soft{border-color:var(--line);background:var(--cream);color:var(--pine-900)}.btn-dark{background:var(--pine-900);color:#fff}.btn-ember{background:var(--ember);color:#fff}.btn-block{width:100%}
    .gift-stage{position:relative;display:grid;place-items:center;width:100%;min-width:0;perspective:1200px}.gift-card{position:relative;overflow:hidden;width:min(500px,100%);aspect-ratio:1.56;border-radius:31px;background:linear-gradient(145deg,#183f33,#09231c 74%);box-shadow:0 44px 105px -42px rgba(0,0,0,.9);transform:rotate(3deg);animation:float 5.2s ease-in-out infinite}.gift-card:before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 78% 18%,rgba(223,252,98,.22),transparent 24%),radial-gradient(circle at 18% 82%,rgba(242,123,74,.16),transparent 23%),url("data:image/svg+xml,%3Csvg width='560' height='360' viewBox='0 0 560 360' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' stroke='%23fff' stroke-opacity='.08'%3E%3Cpath d='M-20 230c86-110 189-115 261-31 68 79 132 73 210 4 70-61 128-48 170 4'/%3E%3Cpath d='M-28 263c93-109 200-108 276-25 70 76 137 67 213-1 67-59 126-47 165-9'/%3E%3Cpath d='M-35 297c103-108 211-98 289-19 73 72 141 59 215-6 64-57 122-47 160-18'/%3E%3C/g%3E%3C/svg%3E") center/cover}.gift-inner{position:absolute;inset:0;display:flex;flex-direction:column;justify-content:space-between;padding:31px;color:#fff}.gift-brand{display:flex;align-items:center;justify-content:space-between;gap:18px}.gift-brand strong{font-family:"Fraunces",serif;font-size:21px;font-weight:600}.gift-brand span{font-size:9px;font-weight:800;letter-spacing:.16em;text-transform:uppercase;color:rgba(255,255,255,.5)}.gift-to small{display:block;margin-bottom:8px;color:var(--acid);font-size:9px;font-weight:800;letter-spacing:.17em;text-transform:uppercase}.gift-to h2{margin:0;font-family:"Fraunces",serif;font-size:clamp(30px,3.3vw,45px);font-weight:600;letter-spacing:-.045em;line-height:1}.gift-message{max-width:340px;color:rgba(255,255,255,.7);font-size:12px;line-height:1.55}.gift-bottom{display:flex;align-items:flex-end;justify-content:space-between;gap:18px}.gift-value small{display:block;color:rgba(255,255,255,.45);font-size:9px;font-weight:800;letter-spacing:.15em;text-transform:uppercase}.gift-value strong{display:block;margin-top:4px;font-family:"Fraunces",serif;font-size:28px;font-weight:600}.gift-code{padding:9px 11px;border:1px solid rgba(223,252,98,.24);border-radius:11px;background:rgba(223,252,98,.08);color:var(--acid);font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:10px;font-weight:700;letter-spacing:.11em}.gift-shadow{position:absolute;right:7%;bottom:-34px;width:74%;height:55px;border-radius:50%;background:rgba(0,0,0,.45);filter:blur(28px);opacity:.72}@keyframes float{0%,100%{transform:rotate(3deg) translateY(0)}50%{transform:rotate(1.8deg) translateY(-8px)}}
    .section{padding:76px 0}.section-tight{padding:54px 0}.section-head{display:flex;align-items:end;justify-content:space-between;gap:28px;margin-bottom:30px}.section-head h2{max-width:760px;margin:0;font-family:"Fraunces",serif;font-size:clamp(36px,4.3vw,62px);font-weight:600;letter-spacing:-.055em;line-height:.98}.section-head h2 em{color:var(--pine-700);font-style:italic}.section-head p{max-width:520px;margin:0;color:var(--muted);line-height:1.7}.kicker{margin:0 0 10px;color:var(--pine-700);font-size:10px;font-weight:800;letter-spacing:.16em;text-transform:uppercase}
    .main-grid{display:grid;grid-template-columns:minmax(0,1.08fr) minmax(340px,.64fr);gap:26px;align-items:start}.panel{border:1px solid rgba(9,37,29,.1);border-radius:28px;background:rgba(255,253,246,.76);box-shadow:var(--card-shadow)}.panel-pad{padding:30px}.panel-title{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:24px}.panel-title h3{margin:0;font-family:"Fraunces",serif;font-size:28px;font-weight:600;letter-spacing:-.035em}.panel-title span{padding:7px 10px;border-radius:999px;background:rgba(27,82,66,.08);color:var(--pine-700);font-size:10px;font-weight:800;letter-spacing:.11em;text-transform:uppercase}
    .delivery-card{position:relative;overflow:hidden;padding:28px;border-radius:24px;background:var(--pine-900);color:#fff}.delivery-card:before{content:"";position:absolute;right:-65px;top:-80px;width:230px;height:230px;border:1px solid rgba(223,252,98,.12);border-radius:50%;box-shadow:0 0 0 35px rgba(223,252,98,.026)}.delivery-status{position:relative;z-index:2;display:flex;align-items:flex-start;gap:15px}.status-icon{display:grid;place-items:center;width:44px;height:44px;flex:0 0 auto;border-radius:15px;background:rgba(223,252,98,.12);color:var(--acid)}.delivery-status strong{display:block;font-family:"Fraunces",serif;font-size:24px;font-weight:600;letter-spacing:-.03em}.delivery-status p{margin:7px 0 0;color:rgba(255,255,255,.6);font-size:13px;line-height:1.6}.delivery-meta{position:relative;z-index:2;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-top:24px}.meta-box{padding:15px;border:1px solid rgba(255,255,255,.1);border-radius:16px;background:rgba(255,255,255,.05)}.meta-box span{display:block;color:rgba(255,255,255,.45);font-size:9px;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.meta-box strong{display:block;margin-top:6px;font-size:12px}.delivery-actions{position:relative;z-index:2;display:flex;flex-wrap:wrap;gap:10px;margin-top:22px}
    .detail-list{display:grid;gap:0}.detail-row{display:grid;grid-template-columns:150px minmax(0,1fr);gap:20px;padding:17px 0;border-bottom:1px solid var(--line)}.detail-row:last-child{border-bottom:0}.detail-row span{color:var(--muted);font-size:12px}.detail-row strong{font-size:13px;line-height:1.55}.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.06em}.code-row{display:flex;align-items:center;justify-content:space-between;gap:12px}.icon-btn{display:grid;place-items:center;width:38px;height:38px;flex:0 0 auto;border:1px solid var(--line);border-radius:12px;background:rgba(255,255,255,.55);color:var(--pine-800)}
    .action-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.action-card{display:flex;align-items:center;gap:13px;min-height:83px;padding:16px;border:1px solid var(--line);border-radius:18px;background:rgba(255,255,255,.55);text-align:left;transition:.2s ease}.action-card:hover{transform:translateY(-2px);border-color:rgba(27,82,66,.28);box-shadow:0 18px 35px -28px rgba(6,26,21,.6)}.action-icon{display:grid;place-items:center;width:42px;height:42px;flex:0 0 auto;border-radius:14px;background:rgba(27,82,66,.08);color:var(--pine-700)}.action-card strong{display:block;font-size:12px}.action-card span{display:block;margin-top:4px;color:var(--muted);font-size:10px;line-height:1.4}
    .order-summary{position:sticky;top:96px}.summary-card{padding:26px;border-radius:28px;background:var(--pine-900);color:#fff;box-shadow:var(--shadow)}.summary-card h3{margin:0 0 20px;font-family:"Fraunces",serif;font-size:28px;font-weight:600;letter-spacing:-.035em}.summary-lines{display:grid;gap:12px;padding-bottom:18px;border-bottom:1px solid rgba(255,255,255,.11)}.summary-line{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;color:rgba(255,255,255,.56);font-size:11px}.summary-line strong{color:#fff;text-align:right;font-size:11px}.summary-total{display:flex;align-items:end;justify-content:space-between;gap:18px;padding:20px 0}.summary-total span{color:rgba(255,255,255,.55);font-size:11px}.summary-total strong{font-family:"Fraunces",serif;font-size:35px;font-weight:600}.summary-note{display:flex;gap:10px;margin-top:16px;color:rgba(255,255,255,.48);font-size:10px;line-height:1.55}.summary-note svg{width:18px;height:18px;flex:0 0 auto;color:var(--acid)}
    .timeline{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:0;margin-top:28px}.timeline-step{position:relative;padding:0 18px 0 0}.timeline-step:not(:last-child):after{content:"";position:absolute;left:34px;right:0;top:15px;height:1px;background:rgba(9,37,29,.14)}.timeline-dot{position:relative;z-index:2;display:grid;place-items:center;width:31px;height:31px;margin-bottom:12px;border-radius:50%;background:var(--pine-900);color:var(--acid);box-shadow:0 0 0 7px var(--oat)}.timeline-step.future .timeline-dot{background:#d6d4c7;color:rgba(22,35,30,.55)}.timeline-step strong{display:block;font-size:12px}.timeline-step span{display:block;margin-top:5px;color:var(--muted);font-size:10px;line-height:1.45}
    .story-card{display:grid;grid-template-columns:minmax(0,.8fr) minmax(0,1.2fr);overflow:hidden;border-radius:32px;background:var(--pine-900);color:#fff;box-shadow:var(--shadow)}.story-media{min-height:390px;background:linear-gradient(90deg,rgba(9,37,29,.05),rgba(9,37,29,.25)),url("https://images.unsplash.com/photo-1473445361085-b9a07f55608b?auto=format&fit=crop&w=1300&q=84") center/cover}.story-copy{display:flex;flex-direction:column;justify-content:center;padding:48px}.story-copy small{color:var(--acid);font-size:10px;font-weight:800;letter-spacing:.15em;text-transform:uppercase}.story-copy h2{margin:14px 0 16px;font-family:"Fraunces",serif;font-size:clamp(36px,4vw,59px);font-weight:600;letter-spacing:-.055em;line-height:.98}.story-copy p{margin:0;color:rgba(255,255,255,.62);line-height:1.75}.story-actions{display:flex;flex-wrap:wrap;gap:11px;margin-top:24px}
    .footer{padding:30px 0 104px}.footer-card{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:26px;border-radius:27px;background:var(--pine-900);color:#fff}.footer-card p{margin:12px 0 0;color:rgba(255,255,255,.45);font-size:11px}.footer-links{display:flex;flex-wrap:wrap;gap:18px}.footer-links a{color:rgba(255,255,255,.62);font-size:11px}.footer-links a:hover{color:var(--acid)}
    .mobile-bar{display:none}.mobile-menu{position:fixed;z-index:110;inset:0;padding:16px;background:var(--pine-950);color:#fff;transform:translateY(-105%);transition:.32s cubic-bezier(.2,.8,.2,1)}.mobile-menu.open{transform:translateY(0)}.mobile-menu-head{display:flex;align-items:center;justify-content:space-between}.mobile-menu-links{display:grid;gap:6px;margin-top:36px}.mobile-menu-links a{padding:17px 0;border-bottom:1px solid rgba(255,255,255,.1);font-family:"Fraunces",serif;font-size:28px}
    .modal-backdrop{position:fixed;z-index:130;inset:0;display:grid;place-items:center;padding:18px;background:rgba(6,26,21,.72);backdrop-filter:blur(12px);opacity:0;pointer-events:none;transition:.24s ease}.modal-backdrop.open{opacity:1;pointer-events:auto}.modal{width:min(560px,100%);max-height:min(760px,calc(100vh - 36px));overflow:auto;border-radius:29px;background:var(--cream);box-shadow:0 40px 110px -40px rgba(0,0,0,.8);transform:translateY(16px) scale(.98);transition:.25s ease}.modal-backdrop.open .modal{transform:none}.modal-head{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;padding:26px;border-bottom:1px solid var(--line)}.modal-head h3{margin:0;font-family:"Fraunces",serif;font-size:28px;font-weight:600;letter-spacing:-.04em}.modal-head p{margin:6px 0 0;color:var(--muted);font-size:11px}.modal-close{display:grid;place-items:center;width:38px;height:38px;flex:0 0 auto;border:1px solid var(--line);border-radius:12px;background:#fff}.modal-body{padding:26px}.field{display:grid;gap:7px}.field+ .field{margin-top:15px}.field label{font-size:10px;font-weight:800;letter-spacing:.1em;text-transform:uppercase;color:var(--pine-700)}.field input,.field select,.field textarea{width:100%;min-height:48px;padding:12px 14px;border:1px solid var(--line);border-radius:14px;background:#fff;color:var(--ink);outline:none}.field textarea{min-height:105px;resize:vertical}.field input:focus,.field select:focus,.field textarea:focus{border-color:rgba(27,82,66,.5);box-shadow:0 0 0 4px rgba(27,82,66,.08)}.modal-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:22px}.toast{position:fixed;z-index:160;left:50%;bottom:24px;max-width:calc(100% - 32px);padding:13px 17px;border-radius:14px;background:var(--pine-950);color:#fff;font-size:12px;font-weight:700;box-shadow:0 18px 50px -28px rgba(0,0,0,.8);transform:translate(-50%,30px);opacity:0;pointer-events:none;transition:.25s ease}.toast.show{transform:translate(-50%,0);opacity:1}
    .confetti{position:absolute;inset:0;overflow:hidden;pointer-events:none}.confetti i{position:absolute;top:-15px;width:7px;height:15px;border-radius:3px;opacity:.75;animation:fall linear infinite}.confetti i:nth-child(1){left:8%;background:var(--acid);animation-duration:5.6s;animation-delay:-1s}.confetti i:nth-child(2){left:18%;background:var(--ember);animation-duration:7.2s;animation-delay:-4s}.confetti i:nth-child(3){left:30%;background:var(--sky);animation-duration:6.2s;animation-delay:-2s}.confetti i:nth-child(4){left:48%;background:var(--acid);animation-duration:7.8s;animation-delay:-6s}.confetti i:nth-child(5){left:62%;background:var(--ember);animation-duration:5.9s;animation-delay:-3s}.confetti i:nth-child(6){left:76%;background:var(--sky);animation-duration:6.8s;animation-delay:-5s}.confetti i:nth-child(7){left:91%;background:var(--acid);animation-duration:7.4s;animation-delay:-1.5s}@keyframes fall{to{transform:translateY(650px) rotate(520deg);opacity:0}}
    @media(max-width:1120px){.main-nav{display:none}.menu-btn{display:grid}.hero-inner{grid-template-columns:1fr 420px;padding:52px}.main-grid{grid-template-columns:1fr 330px}.hero h1{font-size:60px}}
    @media(max-width:900px){.hero-inner{grid-template-columns:1fr;gap:34px;padding:48px;min-height:auto}.hero{min-height:auto}.gift-stage{max-width:560px;margin-inline:auto}.main-grid{grid-template-columns:1fr}.order-summary{position:static}.story-card{grid-template-columns:1fr}.story-media{min-height:280px}.delivery-meta{grid-template-columns:1fr 1fr}.timeline{grid-template-columns:1fr 1fr;gap:24px}.timeline-step:nth-child(2):after{display:none}}
    @media(max-width:640px){.shell{width:min(100% - 20px,1460px)}.site-header{padding:8px 0}.nav{padding:8px 8px 8px 11px;border-radius:18px}.brand-mark{width:38px;height:38px;border-radius:13px}.brand-copy strong{font-size:16px}.brand-copy span{display:none}.ticket-cta{min-height:38px;padding:0 12px}.nav-actions{gap:6px}.hero{margin-top:8px;border-radius:25px}.hero-inner{padding:34px 22px 45px}.hero h1{font-size:44px;line-height:.95;margin-top:18px}.lead{font-size:14px}.hero-actions{display:grid;grid-template-columns:1fr}.btn{width:100%}.order-strip{display:grid;grid-template-columns:1fr 1fr}.order-chip{min-width:0;align-items:flex-start}.gift-card{border-radius:22px;transform:rotate(1.6deg);animation:none}.gift-inner{padding:20px}.gift-brand strong{font-size:17px}.gift-to h2{font-size:29px}.gift-message{font-size:10px;max-width:250px}.gift-value strong{font-size:22px}.gift-code{font-size:8px;padding:7px}.section{padding:54px 0}.section-tight{padding:38px 0}.section-head{display:block}.section-head h2{font-size:39px}.section-head p{margin-top:16px}.panel{border-radius:22px}.panel-pad{padding:21px}.panel-title{align-items:flex-start}.panel-title h3{font-size:24px}.delivery-card{padding:21px;border-radius:20px}.delivery-meta{grid-template-columns:1fr}.delivery-actions{display:grid}.detail-row{grid-template-columns:1fr;gap:7px;padding:14px 0}.action-grid{grid-template-columns:1fr}.timeline{grid-template-columns:1fr;gap:0}.timeline-step{display:grid;grid-template-columns:34px 1fr;column-gap:12px;padding:0 0 24px}.timeline-step:not(:last-child):after{left:15px;right:auto;top:30px;width:1px;height:calc(100% - 14px)}.timeline-step:nth-child(2):after{display:block}.timeline-dot{grid-row:1/3;margin:0}.timeline-step strong{padding-top:5px}.story-media{min-height:230px}.story-copy{padding:27px 22px}.story-copy h2{font-size:38px}.footer-card{display:block}.footer-links{margin-top:24px}.footer{padding-bottom:92px}.modal-backdrop{align-items:end;padding:0}.modal{width:100%;max-height:90vh;border-radius:25px 25px 0 0}.modal-actions{display:grid}.mobile-bar{position:fixed;z-index:85;left:10px;right:10px;bottom:10px;display:grid;grid-template-columns:1fr auto;align-items:center;gap:10px;padding:10px;border:1px solid rgba(255,255,255,.12);border-radius:18px;background:rgba(6,26,21,.94);color:#fff;box-shadow:0 20px 70px -36px rgba(0,0,0,.95);backdrop-filter:blur(18px)}.mobile-bar .btn{width:auto;min-height:42px;padding-inline:15px}.mobile-copy span{display:block;color:rgba(255,255,255,.5);font-size:9px;text-transform:uppercase;letter-spacing:.1em}.mobile-copy strong{display:block;margin-top:3px;font-size:11px}.toast{bottom:78px}}
    @media(max-width:390px){.order-strip{grid-template-columns:1fr}.hero h1{font-size:40px}.ticket-cta{padding:0 10px}.gift-message{display:none}.gift-inner{padding:17px}.gift-to h2{font-size:25px}.gift-bottom{gap:8px}.mobile-bar{grid-template-columns:minmax(0,1fr) auto}.mobile-bar .btn{font-size:11px;padding-inline:12px}}
    @media(prefers-reduced-motion:reduce){*,*:before,*:after{scroll-behavior:auto!important;animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important}.gift-card{transform:none}}
    @media print{.site-header,.hero-copy,.hero-actions,.order-strip,.section,.footer,.mobile-bar,.confetti{display:none!important}.hero{margin:0;border-radius:0;box-shadow:none;background:#fff}.hero:before,.hero:after{display:none}.hero-inner{display:block;min-height:auto;padding:40px}.gift-stage{max-width:760px;margin:0 auto}.gift-card{transform:none;box-shadow:none;border:1px solid #ddd}.gift-shadow{display:none}}
  </style>
</head>
<body>
<?php include __DIR__ . '/includes/header.php'; ?>
<main>
  <section class="shell hero topo">
    <div class="confetti" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div>
    <div class="hero-inner">
      <div class="hero-copy">
        <span class="success-badge"><i class="success-dot"></i>Voucher confirmat</span>
        <h1>Cadoul este gata să devină o <em>aventură.</em></h1>
        <p class="lead">Plata a fost confirmată, voucherul a fost generat, iar livrarea către <?= e($gcTo) ?> este programată pentru 18 august 2026, ora 08:00.</p>
        <div class="order-strip">
          <div class="order-chip"><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M5 4h14v16H5z"/><path d="M8 8h8M8 12h5"/></svg><span>Comandă <strong>#<?= e($gcOrder) ?></strong></span></div>
          <div class="order-chip"><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 6h16v12H4z"/><path d="m4 8 8 5 8-5"/></svg><span>Confirmare trimisă la <strong><?= e($gcFrom) ?></strong></span></div>
        </div>
        <div class="hero-actions"><button class="btn btn-primary" type="button" id="downloadVoucher"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><path d="M12 3v12m0 0 4-4m-4 4-4-4"/><path d="M5 20h14"/></svg>Descarcă voucherul</button><button class="btn btn-ghost" type="button" id="shareOpen"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9"><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8.6 10.6 6.8-4.1M8.6 13.4l6.8 4.1"/></svg>Trimite personal</button></div>
      </div>
      <div class="gift-stage" aria-label="Previzualizare voucher cadou">
        <div class="gift-card" id="giftCard">
          <div class="gift-inner">
            <div class="gift-brand"><strong>Nordvale</strong><span>Wild Park & Forest Reserve</span></div>
            <div class="gift-to"><small>Pentru</small><h2><?= e($gcTo) ?></h2><p class="gift-message"><?= e($gcMsg) ?></p></div>
            <div class="gift-bottom"><div class="gift-value"><small>Voucher valoric</small><strong><?= e($gcAmountFmt) ?></strong></div><div class="gift-code"><?= e($gcCode) ?></div></div>
          </div>
        </div>
        <div class="gift-shadow"></div>
      </div>
    </div>
  </section>

  <section class="section-tight">
    <div class="shell main-grid">
      <div>
        <article class="panel panel-pad">
          <div class="panel-title"><h3>Livrarea cadoului</h3><span id="deliveryBadge">Programată</span></div>
          <div class="delivery-card">
            <div class="delivery-status"><span class="status-icon"><svg width="23" height="23" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 6h16v12H4z"/><path d="m4 8 8 5 8-5"/></svg></span><div><strong id="deliveryTitle">Email programat pentru 18 august</strong><p id="deliveryCopy">Voucherul va ajunge la <?= e($gcEmail) ?> la ora 08:00. Până atunci poți modifica momentul livrării sau îl poți trimite personal.</p></div></div>
            <div class="delivery-meta"><div class="meta-box"><span>Destinatar</span><strong><?= e($gcToFull) ?></strong></div><div class="meta-box"><span>Email</span><strong id="recipientEmailLabel"><?= e($gcEmail) ?></strong></div><div class="meta-box"><span>Livrare</span><strong id="deliveryDateLabel">18 aug. 2026 · 08:00</strong></div></div>
            <div class="delivery-actions"><button class="btn btn-primary" type="button" id="editDeliveryOpen">Modifică livrarea</button><button class="btn btn-ghost" type="button" id="sendNow">Trimite acum</button></div>
          </div>
        </article>

        <article class="panel panel-pad" style="margin-top:24px">
          <div class="panel-title"><h3>Voucherul emis</h3><span>Valabil 12 luni</span></div>
          <div class="detail-list">
            <div class="detail-row"><span>Tip</span><strong>Voucher valoric Nordvale</strong></div>
            <div class="detail-row"><span>Valoare</span><strong><?= e($gcAmountFmt) ?></strong></div>
            <div class="detail-row"><span>Cod unic</span><div class="code-row"><strong class="mono" id="voucherCode"><?= e($gcCode) ?></strong><button class="icon-btn" type="button" id="copyCode" aria-label="Copiază codul"><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="8" y="8" width="11" height="11" rx="2"/><path d="M16 8V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h3"/></svg></button></div></div>
            <div class="detail-row"><span>Valabilitate</span><strong>29 iulie 2026 — 29 iulie 2027</strong></div>
            <div class="detail-row"><span>Poate fi folosit pentru</span><strong>Bilete, experiențe, pachete și abonamente eligibile</strong></div>
            <div class="detail-row"><span>Mesaj</span><strong>„<?= e($gcMsg) ?>”</strong></div>
          </div>
        </article>

        <article class="panel panel-pad" style="margin-top:24px">
          <div class="panel-title"><h3>Acțiuni rapide</h3><span>Gestionare</span></div>
          <div class="action-grid">
            <button class="action-card" type="button" id="printVoucher"><span class="action-icon"><svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M6 9V3h12v6M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"/><path d="M6 14h12v7H6z"/></svg></span><span><strong>Tipărește voucherul</strong><span>Versiune curată, gata de oferit.</span></span></button>
            <button class="action-card" type="button" id="shareOpen2"><span class="action-icon"><svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8.6 10.6 6.8-4.1M8.6 13.4l6.8 4.1"/></svg></span><span><strong>Distribuie cadoul</strong><span>Trimite-l tu prin email sau mesaj.</span></span></button>
            <button class="action-card" type="button" id="downloadReceipt"><span class="action-icon"><svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M6 3h12v18l-3-2-3 2-3-2-3 2z"/><path d="M9 8h6M9 12h6"/></svg></span><span><strong>Descarcă confirmarea</strong><span>Rezumatul comenzii și al plății.</span></span></button>
            <a class="action-card" href="/cont/comenzi"><span class="action-icon"><svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M5 4h14v16H5z"/><path d="M8 8h8M8 12h5M8 16h4"/></svg></span><span><strong>Vezi în cont</strong><span>Comandă, factură și statusul livrării.</span></span></a>
          </div>
        </article>
      </div>

      <aside class="order-summary">
        <div class="summary-card">
          <h3>Comanda ta</h3>
          <div class="summary-lines"><div class="summary-line"><span>Voucher valoric</span><strong><?= e($gcAmountFmt) ?></strong></div><div class="summary-line"><span>Cantitate</span><strong>1</strong></div><div class="summary-line"><span>Livrare digitală</span><strong>Inclusă</strong></div><div class="summary-line"><span>Plată</span><strong>Card •••• 4242</strong></div><div class="summary-line"><span>Factura</span><strong>NVF-2041</strong></div></div>
          <div class="summary-total"><span>Total plătit</span><strong><?= e($gcAmountFmt) ?></strong></div>
          <button class="btn btn-primary btn-block" type="button" id="invoiceDownload">Descarcă factura</button>
          <a class="btn btn-ghost btn-block" style="margin-top:10px" href="/card-cadou">Cumpără alt voucher</a>
          <div class="summary-note"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 3 4 6v6c0 5 3.5 8 8 9 4.5-1 8-4 8-9V6z"/><path d="m9 12 2 2 4-5"/></svg><span>Codul devine activ imediat. Livrarea programată nu afectează valabilitatea voucherului.</span></div>
        </div>
      </aside>
    </div>
  </section>

  <section class="section paper-grid">
    <div class="shell">
      <div class="section-head"><div><p class="kicker">Ce urmează</p><h2>De la confirmare la prima <em>aventură.</em></h2></div><p>Tu ai încheiat cumpărarea. De aici, destinatarul își poate transforma voucherul într-o zi completă în Nordvale.</p></div>
      <div class="timeline">
        <div class="timeline-step"><span class="timeline-dot"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m5 12 4 4L19 6"/></svg></span><strong>Voucher generat</strong><span>29 iulie 2026 · 17:40</span></div>
        <div class="timeline-step"><span class="timeline-dot"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 6h16v12H4z"/><path d="m4 8 8 5 8-5"/></svg></span><strong>Confirmare cumpărător</strong><span>Trimisă la <?= e($gcFrom) ?></span></div>
        <div class="timeline-step future" id="timelineDelivery"><span class="timeline-dot"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 7v5l3 2"/><circle cx="12" cy="12" r="9"/></svg></span><strong>Livrare către <?= e($gcTo) ?></strong><span id="timelineDeliveryCopy">18 august 2026 · 08:00</span></div>
        <div class="timeline-step future"><span class="timeline-dot"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m4 17 5-10 3 6 2-4 6 8"/><path d="M3 20h18"/></svg></span><strong>Rezervarea aventurii</strong><span>Destinatarul alege experiența și data</span></div>
      </div>
    </div>
  </section>

  <section class="section">
    <div class="shell story-card">
      <div class="story-media"></div>
      <div class="story-copy"><small>Mai mult decât un cod</small><h2>Cadoul continuă când <?= e($gcTo) ?> își alege traseul.</h2><p>Din email, destinatarul poate verifica soldul, poate combina voucherul cu o plată online și poate rezerva orice experiență eligibilă, în limita locurilor disponibile.</p><div class="story-actions"><a class="btn btn-primary" href="/voucher">Vezi cum se folosește</a><a class="btn btn-ghost" href="/experiente">Explorează experiențele</a></div></div>
    </div>
  </section>
</main>
<?php include __DIR__ . '/includes/footer.php'; ?>

<div class="mobile-bar"><div class="mobile-copy"><span>Voucher pregătit</span><strong id="mobileDeliveryText">Livrare 18 aug. · 08:00</strong></div><button class="btn btn-primary" type="button" id="mobileDownload">Descarcă</button></div>

<div class="modal-backdrop" id="shareModal" aria-hidden="true"><div class="modal" role="dialog" aria-modal="true" aria-labelledby="shareTitle"><div class="modal-head"><div><h3 id="shareTitle">Trimite voucherul personal</h3><p>Această acțiune nu modifică livrarea programată decât dacă alegi explicit să o anulezi.</p></div><button class="modal-close" type="button" data-close-modal aria-label="Închide"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m6 6 12 12M18 6 6 18"/></svg></button></div><form class="modal-body" id="shareForm"><div class="field"><label for="shareEmail">Email</label><input id="shareEmail" type="email" value="<?= e($gcEmail) ?>" required></div><div class="field"><label for="shareMessage">Mesaj opțional</label><textarea id="shareMessage">Ți-am pregătit o aventură Nordvale. Voucherul este atașat și îl poți folosi când îți alegi ziua potrivită.</textarea></div><label style="display:flex;align-items:flex-start;gap:10px;margin-top:16px;color:var(--muted);font-size:11px"><input type="checkbox" id="cancelScheduled" style="margin-top:2px"> Anulează livrarea programată dacă trimit voucherul acum.</label><div class="modal-actions"><button class="btn btn-soft" type="button" data-close-modal>Renunță</button><button class="btn btn-dark" type="submit">Trimite voucherul</button></div></form></div></div>

<div class="modal-backdrop" id="deliveryModal" aria-hidden="true"><div class="modal" role="dialog" aria-modal="true" aria-labelledby="deliveryModalTitle"><div class="modal-head"><div><h3 id="deliveryModalTitle">Modifică livrarea</h3><p>Poți schimba data, ora și adresa până la procesarea emailului.</p></div><button class="modal-close" type="button" data-close-modal aria-label="Închide"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m6 6 12 12M18 6 6 18"/></svg></button></div><form class="modal-body" id="deliveryForm"><div class="field"><label for="deliveryEmail">Email destinatar</label><input id="deliveryEmail" type="email" value="<?= e($gcEmail) ?>" required></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:12px"><div class="field"><label for="deliveryDate">Data</label><input id="deliveryDate" type="date" value="2026-08-18" min="2026-07-29" required></div><div class="field"><label for="deliveryTime">Ora</label><input id="deliveryTime" type="time" value="08:00" required></div></div><div class="modal-actions"><button class="btn btn-soft" type="button" data-close-modal>Renunță</button><button class="btn btn-dark" type="submit">Salvează livrarea</button></div></form></div></div>
<div class="toast" id="toast" role="status" aria-live="polite"></div>
<script>
(() => {
  'use strict';
  const $ = (s, root=document) => root.querySelector(s);
  const $$ = (s, root=document) => [...root.querySelectorAll(s)];
  const state = { scheduled: true, email:'<?= e($gcEmail) ?>', date:'2026-08-18', time:'08:00' };
  let toastTimer;
  function toast(message){ const el=$('#toast'); if(!el)return; el.textContent=message; el.classList.add('show'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>el.classList.remove('show'),2600); }
  function openModal(id){ const el=$(id); if(!el)return; el.classList.add('open'); el.setAttribute('aria-hidden','false'); document.body.style.overflow='hidden'; setTimeout(()=>el.querySelector('input,button,textarea,select')?.focus(),50); }
  function closeModal(el){ if(!el)return; el.classList.remove('open'); el.setAttribute('aria-hidden','true'); document.body.style.overflow=''; }
  function formatDate(value){ const d=new Date(value+'T12:00:00'); return new Intl.DateTimeFormat('ro-RO',{day:'numeric',month:'short',year:'numeric'}).format(d); }
  function updateDeliveryUI(){
    const title=$('#deliveryTitle'), copy=$('#deliveryCopy'), badge=$('#deliveryBadge'), dateLabel=$('#deliveryDateLabel'), emailLabel=$('#recipientEmailLabel'), timeline=$('#timelineDeliveryCopy'), mobile=$('#mobileDeliveryText'), step=$('#timelineDelivery');
    if(state.scheduled){
      title.textContent='Email programat pentru '+formatDate(state.date).replace('2026','').trim();
      copy.textContent=`Voucherul va ajunge la ${state.email} la ora ${state.time}. Până atunci poți modifica momentul livrării sau îl poți trimite personal.`;
      badge.textContent='Programată'; dateLabel.textContent=`${formatDate(state.date)} · ${state.time}`; timeline.textContent=`${formatDate(state.date)} · ${state.time}`; mobile.textContent=`Livrare ${formatDate(state.date).replace('2026','').trim()} · ${state.time}`; step.classList.add('future');
    } else {
      title.textContent='Voucher trimis către <?= e($gcTo) ?>'; copy.textContent=`Emailul a fost trimis la ${state.email}. Poți retrimite voucherul sau îl poți distribui printr-un alt canal.`;
      badge.textContent='Trimis'; dateLabel.textContent='Trimis acum'; timeline.textContent='Trimis către '+state.email; mobile.textContent='Voucher trimis'; step.classList.remove('future');
    }
    emailLabel.textContent=state.email;
  }
  function downloadFile(name, content, type='text/plain'){ const blob=new Blob([content],{type}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=name; document.body.appendChild(a); a.click(); a.remove(); setTimeout(()=>URL.revokeObjectURL(url),500); }
  function downloadVoucher(){
    const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1400" height="900" viewBox="0 0 1400 900"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#173e32"/><stop offset="1" stop-color="#09231c"/></linearGradient></defs><rect width="1400" height="900" rx="60" fill="url(#g)"/><circle cx="1180" cy="160" r="250" fill="#dffc62" opacity=".12"/><circle cx="190" cy="760" r="210" fill="#f27b4a" opacity=".12"/><text x="85" y="105" fill="#fff" font-family="Georgia" font-size="50">Nordvale</text><text x="85" y="320" fill="#dffc62" font-family="Arial" font-weight="700" font-size="25" letter-spacing="5">PENTRU</text><text x="85" y="440" fill="#fff" font-family="Georgia" font-size="110"><?= e($gcTo) ?></text><text x="85" y="535" fill="#fff" opacity=".72" font-family="Arial" font-size="28">Pentru o zi cu aer curat, curaj și libertate.</text><text x="85" y="720" fill="#fff" opacity=".55" font-family="Arial" font-size="23" letter-spacing="3">VOUCHER VALORIC</text><text x="85" y="805" fill="#fff" font-family="Georgia" font-size="72"><?= e($gcAmountFmt) ?></text><rect x="990" y="740" width="320" height="70" rx="20" fill="#dffc62" opacity=".12" stroke="#dffc62" stroke-opacity=".35"/><text x="1030" y="786" fill="#dffc62" font-family="monospace" font-size="30" letter-spacing="4"><?= e($gcCode) ?></text></svg>`;
    downloadFile('voucher-nordvale-mara.svg',svg,'image/svg+xml'); toast('Voucherul a fost descărcat.');
  }
  $('#menuOpen')?.addEventListener('click',()=>$('#mobileMenu')?.classList.add('open'));
  $('#menuClose')?.addEventListener('click',()=>$('#mobileMenu')?.classList.remove('open'));
  ['#shareOpen','#shareOpen2'].forEach(id=>$(id)?.addEventListener('click',()=>openModal('#shareModal')));
  $('#editDeliveryOpen')?.addEventListener('click',()=>openModal('#deliveryModal'));
  $$('[data-close-modal]').forEach(btn=>btn.addEventListener('click',()=>closeModal(btn.closest('.modal-backdrop'))));
  $$('.modal-backdrop').forEach(backdrop=>backdrop.addEventListener('click',e=>{if(e.target===backdrop)closeModal(backdrop)}));
  document.addEventListener('keydown',e=>{if(e.key==='Escape')$$('.modal-backdrop.open').forEach(closeModal)});
  $('#copyCode')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#voucherCode').textContent.trim());toast('Codul voucherului a fost copiat.')}catch{toast('Selectează și copiază manual codul.')}});
  ['#downloadVoucher','#mobileDownload'].forEach(id=>$(id)?.addEventListener('click',downloadVoucher));
  $('#printVoucher')?.addEventListener('click',()=>window.print());
  $('#downloadReceipt')?.addEventListener('click',()=>{downloadFile('confirmare-comanda-<?= e($gcOrder) ?>.txt','NORDVALE\nComanda #<?= e($gcOrder) ?>\nVoucher valoric: <?= e($gcAmountFmt) ?>\nDestinatar: <?= e($gcToFull) ?>\nCod: <?= e($gcCode) ?>\nTotal plătit: <?= e($gcAmountFmt) ?>\n');toast('Confirmarea a fost descărcată.')} );
  $('#invoiceDownload')?.addEventListener('click',()=>{downloadFile('factura-NVF-2041.txt','FACTURĂ DEMO NVF-2041\nVoucher cadou Nordvale: <?= e($gcAmountFmt) ?>\nTotal: <?= e($gcAmountFmt) ?>\nPlată: card •••• 4242\n');toast('Factura demonstrativă a fost descărcată.')} );
  $('#sendNow')?.addEventListener('click',()=>{state.scheduled=false;updateDeliveryUI();toast('Voucherul a fost trimis acum către <?= e($gcTo) ?>.');});
  $('#deliveryForm')?.addEventListener('submit',e=>{e.preventDefault();const email=$('#deliveryEmail').value.trim(),date=$('#deliveryDate').value,time=$('#deliveryTime').value;if(!email||!date||!time){toast('Completează toate datele de livrare.');return}state.email=email;state.date=date;state.time=time;state.scheduled=true;updateDeliveryUI();closeModal($('#deliveryModal'));toast('Livrarea programată a fost actualizată.');});
  $('#shareForm')?.addEventListener('submit',e=>{e.preventDefault();const email=$('#shareEmail').value.trim();if(!email){toast('Completează adresa de email.');return}if($('#cancelScheduled').checked){state.email=email;state.scheduled=false;updateDeliveryUI()}closeModal($('#shareModal'));toast('Voucherul a fost trimis către '+email+'.');});
  updateDeliveryUI();
})();
</script>
</body>
</html>
