<?php

namespace App\Filament\Organizer\Resources;

use App\Models\Marketplace\MarketplacePayout;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Filament\Infolists;
use Filament\Infolists\Infolist;
use Illuminate\Database\Eloquent\Builder;

class PayoutResource extends Resource
{
    protected static ?string $model = MarketplacePayout::class;

    protected static ?string $navigationIcon = 'heroicon-o-banknotes';
    protected static ?string $navigationGroup = 'Finance';
    protected static ?string $navigationLabel = 'Payouts';
    protected static ?int $navigationSort = 1;
    protected static ?string $modelLabel = 'Payout';
    protected static ?string $pluralModelLabel = 'Payouts';

    public static function getEloquentQuery(): Builder
    {
        $organizer = auth('organizer')->user()?->organizer;

        return parent::getEloquentQuery()
            ->where('organizer_id', $organizer?->id);
    }

    public static function canCreate(): bool
    {
        return false; // Payouts are generated by the marketplace
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                // Read-only form
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('reference')
                    ->label('Reference')
                    ->searchable()
                    ->sortable()
                    ->copyable(),

                Tables\Columns\TextColumn::make('status')
                    ->badge()
                    ->color(fn (string $state): string => match ($state) {
                        'completed' => 'success',
                        'processing' => 'warning',
                        'pending' => 'gray',
                        'failed' => 'danger',
                        default => 'gray',
                    }),

                Tables\Columns\TextColumn::make('period_start')
                    ->label('Period')
                    ->date()
                    ->description(fn (MarketplacePayout $record) => 'to ' . $record->period_end?->format('M j, Y')),

                Tables\Columns\TextColumn::make('orders_count')
                    ->label('Orders')
                    ->counts('orders')
                    ->sortable(),

                Tables\Columns\TextColumn::make('total_amount')
                    ->label('Amount')
                    ->money('RON')
                    ->sortable()
                    ->color('success'),

                Tables\Columns\TextColumn::make('processed_at')
                    ->label('Processed')
                    ->dateTime()
                    ->sortable()
                    ->placeholder('Pending'),

                Tables\Columns\TextColumn::make('created_at')
                    ->label('Created')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                Tables\Filters\SelectFilter::make('status')
                    ->options([
                        'pending' => 'Pending',
                        'processing' => 'Processing',
                        'completed' => 'Completed',
                        'failed' => 'Failed',
                    ]),
            ])
            ->actions([
                Tables\Actions\ViewAction::make(),
            ])
            ->bulkActions([])
            ->defaultSort('created_at', 'desc');
    }

    public static function infolist(Infolist $infolist): Infolist
    {
        return $infolist
            ->schema([
                Infolists\Components\Section::make('Payout Information')
                    ->schema([
                        Infolists\Components\TextEntry::make('reference')
                            ->label('Reference')
                            ->copyable(),
                        Infolists\Components\TextEntry::make('status')
                            ->badge()
                            ->color(fn (string $state): string => match ($state) {
                                'completed' => 'success',
                                'processing' => 'warning',
                                'pending' => 'gray',
                                'failed' => 'danger',
                                default => 'gray',
                            }),
                        Infolists\Components\TextEntry::make('period_start')
                            ->label('Period Start')
                            ->date(),
                        Infolists\Components\TextEntry::make('period_end')
                            ->label('Period End')
                            ->date(),
                    ])->columns(4),

                Infolists\Components\Section::make('Amount Details')
                    ->schema([
                        Infolists\Components\TextEntry::make('total_amount')
                            ->label('Total Amount')
                            ->money('RON'),
                        Infolists\Components\TextEntry::make('orders_count')
                            ->label('Orders Included')
                            ->state(fn (MarketplacePayout $record) => $record->orders()->count()),
                        Infolists\Components\TextEntry::make('currency')
                            ->label('Currency'),
                    ])->columns(3),

                Infolists\Components\Section::make('Payment Details')
                    ->schema([
                        Infolists\Components\TextEntry::make('method')
                            ->label('Payment Method')
                            ->formatStateUsing(fn ($state) => match ($state) {
                                'bank_transfer' => 'Bank Transfer',
                                'paypal' => 'PayPal',
                                'stripe_connect' => 'Stripe Connect',
                                default => ucfirst($state ?? 'N/A'),
                            }),
                        Infolists\Components\TextEntry::make('bank_reference')
                            ->label('Bank Reference')
                            ->placeholder('Not yet processed'),
                        Infolists\Components\TextEntry::make('processed_at')
                            ->label('Processed Date')
                            ->dateTime()
                            ->placeholder('Pending'),
                    ])->columns(3),

                Infolists\Components\Section::make('Notes')
                    ->schema([
                        Infolists\Components\TextEntry::make('notes')
                            ->label('')
                            ->placeholder('No notes'),
                    ])
                    ->visible(fn (MarketplacePayout $record) => filled($record->notes)),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            PayoutResource\RelationManagers\OrdersRelationManager::class,
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => PayoutResource\Pages\ListPayouts::route('/'),
            'view' => PayoutResource\Pages\ViewPayout::route('/{record}'),
        ];
    }

    public static function getNavigationBadge(): ?string
    {
        $organizer = auth('organizer')->user()?->organizer;
        if (!$organizer) {
            return null;
        }

        $pending = static::getEloquentQuery()->pending()->count();
        return $pending > 0 ? (string) $pending : null;
    }

    public static function getNavigationBadgeColor(): ?string
    {
        return 'warning';
    }
}
