<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('marketplace_todo_comments', function (Blueprint $table) {
            $table->id();
            $table->foreignId('marketplace_client_id')
                ->constrained('marketplace_clients')
                ->cascadeOnDelete();
            $table->foreignId('marketplace_todo_id')
                ->constrained('marketplace_todos')
                ->cascadeOnDelete();

            // Author is always a marketplace_admin (only marketplace users
            // can create or comment on TODOs — not clients or organizers).
            $table->foreignId('author_marketplace_admin_id')
                ->constrained('marketplace_admins')
                ->cascadeOnDelete();

            $table->mediumText('body'); // WYSIWYG HTML
            $table->json('attachments')->nullable();

            // Internal events generated by status / assignee changes
            // (so the timeline records "who closed it" etc.). Plain user
            // comments leave this null.
            $table->string('event_type', 32)->nullable();

            $table->timestamps();

            $table->index(['marketplace_todo_id', 'created_at'], 'mp_todo_comment_thread_idx');
            $table->index(['author_marketplace_admin_id'], 'mp_todo_comment_author_idx');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('marketplace_todo_comments');
    }
};
