<?php
$navActive = 'subscriptions';
$pageTitle = 'Abonamentele mele — ' . (defined('SITE_NAME') ? SITE_NAME : 'Contul meu');
require __DIR__ . '/_inc/head.php';
require __DIR__ . '/_inc/top.php';
?>
<div class="mb-9"><p class="text-[11px] font-bold tracking-[.22em] text-brass-light">ABONAMENTE</p><h1 class="mt-3 font-display text-4xl leading-tight sm:text-5xl">Abonamentele mele</h1><p class="mt-3 max-w-3xl text-sm leading-7 text-paper/48 sm:text-base">Vezi intrările rămase, producțiile eligibile și rezervă locuri pentru reprezentațiile preferate.</p></div>
<div x-data="{reserve:false,history:false}"><section class="grain relative overflow-hidden rounded-3xl border border-brass/25 bg-gradient-to-br from-wine-dark via-panel to-coal p-6 sm:p-8"><div class="relative grid gap-7 lg:grid-cols-[1fr_.8fr] lg:items-end"><div><span class="badge bg-emerald-500/12 text-emerald-300">ABONAMENT ACTIV</span><h2 class="mt-4 font-display text-4xl">Plus · Stagiunea 2026–2027</h2><p class="mt-3 text-paper/50">8 intrări flexibile pentru producțiile eligibile. Valabil până la 30 iunie 2027.</p><div class="mt-6 flex flex-wrap gap-3"><button @click="reserve=true" class="btn-primary rounded-full px-5 py-3 text-sm font-bold">Rezervă o reprezentație</button><button @click="history=!history" class="btn-secondary rounded-full px-5 py-3 text-sm">Istoric utilizare</button></div></div><div class="rounded-2xl border border-white/10 bg-ink/40 p-5"><div class="flex items-end justify-between"><div><strong class="font-display text-5xl">5</strong><span class="ml-2 text-paper/40">intrări disponibile</span></div><span class="text-sm text-brass-light">62%</span></div><div class="mt-4 h-3 rounded-full bg-white/10"><div class="h-full w-[62%] rounded-full bg-brass"></div></div><div class="mt-4 grid grid-cols-2 gap-3 text-xs"><div class="rounded-xl bg-white/[.035] p-3"><span class="text-paper/35">Folosite</span><strong class="mt-1 block text-lg">3</strong></div><div class="rounded-xl bg-white/[.035] p-3"><span class="text-paper/35">Beneficiari</span><strong class="mt-1 block text-lg">2</strong></div></div></div></div></section>
<div x-show="history" x-collapse class="card mt-5 p-5"><h3 class="font-display text-xl">Istoric utilizare</h3><div class="mt-4 grid gap-3"><div class="flex items-center justify-between rounded-xl bg-white/[.025] p-4"><div><strong>A Jazzy Story</strong><p class="text-xs text-paper/35">28 iulie · 2 intrări</p></div><span class="badge bg-emerald-500/10 text-emerald-300">REZERVAT</span></div><div class="flex items-center justify-between rounded-xl bg-white/[.025] p-4"><div><strong>O idee genială</strong><p class="text-xs text-paper/35">20 aprilie · 1 intrare</p></div><span class="badge bg-white/5 text-paper/40">UTILIZAT</span></div></div></div>
<section class="mt-7"><div class="flex items-end justify-between"><div><h2 class="font-display text-3xl">Spectacole eligibile</h2><p class="mt-2 text-sm text-paper/40">Alege o dată și rezervă locurile fără o nouă plată.</p></div><a href="/abonamente" class="hidden text-sm text-brass-light sm:block">Condiții abonament</a></div><div class="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><article class="card card-hover p-5"><span class="badge bg-drama/15 text-rose-200">DRAMA</span><h3 class="mt-3 font-display text-2xl">TOMA</h3><p class="mt-2 text-xs text-paper/38">14 septembrie · 19:00 · locuri disponibile</p><button @click="reserve=true" class="mt-5 text-sm font-semibold text-brass-light">Rezervă →</button></article><article class="card card-hover p-5"><span class="badge bg-revue/15 text-amber-200">REVISTA</span><h3 class="mt-3 font-display text-2xl">Descurcă-lume</h3><p class="mt-2 text-xs text-paper/38">21 septembrie · 19:00 · ultimele locuri</p><button @click="reserve=true" class="mt-5 text-sm font-semibold text-brass-light">Rezervă →</button></article><article class="card card-hover p-5"><span class="badge bg-imaginario/15 text-teal-200">IMAGINARIO</span><h3 class="mt-3 font-display text-2xl">Cartea Junglei</h3><p class="mt-2 text-xs text-paper/38">5 octombrie · 11:00 · familie</p><button @click="reserve=true" class="mt-5 text-sm font-semibold text-brass-light">Rezervă →</button></article></div></section>
<section class="card mt-7 p-5 sm:p-6"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-display text-2xl">Nu mai ai suficiente intrări?</h2><p class="mt-2 text-sm text-paper/40">Poți suplimenta abonamentul sau cumpăra bilete separat.</p></div><a href="/abonamente" class="btn-secondary rounded-full px-5 py-3 text-sm">Vezi opțiunile</a></div></section>
<div x-cloak x-show="reserve" x-transition.opacity class="fixed inset-0 z-[90] grid place-items-center bg-ink/90 p-5" @click.self="reserve=false"><form @submit.prevent="reserve=false;showToast('Rezervarea a fost creată')" class="card w-full max-w-lg p-6"><div class="flex items-center justify-between"><h3 class="font-display text-2xl">Rezervă cu abonamentul</h3><button type="button" @click="reserve=false"><svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.7" d="m6 6 12 12M18 6 6 18"/></svg></button></div><label class="mt-5 block"><span class="label">Spectacol</span><select class="input"><option>TOMA</option><option>Descurcă-lume</option><option>Cartea Junglei</option></select></label><div class="mt-4 grid gap-4 sm:grid-cols-2"><label><span class="label">Reprezentație</span><select class="input"><option>14 septembrie · 19:00</option><option>28 septembrie · 19:00</option></select></label><label><span class="label">Număr intrări</span><select class="input"><option>1</option><option selected>2</option><option>3</option></select></label></div><label class="mt-4 block"><span class="label">Beneficiari</span><select class="input"><option>Andrei Popescu + Mara Popescu</option><option>Andrei Popescu</option></select></label><button class="btn-primary mt-5 w-full rounded-full px-5 py-3 font-bold">Continuă la alegerea locurilor</button></form></div></div>
<?php require __DIR__ . '/_inc/bottom.php'; ?>
