<?php
$navActive = 'orders';
$pageTitle = 'Comenzile mele — ' . (defined('SITE_NAME') ? SITE_NAME : 'Contul meu');
require __DIR__ . '/_inc/head.php';
require __DIR__ . '/_inc/top.php';
?>
<div class="mb-9"><p class="text-[11px] font-bold tracking-[.22em] text-brass-light">COMENZI</p><h1 class="mt-3 font-display text-4xl leading-tight sm:text-5xl">Comenzile mele</h1><p class="mt-3 max-w-3xl text-sm leading-7 text-paper/48 sm:text-base">Istoricul plăților, facturi, bilete emise și starea solicitărilor de rambursare.</p></div>
<div x-data="{status:'all',open:1}"><div class="grid grid-cols-3 gap-3"><div class="card p-5"><p class="font-display text-3xl text-brass-light">14</p><p class="mt-1 text-xs text-paper/38">Total comenzi</p></div><div class="card p-5"><p class="font-display text-3xl text-emerald-300">1.840 lei</p><p class="mt-1 text-xs text-paper/38">Total plătit</p></div><div class="card p-5"><p class="font-display text-3xl text-amber-300">270 lei</p><p class="mt-1 text-xs text-paper/38">Economisit</p></div></div><div class="mt-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div class="flex gap-2 overflow-x-auto"><template x-for="item in [['all','Toate'],['paid','Confirmate'],['pending','În așteptare'],['refunded','Rambursate']]" :key="item[0]"><button @click="status=item[0]" :class="status===item[0]?'bg-brass text-ink':'border-white/10 text-paper/45'" class="whitespace-nowrap rounded-full border px-4 py-2 text-sm" x-text="item[1]"></button></template></div><input class="input max-w-xs" placeholder="Caută după număr sau spectacol"></div>
<div class="mt-5 grid gap-4"><article class="card overflow-hidden"><button @click="open=open===1?0:1" class="flex w-full flex-col gap-4 p-5 text-left sm:flex-row sm:items-center"><div class="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-emerald-500/10 text-emerald-300"><svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.7" d="m5 12 4 4L19 6"/></svg></div><div class="flex-1"><div class="flex flex-wrap items-center gap-2"><strong>#TC-10482</strong><span class="badge bg-emerald-500/10 text-emerald-300">CONFIRMATĂ</span></div><p class="mt-1 text-xs text-paper/38">24 iulie 2026 · A Jazzy Story · 2 bilete</p></div><div class="sm:text-right"><strong class="block">120 lei</strong><span class="text-xs text-paper/35">Visa •••• 4532</span></div><span :class="open===1?'rotate-90':''" class="transition"><svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.7" d="m9 18 6-6-6-6"/></svg></span></button><div x-show="open===1" x-collapse class="border-t border-white/8 p-5"><div class="grid gap-4 md:grid-cols-[1fr_auto]"><div><p class="text-sm text-paper/50">Biletele au fost emise și sunt disponibile în cont.</p><div class="mt-3 flex flex-wrap gap-2"><span class="badge bg-white/5 text-paper/45">2 bilete</span><span class="badge bg-white/5 text-paper/45">Taxe incluse</span><span class="badge bg-white/5 text-paper/45">Factura disponibilă</span></div></div><div class="flex gap-2"><a href="/cont/comanda" class="btn-secondary rounded-full px-4 py-2.5 text-sm">Detalii</a><a href="/cont/bilete" class="btn-primary rounded-full px-4 py-2.5 text-sm font-bold">Bilete</a></div></div></div></article>
<article class="card overflow-hidden"><button @click="open=open===2?0:2" class="flex w-full flex-col gap-4 p-5 text-left sm:flex-row sm:items-center"><div class="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-amber-500/10 text-amber-300"><svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.7" d="M12 9v4m0 4h.01M10.3 3.7 2.6 18a2 2 0 0 0 1.8 3h15.2a2 2 0 0 0 1.8-3L13.7 3.7a2 2 0 0 0-3.4 0Z"/></svg></div><div class="flex-1"><div class="flex flex-wrap items-center gap-2"><strong>#TC-10396</strong><span class="badge bg-amber-500/10 text-amber-300">RAMBURSARE ÎN CURS</span></div><p class="mt-1 text-xs text-paper/38">10 iunie 2026 · TOMA · 2 bilete</p></div><div class="sm:text-right"><strong class="block">160 lei</strong><span class="text-xs text-paper/35">Card bancar</span></div><span :class="open===2?'rotate-90':''" class="transition"><svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.7" d="m9 18 6-6-6-6"/></svg></span></button><div x-show="open===2" x-collapse class="border-t border-white/8 p-5"><p class="text-sm text-paper/50">Cererea #RF-882 este în analiză. Vei primi răspuns prin email.</p><a href="/cont/rambursare" class="mt-3 inline-flex text-sm text-brass-light">Vezi cererea →</a></div></article>
<article class="card flex flex-col gap-4 p-5 opacity-70 sm:flex-row sm:items-center"><div class="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-white/5 text-paper/35"><svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.7" d="M5 8h14l1 12H4L5 8Zm4 0V6a3 3 0 0 1 6 0v2"/></svg></div><div class="flex-1"><div class="flex flex-wrap items-center gap-2"><strong>#TC-09840</strong><span class="badge bg-white/5 text-paper/40">FINALIZATĂ</span></div><p class="mt-1 text-xs text-paper/38">18 februarie 2026 · O idee genială · 2 bilete</p></div><strong>140 lei</strong><a href="/cont/comanda" class="text-sm text-brass-light">Detalii</a></article></div></div>
<?php require __DIR__ . '/_inc/bottom.php'; ?>
