<?php
$navActive = 'favorites';
$pageTitle = 'Favorite și alerte — ' . (defined('SITE_NAME') ? SITE_NAME : 'Contul meu');
require __DIR__ . '/_inc/head.php';
require __DIR__ . '/_inc/top.php';
?>
<div class="mb-9"><p class="text-[11px] font-bold tracking-[.22em] text-brass-light">FAVORITE</p><h1 class="mt-3 font-display text-4xl leading-tight sm:text-5xl">Favorite și alerte</h1><p class="mt-3 max-w-3xl text-sm leading-7 text-paper/48 sm:text-base">Urmărește spectacole, artiști și festivaluri și controlează exact tipul de notificări primit.</p></div>
<div x-data="{tab:'shows'}"><div class="flex gap-2 overflow-x-auto rounded-xl border border-white/8 bg-white/[.025] p-1"><button @click="tab='shows'" :class="tab==='shows'?'bg-brass text-ink':'text-paper/45'" class="rounded-lg px-4 py-2 text-sm font-semibold">Spectacole · 5</button><button @click="tab='artists'" :class="tab==='artists'?'bg-brass text-ink':'text-paper/45'" class="rounded-lg px-4 py-2 text-sm font-semibold">Artiști · 3</button><button @click="tab='festivals'" :class="tab==='festivals'?'bg-brass text-ink':'text-paper/45'" class="rounded-lg px-4 py-2 text-sm font-semibold">Festivaluri · 2</button></div><section class="card mt-5 border-brass/20 bg-brass/[.035] p-5"><div class="flex flex-col gap-4 sm:flex-row sm:items-center"><span class="grid h-11 w-11 place-items-center rounded-xl bg-brass/10 text-brass-light"><svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.7" d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9Zm-8 12h4"/></svg></span><div class="flex-1"><strong>Alerte active pentru 4 favorite</strong><p class="mt-1 text-xs text-paper/38">Primești notificări pentru date noi, locuri eliberate și ultimele locuri.</p></div><a href="/cont/setari#notifications" class="text-sm text-brass-light">Gestionează</a></div></section>
<div x-show="tab==='shows'" class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><article class="card card-hover overflow-hidden"><div class="h-36 bg-gradient-to-br from-drama/40 to-ink"></div><div class="p-5"><div class="flex justify-between"><span class="badge bg-drama/15 text-rose-200">DRAMA</span><button @click="showToast('Eliminat din favorite')" class="text-rose-300">♥</button></div><h3 class="mt-3 font-display text-2xl">TOMA</h3><p class="mt-2 text-xs text-paper/38">Următoarea dată: 14 septembrie</p><div class="mt-4 flex items-center justify-between"><span class="badge bg-amber-500/10 text-amber-300">ULTIMELE LOCURI</span><a href="/program" class="text-sm text-brass-light">Detalii →</a></div></div></article><article class="card card-hover overflow-hidden"><div class="h-36 bg-gradient-to-br from-imaginario/40 to-ink"></div><div class="p-5"><div class="flex justify-between"><span class="badge bg-imaginario/15 text-teal-200">IMAGINARIO</span><button @click="showToast('Eliminat din favorite')" class="text-rose-300">♥</button></div><h3 class="mt-3 font-display text-2xl">Cartea Junglei</h3><p class="mt-2 text-xs text-paper/38">Următoarea dată: 3 august</p><div class="mt-4 flex items-center justify-between"><span class="badge bg-emerald-500/10 text-emerald-300">DISPONIBIL</span><a href="/program" class="text-sm text-brass-light">Detalii →</a></div></div></article><article class="card card-hover overflow-hidden"><div class="h-36 bg-gradient-to-br from-revue/40 to-ink"></div><div class="p-5"><div class="flex justify-between"><span class="badge bg-revue/15 text-amber-200">REVISTA</span><button @click="showToast('Eliminat din favorite')" class="text-rose-300">♥</button></div><h3 class="mt-3 font-display text-2xl">Descurcă-lume</h3><p class="mt-2 text-xs text-paper/38">Vânzarea începe în curând.</p><div class="mt-4 flex items-center justify-between"><span class="badge bg-white/5 text-paper/40">ALERTĂ ACTIVĂ</span><a href="/program" class="text-sm text-brass-light">Detalii →</a></div></div></article></div>
<div x-cloak x-show="tab==='artists'" class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><template x-for="name in ['Mihaela Rus','Ioan Coman','Ana Maria Ivan','Cristi Martin']"><article class="card card-hover p-5 text-center"><div class="mx-auto h-24 w-24 rounded-full bg-gradient-to-br from-wine to-panel"></div><h3 class="mt-4 font-display text-xl" x-text="name"></h3><p class="mt-1 text-xs text-paper/38">Actor · Drama</p><button @click="showToast('Preferință actualizată')" class="mt-3 text-sm text-rose-300">♥ Urmărit</button></article></template></div>
<div x-cloak x-show="tab==='festivals'" class="mt-6 grid gap-4 md:grid-cols-2"><article class="card card-hover p-6"><span class="badge bg-brass/10 text-brass-light">FESTIVAL</span><h3 class="mt-4 font-display text-3xl">Festivalul „Toma Caragiu”</h3><p class="mt-3 text-sm text-paper/42">Primești alerta când se publică programul ediției următoare.</p></article><article class="card card-hover p-6"><span class="badge bg-imaginario/15 text-teal-200">FAMILIE</span><h3 class="mt-4 font-display text-3xl">Imaginarium</h3><p class="mt-3 text-sm text-paper/42">Program, ateliere și spectacole pentru copii.</p></article></div></div>
<?php require __DIR__ . '/_inc/bottom.php'; ?>
