<?php
/**
 * GitHub Webhook Auto-Deploy (FTP-only servers)
 *
 * Descarcă ZIP-ul branch-ului marketplace și extrage fișierele.
 * Nu necesită SSH sau Git pe server.
 *
 * SETUP:
 * 1. Urcă acest fișier pe server: bilete.online/_webhook-deploy.php
 * 2. Pune secretul în data/deploy-secret.php pe server (vezi mai jos), NU în acest fișier
 * 3. GitHub repo → Settings → Webhooks → Add webhook:
 *    - Payload URL: https://bilete.online/_webhook-deploy.php
 *    - Content type: application/json
 *    - Secret: (același cu DEPLOY_SECRET)
 *    - Events: Just the push event
 *
 * Deploy-urile nu se mai pot suprapune (2026-09-15: GitHub a trimis același push de două ori în aceeași secundă, cele
 * două rulări au folosit aceleași fișiere temporare și a doua a golit site-ul):
 * - un singur deploy o dată: lacăt în data/deploy.lock, a doua livrare așteaptă să termine prima;
 * - un commit instalat deja în ultimele DUPLICATE_WINDOW secunde este sărit (livrare dublă); un Redeliver făcut mai
 *   târziu sau „Test Manual Deploy” instalează din nou;
 * - fiecare rulare are fișierele ei temporare, șterse și când deploy-ul se oprește cu eroare;
 * - un ZIP care nu arată ca site-ul (sub MIN_FILES fișiere, fără index.php / .htaccess) e refuzat înainte să fie atins
 *   ceva pe server;
 * - fișierele se înlocuiesc pe loc (copiere în fișier temporar + rename), .htaccess la final, apoi se șterg doar
 *   fișierele care nu mai sunt în repo: site-ul nu mai rămâne gol nici măcar o clipă. Dacă vreun fișier nu se poate
 *   scrie, curățarea nu mai rulează și deploy-ul e raportat ca eșuat.
 */

// ===================== CONFIGURATION =====================

// Secret shared with the GitHub webhook. Not committed, because the repository is public: it comes
// from the DEPLOY_SECRET environment variable or from data/deploy-secret.php on the server, a file
// containing only  <?php return 'the-secret';  (a PHP file, so fetching it over the web shows nothing).
$deploySecretFile = __DIR__ . '/data/deploy-secret.php';
define('DEPLOY_SECRET', (string) (getenv('DEPLOY_SECRET') ?: (is_file($deploySecretFile) ? (include $deploySecretFile) : '')));

// GitHub repo details
define('GITHUB_USER', 'andreiandoo');
define('GITHUB_REPO', 'epas');
define('GITHUB_BRANCH', 'bilete');
define('ZIP_URL', 'https://github.com/' . GITHUB_USER . '/' . GITHUB_REPO . '/archive/refs/heads/' . GITHUB_BRANCH . '.zip');

// Deploy path (unde să extragă fișierele)
define('DEPLOY_PATH', __DIR__);

// Fișiere/foldere de pe primul nivel care NU se ating la deploy (relative la DEPLOY_PATH)
// NOTĂ: .htaccess NU mai e protejat - se actualizează din repo
define('PRESERVE_FILES', [
    '_webhook-deploy.php',
    'deploy.log',
    'wp-config.php',      // dacă ai WordPress
    'configuration.php',  // dacă ai Joomla
    'uploads',            // foldere cu upload-uri
    'media',
    // Runtime state generated by the marketplace itself — must survive every
    // deploy or organizers lose their share-links.json, rate-limit counters,
    // and brute-force lockouts on each push.
    'data',
    'cache',
]);

// Log file
define('LOG_FILE', __DIR__ . '/deploy.log');

// One deploy at a time, and what was installed last (both in data/, which deploys never touch)
define('STATE_DIR', is_dir(__DIR__ . '/data') && is_writable(__DIR__ . '/data') ? __DIR__ . '/data' : sys_get_temp_dir());
define('LOCK_FILE', STATE_DIR . '/deploy.lock');
define('STATE_FILE', STATE_DIR . '/deploy-state.json');
define('DUPLICATE_WINDOW', 600); // s: the same commit delivered again within this time is a duplicate

// A ZIP that doesn't look like the site is never installed
define('MIN_FILES', 100);
define('REQUIRED_FILES', ['index.php', '.htaccess']);

// ===================== FUNCTIONS =====================

function logMsg($msg, $type = 'INFO') {
    $line = "[" . date('Y-m-d H:i:s') . "] [$type] $msg\n";
    file_put_contents(LOG_FILE, $line, FILE_APPEND | LOCK_EX);
    if ($type === 'ERROR') {
        http_response_code(500);
        die(json_encode(['success' => false, 'error' => $msg]));
    }
}

function verifySignature($payload, $signature) {
    if (empty($signature)) return false;
    $expected = 'sha256=' . hash_hmac('sha256', $payload, DEPLOY_SECRET);
    return hash_equals($expected, $signature);
}

function downloadFile($url, $destination) {
    $ch = curl_init($url);
    $fp = fopen($destination, 'w');
    if (!$fp) return false;
    curl_setopt_array($ch, [
        CURLOPT_FILE => $fp,
        CURLOPT_FOLLOWLOCATION => true,
        CURLOPT_TIMEOUT => 120,
        CURLOPT_CONNECTTIMEOUT => 10,
        CURLOPT_USERAGENT => 'PHP Deploy Script',
        CURLOPT_SSL_VERIFYPEER => true,
    ]);
    $success = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    fclose($fp);
    if (!$success || $httpCode >= 400) {
        @unlink($destination);
        return false;
    }
    return true;
}

/** Path relative to a root, always with "/" */
function relativeTo($root, $path) {
    return str_replace('\\', '/', substr($path, strlen($root) + 1));
}

/** True for a preserved first-level entry or anything inside it */
function isPreserved($relativePath) {
    foreach (PRESERVE_FILES as $preserved) {
        if ($relativePath === $preserved || strpos($relativePath, $preserved . '/') === 0) {
            return true;
        }
    }
    return false;
}

/**
 * Writes every file of $src over DEPLOY_PATH in place: each file is copied next to its target under a temporary name
 * and renamed over it, so a visitor gets either the old file or the new one. .htaccess files go last, once the files
 * their rules point to are there. Returns [entries now in the site (relative => true), entries that failed].
 */
function installFiles($src, $runId) {
    $wanted = [];
    $failed = [];
    $late = [];
    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($src, FilesystemIterator::SKIP_DOTS),
        RecursiveIteratorIterator::SELF_FIRST
    );
    $put = function ($from, $rel) use (&$wanted, &$failed, $runId) {
        $dst = DEPLOY_PATH . '/' . $rel;
        if (is_dir($dst) && !is_link($dst)) {
            cleanupTemp($dst); // a folder that became a file
        }
        $tmp = $dst . '.deploy-' . $runId;
        if (@copy($from, $tmp) && @rename($tmp, $dst)) {
            $wanted[$rel] = true;
        } else {
            @unlink($tmp);
            $failed[] = $rel;
        }
    };
    foreach ($iterator as $item) {
        $rel = relativeTo($src, $item->getPathname());
        if (isPreserved($rel)) continue;
        if ($item->isDir()) {
            $dst = DEPLOY_PATH . '/' . $rel;
            if (is_file($dst) || is_link($dst)) {
                @unlink($dst); // a file that became a folder
            }
            if (is_dir($dst) || @mkdir($dst, 0755, true)) {
                $wanted[$rel] = true;
            } else {
                $failed[] = $rel . '/';
            }
            continue;
        }
        if ($item->getFilename() === '.htaccess') {
            $late[$rel] = $item->getPathname();
            continue;
        }
        $put($item->getPathname(), $rel);
    }
    foreach ($late as $rel => $from) {
        $put($from, $rel);
    }
    return [$wanted, $failed];
}

/** Removes what the new release no longer has (files, then folders left empty); preserved entries are never read. */
function removeStale(array $wanted) {
    $removed = 0;
    foreach (scandir(DEPLOY_PATH) as $top) {
        if ($top === '.' || $top === '..' || isPreserved($top)) continue;
        $path = DEPLOY_PATH . '/' . $top;
        if (is_dir($path) && !is_link($path)) {
            $iterator = new RecursiveIteratorIterator(
                new RecursiveDirectoryIterator($path, FilesystemIterator::SKIP_DOTS),
                RecursiveIteratorIterator::CHILD_FIRST
            );
            foreach ($iterator as $item) {
                $rel = relativeTo(DEPLOY_PATH, $item->getPathname());
                if (isset($wanted[$rel])) continue;
                if ($item->isDir() && !$item->isLink()) {
                    if (@rmdir($item->getPathname())) $removed++;
                } elseif (@unlink($item->getPathname())) {
                    $removed++;
                }
            }
            if (!isset($wanted[$top]) && @rmdir($path)) $removed++;
        } elseif (!isset($wanted[$top]) && @unlink($path)) {
            $removed++;
        }
    }
    return $removed;
}

function cleanupTemp($path) {
    if (!is_dir($path)) {
        @unlink($path);
        return;
    }

    $items = scandir($path);
    foreach ($items as $item) {
        if ($item === '.' || $item === '..') continue;
        $itemPath = $path . DIRECTORY_SEPARATOR . $item;
        if (is_dir($itemPath)) {
            cleanupTemp($itemPath);
        } else {
            @unlink($itemPath);
        }
    }
    @rmdir($path);
}

// ===================== STATUS PAGE (GET) =====================

// The status page, its logs and the manual deploy are only for someone holding the secret.
$hasKey = DEPLOY_SECRET !== '' && hash_equals(DEPLOY_SECRET, (string) ($_GET['key'] ?? ''));

if ($_SERVER['REQUEST_METHOD'] === 'GET') {
    if (!$hasKey) {
        http_response_code(404);
        exit;
    }
    header('Content-Type: text/html; charset=utf-8');
    ?>
    <!DOCTYPE html>
    <html>
    <head>
        <title>Deploy Status - bilete.online</title>
        <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; background: #f5f5f5; }
            .card { background: white; border-radius: 8px; padding: 20px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
            h1 { color: #333; margin-top: 0; }
            .status { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 14px; font-weight: 500; }
            .status.active { background: #d4edda; color: #155724; }
            pre { background: #1e1e1e; color: #d4d4d4; padding: 15px; border-radius: 6px; overflow-x: auto; font-size: 13px; max-height: 400px; overflow-y: auto; }
            .info { color: #666; font-size: 14px; }
            .btn { display: inline-block; padding: 10px 20px; background: #007bff; color: white; border-radius: 6px; text-decoration: none; font-weight: 500; }
            .btn:hover { background: #0056b3; }
        </style>
    </head>
    <body>
        <div class="card">
            <h1>🚀 Deploy Webhook <span class="status active">Active</span></h1>
            <p class="info">
                <strong>Branch:</strong> <?= GITHUB_BRANCH ?><br>
                <strong>Repo:</strong> <?= GITHUB_USER ?>/<?= GITHUB_REPO ?><br>
                <strong>Deploy path:</strong> <?= DEPLOY_PATH ?>
            </p>
            <a href="?test=1&amp;key=<?= htmlspecialchars(urlencode((string) $_GET['key'])) ?>" class="btn">Test Manual Deploy</a>
        </div>

        <?php if (file_exists(LOG_FILE)): ?>
        <div class="card">
            <h2>📋 Recent Logs</h2>
            <pre><?= htmlspecialchars(substr(file_get_contents(LOG_FILE), -10000)) ?></pre>
        </div>
        <?php endif; ?>

        <div class="card">
            <h2>⚙️ Webhook Setup</h2>
            <p class="info">Add this webhook in GitHub repo settings:</p>
            <pre>
Payload URL: <?= (isset($_SERVER['HTTPS']) ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] ?>

Content type: application/json
Secret: [your DEPLOY_SECRET value]
Events: Just the push event</pre>
        </div>
    </body>
    </html>
    <?php

    // Manual test deploy
    if (isset($_GET['test']) && $_GET['test'] === '1' && $hasKey) {
        $_SERVER['REQUEST_METHOD'] = 'POST';
        // Continue to deploy logic below
    } else {
        exit;
    }
}

// ===================== WEBHOOK HANDLER (POST) =====================

$payload = file_get_contents('php://input');
$signature = $_SERVER['HTTP_X_HUB_SIGNATURE_256'] ?? '';
$isManualTest = isset($_GET['test']) && $hasKey;

logMsg("=== Deploy started ===");

// Verify signature (skip for manual test)
if (DEPLOY_SECRET === '') {
    logMsg("DEPLOY_SECRET is not configured (data/deploy-secret.php)", 'ERROR');
}
if (!$isManualTest) {
    if (!verifySignature($payload, $signature)) {
        logMsg("Invalid signature", 'ERROR');
    }
}

// Parse webhook data
$data = json_decode($payload, true);
$branch = '';

if ($data) {
    $ref = $data['ref'] ?? '';
    $branch = str_replace('refs/heads/', '', $ref);
    $pusher = $data['pusher']['name'] ?? 'manual';
    logMsg("Triggered by: $pusher, Branch: $branch");

    if ($branch !== GITHUB_BRANCH && !$isManualTest) {
        logMsg("Ignoring push to branch: $branch");
        echo json_encode(['success' => true, 'message' => 'Ignored: wrong branch']);
        exit;
    }
}

// Keep going if GitHub stops waiting (it gives a delivery 10 s), and give a slow download time to finish
ignore_user_abort(true);
@set_time_limit(300);

$sha = (is_array($data) && preg_match('/^[0-9a-f]{40}$/', (string) ($data['after'] ?? ''))) ? $data['after'] : '';

// One deploy at a time: a second delivery waits here until the first one has finished
$lock = @fopen(LOCK_FILE, 'c');
if (!$lock || !flock($lock, LOCK_EX)) {
    logMsg("Could not take the deploy lock " . LOCK_FILE, 'ERROR');
}

$state = is_file(STATE_FILE) ? json_decode((string) @file_get_contents(STATE_FILE), true) : null;
if (!$isManualTest && $sha !== '' && is_array($state) && ($state['sha'] ?? '') === $sha && time() - (int) ($state['at'] ?? 0) < DUPLICATE_WINDOW) {
    logMsg("Skipped: commit " . substr($sha, 0, 9) . " was installed " . (time() - (int) $state['at']) . " s ago (duplicate delivery)");
    echo json_encode(['success' => true, 'message' => 'Already deployed', 'sha' => $sha]);
    exit;
}

// This run's own temp files, removed however the script ends
$runId = date('YmdHis') . '-' . bin2hex(random_bytes(4));
$zipFile = sys_get_temp_dir() . '/deploy_' . $runId . '.zip';
$extractPath = sys_get_temp_dir() . '/deploy_extract_' . $runId;
register_shutdown_function(function () use ($zipFile, $extractPath) {
    @unlink($zipFile);
    cleanupTemp($extractPath);
});

// Download ZIP from GitHub
logMsg("Run $runId" . ($sha !== '' ? ", commit " . substr($sha, 0, 9) : '') . ". Downloading: " . ZIP_URL);

if (!downloadFile(ZIP_URL, $zipFile)) {
    logMsg("Failed to download ZIP from GitHub", 'ERROR');
}

logMsg("Downloaded to: $zipFile (" . round(filesize($zipFile) / 1024) . " KB)");

// Extract ZIP
$zip = new ZipArchive();

if ($zip->open($zipFile) !== true) {
    logMsg("Failed to open ZIP file", 'ERROR');
}

if (!$zip->extractTo($extractPath)) {
    $zip->close();
    logMsg("Failed to extract the ZIP file", 'ERROR');
}
$zip->close();
@unlink($zipFile);

logMsg("Extracted to: $extractPath");

// Find the extracted folder (GitHub adds repo-branch prefix)
$extractedFolder = $extractPath . '/' . GITHUB_REPO . '-' . GITHUB_BRANCH;

if (!is_dir($extractedFolder)) {
    // Try to find any folder
    $items = scandir($extractPath);
    foreach ($items as $item) {
        if ($item !== '.' && $item !== '..' && is_dir($extractPath . '/' . $item)) {
            $extractedFolder = $extractPath . '/' . $item;
            break;
        }
    }
}

if (!is_dir($extractedFolder)) {
    logMsg("Extracted folder not found", 'ERROR');
}

logMsg("Source folder: $extractedFolder");

// Count files to deploy
$fileCount = 0;
$iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($extractedFolder, FilesystemIterator::SKIP_DOTS));
foreach ($iterator as $file) {
    if ($file->isFile()) $fileCount++;
}
logMsg("Files to deploy: $fileCount");

$missing = array_values(array_filter(REQUIRED_FILES, function ($f) use ($extractedFolder) {
    return !is_file($extractedFolder . '/' . $f);
}));
if ($fileCount < MIN_FILES || $missing) {
    logMsg("Refused: the ZIP has $fileCount files" . ($missing ? ' and no ' . implode(', ', $missing) : '') . ". Nothing on the server was changed", 'ERROR');
}

// Replace the files in place, then remove what the new release no longer has
logMsg("Installing files in place...");
[$wanted, $failed] = installFiles($extractedFolder, $runId);
if ($failed) {
    logMsg(count($failed) . " files could not be written (" . implode(', ', array_slice($failed, 0, 5)) . "). Old files were not removed", 'ERROR');
}
$removed = removeStale($wanted);
logMsg("Installed " . count($wanted) . " files and folders, removed $removed no longer in the repository");

// Clear OPcache if available
if (function_exists('opcache_reset')) {
    opcache_reset();
    logMsg("OPcache cleared");
}

@file_put_contents(STATE_FILE, json_encode(['sha' => $sha, 'at' => time(), 'run' => $runId, 'files' => $fileCount]), LOCK_EX);
logMsg("=== Deploy completed successfully! ===");

flock($lock, LOCK_UN);
fclose($lock);

// Response
http_response_code(200);
header('Content-Type: application/json');
echo json_encode([
    'success' => true,
    'message' => 'Deployed successfully',
    'files' => $fileCount,
    'branch' => GITHUB_BRANCH,
    'sha' => $sha,
]);
