/** @type {import('tailwindcss').Config} */
// bilete.online — Tailwind config
// Palette: editorial paper + ink + vermilion accent + secondary forest/ochre/sky.
// Typography: Fraunces (display serif) + Hanken Grotesk (sans) + Spline Sans Mono.
module.exports = {
  content: [
    './**/*.php',
    './assets/js/**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        paper:        '#F4EFE3',
        'paper-2':    '#EBE2CF',
        'paper-3':    '#E2D7BF',
        ink:          '#1B1714',
        'ink-2':      '#2E2820',
        'ink-soft':   '#5A4F41',
        vermilion:    '#E84527',
        'vermilion-d':'#C5371C',
        forest:       '#1E4A3D',
        'forest-l':   '#2E6553',
        ochre:        '#DA9A33',
        sky:          '#2C5F8A',
        // Legacy semantic tokens kept for existing JS code (auth, cart, etc.)
        // mapped to the new palette so old class names still render.
        primary:      '#E84527',
        'primary-dark':'#C5371C',
        'primary-light':'#E84527',
        secondary:    '#1B1714',
        accent:       '#DA9A33',
        surface:      '#F4EFE3',
        muted:        '#5A4F41',
        border:       '#E2D7BF',
        success:      '#1E4A3D',
        warning:      '#DA9A33',
        error:        '#E84527',
      },
      fontFamily: {
        display: ['Fraunces', 'Georgia', 'serif'],
        sans:    ['"Hanken Grotesk"', 'system-ui', 'sans-serif'],
        mono:    ['"Spline Sans Mono"', 'ui-monospace', 'monospace'],
      },
      fontWeight: {
        '400': '400',
        '500': '500',
        '600': '600',
        '700': '700',
        '900': '900',
      },
      boxShadow: {
        'ticket': '0 30px 60px -36px rgba(27,23,20,.6)',
        'ticket-lg': '0 45px 85px -40px rgba(27,23,20,.8)',
        'ticket-hover': '0 26px 50px -28px rgba(27,23,20,.55)',
        'logo': '0 6px 14px -6px rgba(232,69,39,.9)',
        'card-cta': '0 22px 50px -32px rgba(27,23,20,.7)',
        'header-scroll': '0 10px 30px -22px rgba(27,23,20,.6)',
        'mega': '0 40px 80px -40px rgba(27,23,20,.7)',
      },
    },
    screens: {
      mobile: { max: "768px" },
      xs: "480px",
      sm: "600px",
      md: "782px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1440px",
    },
  },
  // Safelist for dynamic class strings built in JS / Alpine x-bind
  safelist: [
    // Grid columns used dynamically
    'grid-cols-1', 'grid-cols-2', 'grid-cols-3', 'grid-cols-4', 'grid-cols-5',
    'lg:grid-cols-2', 'lg:grid-cols-3', 'lg:grid-cols-4', 'lg:grid-cols-5',
    'md:grid-cols-2', 'md:grid-cols-3', 'md:grid-cols-4',
    'xl:grid-cols-5',
    // Common dynamic widths
    'w-1/2', 'w-1/3', 'w-1/4', 'w-2/3', 'w-3/4', 'w-full',
    'md:w-1/4', 'md:w-1/3', 'md:w-1/2', 'md:w-2/5', 'md:w-3/5', 'md:w-3/4',
    'opacity-0', 'opacity-100',
    'aspect-square', 'aspect-video',
    'gap-2', 'gap-3', 'gap-4', 'gap-5', 'gap-6', 'gap-8', 'gap-10',
    'p-2', 'p-3', 'p-4', 'p-6', 'p-8',
    'px-2', 'px-3', 'px-4', 'px-6', 'px-8',
    'py-1', 'py-2', 'py-3', 'py-4', 'py-6', 'py-8',
    'mb-2', 'mb-3', 'mb-4', 'mb-6', 'mb-8',
    'mt-2', 'mt-4', 'mt-6', 'mt-8',
    'h-32', 'h-34', 'h-40', 'h-52', 'h-64', 'h-72', 'h-96',
    'text-xs', 'text-sm', 'text-base', 'text-lg', 'text-xl', 'text-2xl', 'text-3xl', 'text-4xl',
    'font-400', 'font-500', 'font-600', 'font-700', 'font-900',
    'transition-all', 'transition-colors', 'transition-transform', 'transition-opacity',
    'duration-200', 'duration-300', 'duration-500', 'duration-700',
    'rounded-lg', 'rounded-xl', 'rounded-2xl', 'rounded-3xl', 'rounded-full',
    'absolute', 'relative', 'fixed', 'sticky',
    'hidden', 'block', 'flex', 'grid', 'inline-flex',
    'flex-col', 'flex-row', 'flex-wrap', 'flex-shrink-0', 'flex-1',
    'items-center', 'items-start', 'items-end',
    'justify-center', 'justify-between', 'justify-start',
    'overflow-hidden', 'overflow-x-auto', 'overflow-y-auto',
    'object-cover', 'object-contain',
    'border', 'border-t', 'border-b', 'border-l', 'border-r', 'border-2',
    'z-10', 'z-20', 'z-30', 'z-40', 'z-50',
    'line-clamp-1', 'line-clamp-2', 'line-clamp-3', 'truncate',
    'max-w-none', 'max-w-md', 'max-w-7xl',
    'invisible', 'visible',
    // Alpine x-bind colors used in category cards / experience tiles
    'bg-vermilion', 'bg-vermilion-d', 'bg-forest', 'bg-forest-l', 'bg-ochre', 'bg-sky', 'bg-ink', 'bg-ink-2', 'bg-paper', 'bg-paper-2', 'bg-paper-3',
    'text-vermilion', 'text-vermilion-d', 'text-forest', 'text-forest-l', 'text-ochre', 'text-sky', 'text-ink', 'text-ink-2', 'text-ink-soft', 'text-paper',
    'border-vermilion', 'border-forest', 'border-ochre', 'border-sky', 'border-ink', 'border-paper',
    'from-vermilion', 'to-vermilion-d', 'from-forest-l', 'to-forest', 'from-sky', 'to-ink', 'from-ochre',
    'hover:bg-vermilion', 'hover:bg-vermilion-d', 'hover:bg-ink', 'hover:bg-ink-2', 'hover:bg-paper-2',
    'hover:text-paper', 'hover:text-vermilion', 'hover:border-vermilion',
    'rotate-180', 'rotate-3', 'rotate-6', 'rotate-12', '-rotate-3', '-rotate-6', '-rotate-12', 'rotate-45',
    {
      pattern: /bg-(paper|paper-2|paper-3|ink|ink-2|vermilion|vermilion-d|forest|forest-l|ochre|sky)\/(5|10|15|20|25|30|40|50|60|70|75|80|85|90|95)/,
    },
    {
      pattern: /text-(paper|paper-2|paper-3|ink|ink-2|ink-soft|vermilion|vermilion-d|forest|forest-l|ochre|sky)\/(30|40|50|60|70|75|80|85|90|95)/,
    },
    {
      pattern: /border-(paper|paper-2|ink|ink-2|vermilion|forest|ochre|sky)\/(5|10|15|20|25|30|40|50)/,
    },
  ],
  plugins: [],
}
